/* Generated by GOB (v2.0.6) on Tue Jan  6 19:47:07 2004
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 6

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "xfce-mixer-settingsbox.h"

#include "xfce-mixer-settingsbox-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-settingsbox.gob"

#include <gtk/gtk.h>
#include <libxfce4util/i18n.h>
#include <libxfcegui4/xfce_framebox.h>
#include <libxfce4mcs/mcs-manager.h>

#line 34 "xfce-mixer-settingsbox.c"

#line 7 "mixer-settingsbox.gob"

#include "helpers3.inc"
#include "vc.h"
#include "stringlist.inc"

#undef SHOW_DEFAULT_DEVICE_ENTRY
#define SETTINGS_LIST_SEP "@"
#define CHANNEL "sound"
/*#define TRACE g_warning(s)*/

static void TRACE (gchar const *n)
{
}


#line 52 "xfce-mixer-settingsbox.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_SETTINGSBOX(x)
#define SELF_CONST(x) XFCE_MIXER_SETTINGSBOX_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_SETTINGSBOX(x)
#define TYPE_SELF XFCE_TYPE_MIXER_SETTINGSBOX
#define SELF_CLASS(x) XFCE_MIXER_SETTINGSBOX_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_SETTINGSBOX_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerSettingsbox Self;
typedef XfceMixerSettingsboxClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_settingsbox_class_init (XfceMixerSettingsboxClass * c) G_GNUC_UNUSED;
static void xfce_mixer_settingsbox_init (XfceMixerSettingsbox * self) G_GNUC_UNUSED;
static void xfce_mixer_settingsbox_device_changed_d_cb (XfceMixerSettingsbox * self, gpointer user_data) G_GNUC_UNUSED;
static void xfce_mixer_settingsbox_device_changed_t_cb (XfceMixerSettingsbox * self, GtkTreeSelection * arg1) G_GNUC_UNUSED;
static gchar * xfce_mixer_settingsbox_mcs_s_name (XfceMixerSettingsbox * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkVBoxClass *parent_class = NULL;

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define self_load(args...) xfce_mixer_settingsbox_load(args)
#define self_save(args...) xfce_mixer_settingsbox_save(args)
#define self_device_changed_d_cb(args...) xfce_mixer_settingsbox_device_changed_d_cb(args)
#define self_device_changed_t_cb(args...) xfce_mixer_settingsbox_device_changed_t_cb(args)
#define self_device_changed_cb(args...) xfce_mixer_settingsbox_device_changed_cb(args)
#define self_devicelst_updated(args...) xfce_mixer_settingsbox_devicelst_updated(args)
#define self_mcs_s_name(args...) xfce_mixer_settingsbox_mcs_s_name(args)
#define self_fill_right_box(args...) xfce_mixer_settingsbox_fill_right_box(args)
#define self_apply_right_box(args...) xfce_mixer_settingsbox_apply_right_box(args)
#define self_new() xfce_mixer_settingsbox_new()
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static void (* const self_load) (XfceMixerSettingsbox * self) = xfce_mixer_settingsbox_load;
static void (* const self_save) (XfceMixerSettingsbox * self) = xfce_mixer_settingsbox_save;
static void (* const self_device_changed_d_cb) (XfceMixerSettingsbox * self, gpointer user_data) = xfce_mixer_settingsbox_device_changed_d_cb;
static void (* const self_device_changed_t_cb) (XfceMixerSettingsbox * self, GtkTreeSelection * arg1) = xfce_mixer_settingsbox_device_changed_t_cb;
static void (* const self_device_changed_cb) (XfceMixerSettingsbox * self) = xfce_mixer_settingsbox_device_changed_cb;
static void (* const self_devicelst_updated) (XfceMixerSettingsbox * self) = xfce_mixer_settingsbox_devicelst_updated;
static gchar * (* const self_mcs_s_name) (XfceMixerSettingsbox * self) = xfce_mixer_settingsbox_mcs_s_name;
static void (* const self_fill_right_box) (XfceMixerSettingsbox * self) = xfce_mixer_settingsbox_fill_right_box;
static void (* const self_apply_right_box) (XfceMixerSettingsbox * self) = xfce_mixer_settingsbox_apply_right_box;
static XfceMixerSettingsbox * (* const self_new) (void) = xfce_mixer_settingsbox_new;

GType
xfce_mixer_settingsbox_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerSettingsboxClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_settingsbox_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerSettingsbox),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_settingsbox_init,
		};

		type = g_type_register_static (GTK_TYPE_VBOX, "XfceMixerSettingsbox", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerSettingsbox *)g_object_new(xfce_mixer_settingsbox_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerSettingsbox * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerSettingsbox *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerSettingsbox *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerSettingsbox *)g_object_new_valist (xfce_mixer_settingsbox_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::finalize"
	XfceMixerSettingsbox *self = XFCE_MIXER_SETTINGSBOX (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 37 "mixer-settingsbox.gob"
	if(self->device_lst) { ((*(void (*)(void *))stringlist_free)) (self->device_lst); self->device_lst = NULL; }
#line 153 "xfce-mixer-settingsbox.c"
#line 39 "mixer-settingsbox.gob"
	if(self->sel_device) { ((*(void (*)(void *))g_free)) (self->sel_device); self->sel_device = NULL; }
#line 156 "xfce-mixer-settingsbox.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__

static void 
xfce_mixer_settingsbox_class_init (XfceMixerSettingsboxClass * c)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::class_init"
	GObjectClass *g_object_class = (GObjectClass*) c;

	parent_class = g_type_class_ref (GTK_TYPE_VBOX);

	g_object_class->finalize = ___finalize;
	return;
	c = NULL;
	g_object_class = NULL;
}
#undef __GOB_FUNCTION__
#line 59 "mixer-settingsbox.gob"
static void 
xfce_mixer_settingsbox_init (XfceMixerSettingsbox * self)
#line 179 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::init"
#line 7 "mixer-settingsbox.gob"
	self->dev_frame = NULL;
#line 184 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->dev_label = NULL;
#line 187 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->useful_frame = NULL;
#line 190 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->useful_tv = NULL;
#line 193 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->useful_model = NULL;
#line 196 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->useful_sc = NULL;
#line 199 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->devlist_model = NULL;
#line 202 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->devlist_tv = NULL;
#line 205 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->devlist_sc = NULL;
#line 208 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->cols = NULL;
#line 211 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->right_box = NULL;
#line 214 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->sep = NULL;
#line 217 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->device_lst = NULL;
#line 220 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->sel_device = NULL;
#line 223 "xfce-mixer-settingsbox.c"
#line 7 "mixer-settingsbox.gob"
	self->manager = NULL;
#line 226 "xfce-mixer-settingsbox.c"
 {
#line 60 "mixer-settingsbox.gob"

		GtkTreeSelection *sels;

		self->cols = GTK_BOX (gtk_hbox_new (FALSE, 5));
		gtk_widget_show (GTK_WIDGET (self->cols));

		self->sep = gtk_vseparator_new ();
		gtk_widget_show (GTK_WIDGET (self->sep));

		self->devlist_tv = GTK_TREE_VIEW (gtk_tree_view_new ());
		gtk_tree_view_append_column (self->devlist_tv, 
			tree_new_text_column (_ ("Device"), 0
			)
		);

		gtk_widget_show (GTK_WIDGET (self->devlist_tv));

		self->devlist_sc = GTK_SCROLLED_WINDOW (gtk_scrolled_window_new (NULL, NULL));
		gtk_scrolled_window_set_policy (self->devlist_sc, GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
		gtk_container_add (GTK_CONTAINER (self->devlist_sc), GTK_WIDGET (self->devlist_tv));
		gtk_widget_show (GTK_WIDGET (self->devlist_sc));

		self->devlist_model = GTK_TREE_STORE (gtk_tree_store_new (1, G_TYPE_STRING));
		gtk_tree_view_set_model (self->devlist_tv, GTK_TREE_MODEL (self->devlist_model));

		self->right_box = GTK_BOX (gtk_vbox_new (FALSE, 5));
		gtk_widget_show (GTK_WIDGET (self->right_box));

		self->dev_frame = xfce_framebox_new (_ ("Device"), TRUE);
		gtk_widget_show (GTK_WIDGET (self->dev_frame));

		self->dev_label = GTK_LABEL (gtk_label_new (_("None")));
		gtk_widget_show (GTK_WIDGET (self->dev_label));

		self->useful_frame = xfce_framebox_new (_ ("Useful Controls"), TRUE);
		gtk_widget_show (GTK_WIDGET (self->useful_frame));

		self->useful_tv = GTK_TREE_VIEW (gtk_tree_view_new ());

		gtk_tree_view_set_headers_visible (self->useful_tv, FALSE);

		gtk_widget_show (GTK_WIDGET (self->useful_tv));

		self->useful_model = GTK_TREE_STORE (gtk_tree_store_new (2, G_TYPE_BOOLEAN, G_TYPE_STRING));
		gtk_tree_view_set_model (self->useful_tv, GTK_TREE_MODEL (self->useful_model));

		gtk_tree_view_append_column (self->useful_tv, 
			tree_new_check_column ("", 0, GTK_TREE_MODEL (self->useful_model)
		));
		gtk_tree_view_append_column (self->useful_tv, 
			tree_new_text_column ("", 1
		));


		self->useful_sc = GTK_SCROLLED_WINDOW (gtk_scrolled_window_new (NULL, NULL));
		gtk_scrolled_window_set_policy (self->useful_sc, GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
		gtk_container_add (GTK_CONTAINER (self->useful_sc), GTK_WIDGET (self->useful_tv));
		gtk_widget_show (GTK_WIDGET (self->useful_sc));

		xfce_framebox_add (XFCE_FRAMEBOX (self->useful_frame), GTK_WIDGET (self->useful_sc));
		xfce_framebox_add (XFCE_FRAMEBOX (self->dev_frame), GTK_WIDGET (self->dev_label));

		gtk_box_pack_start (GTK_BOX (self->right_box), GTK_WIDGET (self->dev_frame), FALSE, FALSE, 0);
		gtk_box_pack_start (GTK_BOX (self->right_box), GTK_WIDGET (self->useful_frame), TRUE, TRUE, 0);

		gtk_box_pack_start (GTK_BOX (self->cols), GTK_WIDGET (self->devlist_sc), FALSE, FALSE, 0);
		gtk_box_pack_start (GTK_BOX (self->cols), GTK_WIDGET (self->sep), FALSE, FALSE, 0);
		gtk_box_pack_start (GTK_BOX (self->cols), GTK_WIDGET (self->right_box), FALSE, FALSE, 0);

		/*g_signal_connect_swapped (G_OBJECT (self->devlist_model), "row-changed", G_CALLBACK (self_device_changed_t_cb), self);*/

		sels = gtk_tree_view_get_selection (self->devlist_tv);
		if (sels) {
			g_signal_connect_swapped (G_OBJECT (sels), "changed", G_CALLBACK (self_device_changed_t_cb), self);
		}

		g_signal_connect_swapped (G_OBJECT (self), "destroy", G_CALLBACK (self_device_changed_d_cb), self);

		gtk_box_pack_start (GTK_BOX (self), GTK_WIDGET (self->cols), TRUE, TRUE, 0);

		/*self_devicelst_updated (self);*/

		gtk_widget_set_size_request (GTK_WIDGET (self), -1, 300);
	
#line 313 "xfce-mixer-settingsbox.c"
 }
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__


#line 43 "mixer-settingsbox.gob"
void 
xfce_mixer_settingsbox_load (XfceMixerSettingsbox * self)
#line 324 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::load"
#line 43 "mixer-settingsbox.gob"
	g_return_if_fail (self != NULL);
#line 43 "mixer-settingsbox.gob"
	g_return_if_fail (XFCE_IS_MIXER_SETTINGSBOX (self));
#line 331 "xfce-mixer-settingsbox.c"
{
#line 44 "mixer-settingsbox.gob"
	
		if (!self->manager)
			return;

		self_devicelst_updated (self);
	}}
#line 340 "xfce-mixer-settingsbox.c"
#undef __GOB_FUNCTION__

#line 51 "mixer-settingsbox.gob"
void 
xfce_mixer_settingsbox_save (XfceMixerSettingsbox * self)
#line 346 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::save"
#line 51 "mixer-settingsbox.gob"
	g_return_if_fail (self != NULL);
#line 51 "mixer-settingsbox.gob"
	g_return_if_fail (XFCE_IS_MIXER_SETTINGSBOX (self));
#line 353 "xfce-mixer-settingsbox.c"
{
#line 52 "mixer-settingsbox.gob"
	
		if (!self->manager)
			return;

		self_device_changed_cb (self);
	}}
#line 362 "xfce-mixer-settingsbox.c"
#undef __GOB_FUNCTION__


#line 145 "mixer-settingsbox.gob"
static void 
xfce_mixer_settingsbox_device_changed_d_cb (XfceMixerSettingsbox * self, gpointer user_data)
#line 369 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::device_changed_d_cb"
#line 145 "mixer-settingsbox.gob"
	g_return_if_fail (self != NULL);
#line 145 "mixer-settingsbox.gob"
	g_return_if_fail (XFCE_IS_MIXER_SETTINGSBOX (self));
#line 376 "xfce-mixer-settingsbox.c"
{
#line 146 "mixer-settingsbox.gob"
	
		self_device_changed_cb (self);
	}}
#line 382 "xfce-mixer-settingsbox.c"
#undef __GOB_FUNCTION__

#line 150 "mixer-settingsbox.gob"
static void 
xfce_mixer_settingsbox_device_changed_t_cb (XfceMixerSettingsbox * self, GtkTreeSelection * arg1)
#line 388 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::device_changed_t_cb"
#line 150 "mixer-settingsbox.gob"
	g_return_if_fail (self != NULL);
#line 150 "mixer-settingsbox.gob"
	g_return_if_fail (XFCE_IS_MIXER_SETTINGSBOX (self));
#line 395 "xfce-mixer-settingsbox.c"
{
#line 153 "mixer-settingsbox.gob"
	
		self_device_changed_cb (self);
	}}
#line 401 "xfce-mixer-settingsbox.c"
#undef __GOB_FUNCTION__

#line 157 "mixer-settingsbox.gob"
void 
xfce_mixer_settingsbox_device_changed_cb (XfceMixerSettingsbox * self)
#line 407 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::device_changed_cb"
#line 157 "mixer-settingsbox.gob"
	g_return_if_fail (self != NULL);
#line 157 "mixer-settingsbox.gob"
	g_return_if_fail (XFCE_IS_MIXER_SETTINGSBOX (self));
#line 414 "xfce-mixer-settingsbox.c"
{
#line 158 "mixer-settingsbox.gob"
	
		GtkTreeSelection *sels;
		GtkTreeModel *m;
		GtkTreeIter iter;
		gchar *s;
		GList *g;
		GList *cl;
		volcontrol_t *vci;
		TRACE ("enter device_changed_cb");

		self_apply_right_box (self);

		sels = gtk_tree_view_get_selection (self->devlist_tv);
		if (!sels)
			return;

		if (!gtk_tree_selection_get_selected (sels, &m, &iter))
			return;

		TRACE ("read selected device string");
		gtk_tree_model_get (m, &iter, 0, &s, -1);
		TRACE ("read selected device string ok");
		if (s) {
			TRACE (s);
			TRACE ("set dev_label");

			gtk_label_set_text (self->dev_label, s);
			TRACE ("set vc device");
			vc_set_device (s);
			TRACE ("free sel_device");
			if (self->sel_device) {
				g_free (self->sel_device);
				self->sel_device = NULL;
			}
			TRACE ("set sel_device");
			self->sel_device = g_strdup (s);
			TRACE ("free selected device string");

			g_free (s);
		}

		TRACE ("fill useful controls list");
		/* fill "useful controls" list */
		gtk_tree_store_clear (self->useful_model);

		cl = vc_get_control_list ();
		g = cl;
		while (g) {
			vci = (volcontrol_t *) g->data;

			if (vci && vci->name) {
				gtk_tree_store_append (self->useful_model, &iter, NULL);
				gtk_tree_store_set (self->useful_model, &iter, 
					0, TRUE,
					1, vci->name, 
				-1);

			}

			g = g_list_next (g);
		}
		TRACE ("fill vccl");
		if (cl)
			vc_free_control_list (cl);

		TRACE ("fill right_box soon");
		self_fill_right_box (self);
		TRACE ("leave device_changed_cb");

		mcs_manager_notify (self->manager, CHANNEL);
	}}
#line 488 "xfce-mixer-settingsbox.c"
#undef __GOB_FUNCTION__

#line 230 "mixer-settingsbox.gob"
void 
xfce_mixer_settingsbox_devicelst_updated (XfceMixerSettingsbox * self)
#line 494 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::devicelst_updated"
#line 230 "mixer-settingsbox.gob"
	g_return_if_fail (self != NULL);
#line 230 "mixer-settingsbox.gob"
	g_return_if_fail (XFCE_IS_MIXER_SETTINGSBOX (self));
#line 501 "xfce-mixer-settingsbox.c"
{
#line 231 "mixer-settingsbox.gob"
	
		GList *g;
		gchar const *s;
		GtkTreeIter iter;
		/*GtkTreeSelection *sels;*/
		if (self->device_lst) {
			stringlist_free (self->device_lst);
			self->device_lst = NULL;
		}
		TRACE ("enter devicelst_updated");
		self->device_lst = vc_get_device_list ();
		gtk_tree_store_clear (self->devlist_model);
		/*sels = gtk_tree_view_get_selection (self->devlist_tv);*/
		g = self->device_lst;
		while (g) {
			s = (gchar const *) g->data;
			if (s
#ifndef SHOW_DEFAULT_DEVICE_ENTRY
	&& !g_str_equal (s, "default")
#endif
			) {
				TRACE ("before append");
				gtk_tree_store_append (self->devlist_model, &iter, NULL);
				TRACE ("before set");
				gtk_tree_store_set (self->devlist_model, &iter, 0, s, -1);

				/*if (sels) {
					gtk_tree_selection_select_iter (sels, &iter);
					self_device_changed_cb (self);
				}*/
			}

			g = g_list_next (g);
		}
		/*if (sels && gtk_tree_model_get_iter_first (GTK_TREE_MODEL (self->devlist_model), &iter))
			gtk_tree_selection_select_iter (sels, &iter);*/
		TRACE ("leave devicelst_updated");
	}}
#line 542 "xfce-mixer-settingsbox.c"
#undef __GOB_FUNCTION__

#line 270 "mixer-settingsbox.gob"
static gchar * 
xfce_mixer_settingsbox_mcs_s_name (XfceMixerSettingsbox * self)
#line 548 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::mcs_s_name"
#line 270 "mixer-settingsbox.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 270 "mixer-settingsbox.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_SETTINGSBOX (self), (gchar * )0);
#line 555 "xfce-mixer-settingsbox.c"
{
#line 271 "mixer-settingsbox.gob"
	
		if (!self->sel_device)
			return NULL;

		return g_strdup_printf ("Sound/Mixer/Useful:%s", self->sel_device);
	}}
#line 564 "xfce-mixer-settingsbox.c"
#undef __GOB_FUNCTION__

#line 278 "mixer-settingsbox.gob"
void 
xfce_mixer_settingsbox_fill_right_box (XfceMixerSettingsbox * self)
#line 570 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::fill_right_box"
#line 278 "mixer-settingsbox.gob"
	g_return_if_fail (self != NULL);
#line 278 "mixer-settingsbox.gob"
	g_return_if_fail (XFCE_IS_MIXER_SETTINGSBOX (self));
#line 577 "xfce-mixer-settingsbox.c"
{
#line 279 "mixer-settingsbox.gob"
	
		gchar *n;
		gchar *s;
		gchar *s2;
		gchar *all;
		gboolean neof;
		gboolean b;
		McsSetting *setting;
		GtkTreeIter iter;
		if (!self->manager)
			return;

		n = self_mcs_s_name (self);
		if (!n)
			return;

	        if ((setting = mcs_manager_setting_lookup(self->manager,
                                        n, CHANNEL)) == NULL
		) {
			self_apply_right_box (self);
		}

	        if ((setting = mcs_manager_setting_lookup(self->manager,
                                        n, CHANNEL)) == NULL
		) {
			g_free (n);
			return;
		}

		g_free (n);

		all = setting->data.v_string;
		if (!all) 
			return;

		TRACE ("mcs_manager_setting_lookup");
		TRACE (all);

		neof = gtk_tree_model_get_iter_first (
			GTK_TREE_MODEL (self->useful_model), &iter);

		while (neof) {
			gtk_tree_model_get (GTK_TREE_MODEL (self->useful_model), 
				&iter, 1, &s, -1);

			b = FALSE;
			if (s) {
				s2 = g_strdup_printf ("%s%s%s", 
					SETTINGS_LIST_SEP,
					s,
					SETTINGS_LIST_SEP);
				g_free (s);
				s = s2;
				s2 = NULL;
			}

			if (s) {
				if (g_strrstr (all, s)) { /*contained*/
					b = TRUE;
				}
				g_free (s);
			}
			gtk_tree_store_set (
				self->useful_model,
				&iter, 
				0, b, -1);
			
			neof = gtk_tree_model_iter_next (GTK_TREE_MODEL (self->useful_model), &iter);
		}
			
		/*g_free (all);*/
		TRACE ("leave fill");
	}}
#line 653 "xfce-mixer-settingsbox.c"
#undef __GOB_FUNCTION__

#line 353 "mixer-settingsbox.gob"
void 
xfce_mixer_settingsbox_apply_right_box (XfceMixerSettingsbox * self)
#line 659 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::apply_right_box"
#line 353 "mixer-settingsbox.gob"
	g_return_if_fail (self != NULL);
#line 353 "mixer-settingsbox.gob"
	g_return_if_fail (XFCE_IS_MIXER_SETTINGSBOX (self));
#line 666 "xfce-mixer-settingsbox.c"
{
#line 354 "mixer-settingsbox.gob"
	
		gchar *n;
		gchar *v;
		gchar *v2;
		gchar *s;
		gboolean b;
		gboolean neof;
		GtkTreeIter iter;
		if (!self->sel_device || !self->manager)
			return;

		TRACE ("enter apply_right_box");

		v = g_strdup ("");

		neof = gtk_tree_model_get_iter_first (
			GTK_TREE_MODEL (self->useful_model), &iter);

		while (neof) {
			gtk_tree_model_get (GTK_TREE_MODEL (self->useful_model), 
				&iter, 0, &b, 1, &s, -1);

			if (s) {
				if (b) {
					v2 = g_strdup_printf("%s%s%s", v, SETTINGS_LIST_SEP, s);
					g_free (v);
					v = v2;
					v2 = NULL;
				}
				g_free (s);
			}			

			neof = gtk_tree_model_iter_next (
				GTK_TREE_MODEL (self->useful_model), &iter);
		}

		v2 = g_strdup_printf("%s%s%s", v, SETTINGS_LIST_SEP,  "");
		g_free (v);
		v = v2;
		v2 = NULL;

		n = self_mcs_s_name (self);
		if (!n)
			return;

		mcs_manager_set_string (self->manager,
                                n, CHANNEL, v);
		TRACE (n);
		TRACE ("mcs_manager_set_string");
		TRACE (v);
		g_free (n);

		TRACE ("leave apply_right_box");
	}}
#line 723 "xfce-mixer-settingsbox.c"
#undef __GOB_FUNCTION__

#line 409 "mixer-settingsbox.gob"
XfceMixerSettingsbox * 
xfce_mixer_settingsbox_new (void)
#line 729 "xfce-mixer-settingsbox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Settingsbox::new"
{
#line 410 "mixer-settingsbox.gob"
	
		return XFCE_MIXER_SETTINGSBOX (GET_NEW);
	}}
#line 737 "xfce-mixer-settingsbox.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___xfce_mixer_settingsbox_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))GET_NEW_VARG)();
	((void (*)(void))self_load)();
	((void (*)(void))self_save)();
	((void (*)(void))self_device_changed_d_cb)();
	((void (*)(void))self_device_changed_t_cb)();
	((void (*)(void))self_device_changed_cb)();
	((void (*)(void))self_devicelst_updated)();
	((void (*)(void))self_mcs_s_name)();
	((void (*)(void))self_fill_right_box)();
	((void (*)(void))self_apply_right_box)();
	((void (*)(void))self_new)();
	___xfce_mixer_settingsbox_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */

