.\" Copyright (c) 2012 Guido Berhoerster <guido+xfce.org@berhoerster.name>
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.\"
.TH XFCE4\-MIXER 1 "1 Aug 2012"
.SH NAME
xfce4\-mixer \- adjust volume levels
.SH SYNOPSIS
\fBxfce4\-mixer\fR
[\fB\-dhV?\fR]
.SH DESCRIPTION
\fBxfce4\-mixer\fR is an audio mixer which allows you to adjust input and
output volume levels on your sound card(s).
.SH OPTIONS
The following options are supported:
.TP
.BR \-d ", " \-\-debug
Print diagnostic output useful for debugging to stderr.
.TP
.BR \-h ", " \-? ", " \-\-help
Print a summary of all command line options and exit.
.TP
.BR \-V ", " \-\-version
Print the version number and exit.
.SH EXIT STATUS
.TP
.B 0
The program has exited normally.
.TP
.B >0
An Error has occurred.
