/* Generated by GOB (v2.0.6)   (do not edit directly) */

#ifndef __XFCE_MIXER_CONTROL_PRIVATE_H__
#define __XFCE_MIXER_CONTROL_PRIVATE_H__

#include "xfce-mixer-control.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>

#line 3 "mixer-control.gob"
#line 18 "xfce-mixer-control-private.h"
struct _XfceMixerControlPrivate {
#line 8 "mixer-control.gob"
	char * location;
#line 10 "mixer-control.gob"
	int orderno;
#line 37 "mixer-control.gob"
	char * vcname;
#line 40 "mixer-control.gob"
	char * value;
#line 28 "xfce-mixer-control-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
