/* Generated by GOB (v2.0.6) on Tue Jan 20 15:50:28 2004
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 6

#define selfp (self->_priv)

#include "xfce-mixer-window.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-window.gob"

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#line 29 "xfce-mixer-window.c"

#line 7 "mixer-window.gob"

#include <gtk/gtk.h>
#include "xfce-mixer-view.h"
#include "xfce-mixer-profile.h"
#include "xfce-mixer-mcs-client.h"

#line 38 "xfce-mixer-window.c"

#line 13 "mixer-window.gob"

#include <gtk/gtk.h>
#include <libxfce4util/i18n.h>
#include "menus.h"
#define CHANNEL "sound"

#line 47 "xfce-mixer-window.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_WINDOW(x)
#define SELF_CONST(x) XFCE_MIXER_WINDOW_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_WINDOW(x)
#define TYPE_SELF XFCE_TYPE_MIXER_WINDOW
#define SELF_CLASS(x) XFCE_MIXER_WINDOW_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_WINDOW_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerWindow Self;
typedef XfceMixerWindowClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_window_class_init (XfceMixerWindowClass * c) G_GNUC_UNUSED;
static void xfce_mixer_window_init (XfceMixerWindow * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkWindowClass *parent_class = NULL;

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define self_new() xfce_mixer_window_new()
#define self_refresh(args...) xfce_mixer_window_refresh(args)
#define self_reset_profile(args...) xfce_mixer_window_reset_profile(args)
#define self_refresh_value(args...) xfce_mixer_window_refresh_value(args)
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static GtkWidget * (* const self_new) (void) = xfce_mixer_window_new;
static void (* const self_refresh) (XfceMixerWindow * self) = xfce_mixer_window_refresh;
static void (* const self_reset_profile) (XfceMixerWindow * self) = xfce_mixer_window_reset_profile;
static void (* const self_refresh_value) (XfceMixerWindow * self, gchar const * vcname) = xfce_mixer_window_refresh_value;

GType
xfce_mixer_window_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerWindowClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_window_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerWindow),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_window_init,
		};

		type = g_type_register_static (GTK_TYPE_WINDOW, "XfceMixerWindow", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerWindow *)g_object_new(xfce_mixer_window_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerWindow * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerWindow *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerWindow *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerWindow *)g_object_new_valist (xfce_mixer_window_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___dispose (GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::dispose"
	XfceMixerWindow *self = XFCE_MIXER_WINDOW (obj_self);
	if (G_OBJECT_CLASS (parent_class)->dispose) \
		(* G_OBJECT_CLASS (parent_class)->dispose) (obj_self);
#line 27 "mixer-window.gob"
	if(self->mcsc) { ((*(void (*)(void *))g_object_unref)) (self->mcsc); self->mcsc = NULL; }
#line 133 "xfce-mixer-window.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__

static void 
xfce_mixer_window_class_init (XfceMixerWindowClass * c)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::class_init"
	GObjectClass *g_object_class = (GObjectClass*) c;

	parent_class = g_type_class_ref (GTK_TYPE_WINDOW);

	g_object_class->dispose = ___dispose;
	return;
	c = NULL;
	g_object_class = NULL;
}
#undef __GOB_FUNCTION__
#line 29 "mixer-window.gob"
static void 
xfce_mixer_window_init (XfceMixerWindow * self)
#line 156 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::init"
#line 13 "mixer-window.gob"
	self->view = NULL;
#line 161 "xfce-mixer-window.c"
#line 13 "mixer-window.gob"
	self->box = NULL;
#line 164 "xfce-mixer-window.c"
#line 13 "mixer-window.gob"
	self->menubar = NULL;
#line 167 "xfce-mixer-window.c"
#line 13 "mixer-window.gob"
	self->profile = NULL;
#line 170 "xfce-mixer-window.c"
#line 13 "mixer-window.gob"
	self->accelgroup = NULL;
#line 173 "xfce-mixer-window.c"
#line 13 "mixer-window.gob"
	self->mcsc = NULL;
#line 176 "xfce-mixer-window.c"
 {
#line 30 "mixer-window.gob"

		self->box = GTK_BOX (gtk_vbox_new (FALSE, 0));
		gtk_widget_show (GTK_WIDGET (self->box));

		self->accelgroup = GTK_ACCEL_GROUP (gtk_accel_group_new ());
		self->menubar = xfce_mixer_create_main_menu (
			GTK_WINDOW (self), self->accelgroup
		);

		gtk_window_add_accel_group (GTK_WINDOW (self), self->accelgroup);

		g_object_unref (G_OBJECT (self->accelgroup));

		/*self->menubar = GTK_MENU_BAR (gtk_menu_bar_new ());*/
		gtk_widget_show (GTK_WIDGET (self->menubar));

		gtk_box_pack_start (self->box, GTK_WIDGET (self->menubar), FALSE, FALSE, 0);


		self->profile = XFCE_MIXER_PROFILE (xfce_mixer_profile_new ("noname"));

		self->view = xfce_mixer_view_new ();
		gtk_widget_set_size_request (GTK_WIDGET (self->view), 600, -1);

		xfce_mixer_view_set_profile (self->view, self->profile);

		gtk_widget_show (GTK_WIDGET (self->view));

		gtk_box_pack_start (self->box, GTK_WIDGET (self->view), TRUE, TRUE, 0);

		gtk_container_add (GTK_CONTAINER (self), GTK_WIDGET (self->box));

		gtk_window_set_title (GTK_WINDOW (self), _("Volume Control"));

		self->mcsc = xfce_mixer_mcs_client_new ();
		g_object_set (self->mcsc, "channel", CHANNEL, NULL);
	
#line 216 "xfce-mixer-window.c"
 }
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__



#line 68 "mixer-window.gob"
GtkWidget * 
xfce_mixer_window_new (void)
#line 228 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::new"
{
#line 69 "mixer-window.gob"
	
		return GTK_WIDGET (GET_NEW);
	}}
#line 236 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 73 "mixer-window.gob"
void 
xfce_mixer_window_refresh (XfceMixerWindow * self)
#line 242 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::refresh"
#line 73 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 73 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 249 "xfce-mixer-window.c"
{
#line 74 "mixer-window.gob"
	
		if (self->profile)
			xfce_mixer_profile_refresh_views (self->profile);
	}}
#line 256 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 79 "mixer-window.gob"
void 
xfce_mixer_window_reset_profile (XfceMixerWindow * self)
#line 262 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::reset_profile"
#line 79 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 79 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 269 "xfce-mixer-window.c"
{
#line 80 "mixer-window.gob"
	
		if (self->view)
			xfce_mixer_view_set_profile (self->view, self->profile);

		if (self->profile)
			xfce_mixer_profile_refresh_views (self->profile);
	}}
#line 279 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 88 "mixer-window.gob"
void 
xfce_mixer_window_refresh_value (XfceMixerWindow * self, gchar const * vcname)
#line 285 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::refresh_value"
#line 88 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 88 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 292 "xfce-mixer-window.c"
{
#line 89 "mixer-window.gob"
	
		if (self->view)
			xfce_mixer_view_refresh_value (self->view, vcname);
	}}
#line 299 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___xfce_mixer_window_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))GET_NEW_VARG)();
	((void (*)(void))self_new)();
	((void (*)(void))self_refresh)();
	((void (*)(void))self_reset_profile)();
	((void (*)(void))self_refresh_value)();
	___xfce_mixer_window_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */

