/* Generated by GOB (v2.0.6) on Wed Jan 21 01:50:38 2004
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 6

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "xfce-mixer-profiles.h"

#include "xfce-mixer-profiles-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-profiles.gob"

#include <gtk/gtk.h>
#include "xfce-mixer-profile.h"
#include "xfce-mixer-pxml.h"

#line 33 "xfce-mixer-profiles.c"

#line 6 "mixer-profiles.gob"

#include <libxfce4util/util.h>
#include <libxfce4util/i18n.h>

#define PROFILES_ROOT "Profiles"
#ifndef MAX_PATH
#define MAX_PATH 4096
#endif

static void profiles_free (GList *profiles)
{
	GList *g;
	g = profiles;
	while (g) {
		g_object_unref (G_OBJECT (g->data));
		g = g_list_next (g);
	}
	g_list_free (profiles);
}


#line 57 "xfce-mixer-profiles.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_PROFILES(x)
#define SELF_CONST(x) XFCE_MIXER_PROFILES_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_PROFILES(x)
#define TYPE_SELF XFCE_TYPE_MIXER_PROFILES
#define SELF_CLASS(x) XFCE_MIXER_PROFILES_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_PROFILES_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerProfiles Self;
typedef XfceMixerProfilesClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_profiles_class_init (XfceMixerProfilesClass * c) G_GNUC_UNUSED;
static void xfce_mixer_profiles_init (XfceMixerProfiles * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define self_clear(args...) xfce_mixer_profiles_clear(args)
#define self_goto_device(args...) xfce_mixer_profiles_goto_device(args)
#define self_load(args...) xfce_mixer_profiles_load(args)
#define self_xml_text_child(args...) xfce_mixer_profiles_xml_text_child(args)
#define self_save(args...) xfce_mixer_profiles_save(args)
#define self_create_profile(args...) xfce_mixer_profiles_create_profile(args)
#define self_get_profile(args...) xfce_mixer_profiles_get_profile(args)
#define self_delete_profile(args...) xfce_mixer_profiles_delete_profile(args)
#define self_set_modified(args...) xfce_mixer_profiles_set_modified(args)
#define self_get_modified(args...) xfce_mixer_profiles_get_modified(args)
#define self_new(args...) xfce_mixer_profiles_new(args)
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static void (* const self_clear) (XfceMixerProfiles * self) = xfce_mixer_profiles_clear;
static void (* const self_goto_device) (XfceMixerProfiles * self) = xfce_mixer_profiles_goto_device;
static void (* const self_load) (XfceMixerProfiles * self) = xfce_mixer_profiles_load;
static void (* const self_xml_text_child) (XfceMixerProfiles * self, gchar const * tagname) = xfce_mixer_profiles_xml_text_child;
static void (* const self_save) (XfceMixerProfiles * self) = xfce_mixer_profiles_save;
static XfceMixerProfile * (* const self_create_profile) (XfceMixerProfiles * self, gchar const * fixedname) = xfce_mixer_profiles_create_profile;
static XfceMixerProfile * (* const self_get_profile) (XfceMixerProfiles * self, gchar const * name) = xfce_mixer_profiles_get_profile;
static void (* const self_delete_profile) (XfceMixerProfiles * self, gchar const * name) = xfce_mixer_profiles_delete_profile;
static void (* const self_set_modified) (XfceMixerProfiles * self, gboolean modi) = xfce_mixer_profiles_set_modified;
static gboolean (* const self_get_modified) (XfceMixerProfiles * self) = xfce_mixer_profiles_get_modified;
static XfceMixerProfiles * (* const self_new) (gchar const * device) = xfce_mixer_profiles_new;

GType
xfce_mixer_profiles_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerProfilesClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_profiles_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerProfiles),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_profiles_init,
		};

		type = g_type_register_static (G_TYPE_OBJECT, "XfceMixerProfiles", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerProfiles *)g_object_new(xfce_mixer_profiles_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerProfiles * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerProfiles *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerProfiles *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerProfiles *)g_object_new_valist (xfce_mixer_profiles_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___dispose (GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::dispose"
	XfceMixerProfiles *self = XFCE_MIXER_PROFILES (obj_self);
	if (G_OBJECT_CLASS (parent_class)->dispose) \
		(* G_OBJECT_CLASS (parent_class)->dispose) (obj_self);
#line 39 "mixer-profiles.gob"
	if(self->xml) { ((*(void (*)(void *))g_object_unref)) (self->xml); self->xml = NULL; }
#line 157 "xfce-mixer-profiles.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::finalize"
	XfceMixerProfiles *self = XFCE_MIXER_PROFILES (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 30 "mixer-profiles.gob"
	if(self->device) { ((*(void (*)(void *))g_free)) (self->device); self->device = NULL; }
#line 173 "xfce-mixer-profiles.c"
#line 32 "mixer-profiles.gob"
	if(self->fname) { ((*(void (*)(void *))g_free)) (self->fname); self->fname = NULL; }
#line 176 "xfce-mixer-profiles.c"
#line 36 "mixer-profiles.gob"
	if(self->profiles) { ((*(void (*)(void *))profiles_free)) (self->profiles); self->profiles = NULL; }
#line 179 "xfce-mixer-profiles.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__

static void 
xfce_mixer_profiles_class_init (XfceMixerProfilesClass * c)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::class_init"
	GObjectClass *g_object_class = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->dispose = ___dispose;
	g_object_class->finalize = ___finalize;
	return;
	c = NULL;
	g_object_class = NULL;
}
#undef __GOB_FUNCTION__
#line 41 "mixer-profiles.gob"
static void 
xfce_mixer_profiles_init (XfceMixerProfiles * self)
#line 203 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::init"
#line 6 "mixer-profiles.gob"
	self->device = NULL;
#line 208 "xfce-mixer-profiles.c"
#line 6 "mixer-profiles.gob"
	self->fname = NULL;
#line 211 "xfce-mixer-profiles.c"
#line 6 "mixer-profiles.gob"
	self->modified = FALSE;
#line 214 "xfce-mixer-profiles.c"
#line 6 "mixer-profiles.gob"
	self->weird_number = 0;
#line 217 "xfce-mixer-profiles.c"
#line 6 "mixer-profiles.gob"
	self->profiles = NULL;
#line 220 "xfce-mixer-profiles.c"
#line 6 "mixer-profiles.gob"
	self->xml = NULL;
#line 223 "xfce-mixer-profiles.c"
 {
#line 42 "mixer-profiles.gob"

		self->fname = xfce_get_userfile ("xfce4-mixer", "profiles.xml", NULL);
		self->xml = xfce_mixer_pxml_new (PROFILES_ROOT);
		g_object_set (G_OBJECT (self->xml), "fname", self->fname, NULL);
	
#line 231 "xfce-mixer-profiles.c"
 }
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__



#line 48 "mixer-profiles.gob"
void 
xfce_mixer_profiles_clear (XfceMixerProfiles * self)
#line 243 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::clear"
#line 48 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 48 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 250 "xfce-mixer-profiles.c"
{
#line 49 "mixer-profiles.gob"
	
		profiles_free (self->profiles);
		self->weird_number = 0;
		self->profiles = NULL;
	}}
#line 258 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 55 "mixer-profiles.gob"
void 
xfce_mixer_profiles_goto_device (XfceMixerProfiles * self)
#line 264 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::goto_device"
#line 55 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 55 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 271 "xfce-mixer-profiles.c"
{
#line 56 "mixer-profiles.gob"
	
		gchar *n;
		xfce_mixer_pxml_goto_root (self->xml);
		xfce_mixer_pxml_goto_children (self->xml);
		while (self->xml->node) {
			if (xfce_mixer_pxml_check_tag (self->xml, "device")) {
				n = xfce_mixer_pxml_get_prop (self->xml, "name");
				if (n && self->device && g_str_equal (n, self->device)) {
					g_free (n);
					return;
				}
				if (n)
					g_free (n);
			}

			xfce_mixer_pxml_goto_next (self->xml);
		}

		/* device does not exist yet in xml */
		self->xml->node = NULL;
		xfce_mixer_pxml_goto_root (self->xml);
		self->xml->node = xfce_mixer_pxml_create_text_child (self->xml, "device", NULL);
		xfce_mixer_pxml_set_prop (self->xml, "name", self->device);
	}}
#line 298 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 81 "mixer-profiles.gob"
void 
xfce_mixer_profiles_load (XfceMixerProfiles * self)
#line 304 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::load"
#line 81 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 81 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 311 "xfce-mixer-profiles.c"
{
#line 82 "mixer-profiles.gob"
	
		gchar *n;
		XfceMixerProfile *p;
		self_clear (self);
		self_goto_device (self);

		xfce_mixer_pxml_goto_children (self->xml);
		while (self->xml->node) {
			if (xfce_mixer_pxml_check_tag (self->xml, "profile")) {
				n = xfce_mixer_pxml_get_prop (self->xml, "name");
				if (n) {
					p = self_create_profile (self, n);
					if (p) {
						/* TODO read data etc */
					}
				}
			}

			xfce_mixer_pxml_goto_next (self->xml);
		}

	}}
#line 336 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 105 "mixer-profiles.gob"
void 
xfce_mixer_profiles_xml_text_child (XfceMixerProfiles * self, gchar const * tagname)
#line 342 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::xml_text_child"
#line 105 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 105 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 349 "xfce-mixer-profiles.c"
{
#line 106 "mixer-profiles.gob"
	
		self->xml->node = xfce_mixer_pxml_create_text_child (self->xml, tagname, NULL);
	}}
#line 355 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 110 "mixer-profiles.gob"
void 
xfce_mixer_profiles_save (XfceMixerProfiles * self)
#line 361 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::save"
#line 110 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 110 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 368 "xfce-mixer-profiles.c"
{
#line 111 "mixer-profiles.gob"
	
		xmlNodePtr profilesx;
		XfceMixerProfile *p;
		GList *g;
		gchar const *n;
		if (!self_get_modified (self))
			return;

		xfce_mixer_pxml_goto_root (self->xml);
		self_goto_device (self);

		profilesx = self->xml->node;

		xfce_mixer_pxml_eat_children (self->xml, NULL);

		g = self->profiles;
		while (g) {
			p = XFCE_MIXER_PROFILE (g->data);

			n = xfce_mixer_profile_get_title (p);
			xfce_mixer_pxml_goto_node (self->xml, profilesx);
			self_xml_text_child (self, "profile");
			xfce_mixer_pxml_set_prop (self->xml, "name", n);

			/* TODO save actual data */

			g = g_list_next (g);
		}

		self_set_modified (self, FALSE);
	}}
#line 402 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 143 "mixer-profiles.gob"
XfceMixerProfile * 
xfce_mixer_profiles_create_profile (XfceMixerProfiles * self, gchar const * fixedname)
#line 408 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::create_profile"
#line 143 "mixer-profiles.gob"
	g_return_val_if_fail (self != NULL, (XfceMixerProfile * )0);
#line 143 "mixer-profiles.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PROFILES (self), (XfceMixerProfile * )0);
#line 415 "xfce-mixer-profiles.c"
{
#line 144 "mixer-profiles.gob"
	
		XfceMixerProfile *p;
		gchar tmp[MAX_PATH];

		if (fixedname)
			g_snprintf (tmp, MAX_PATH, "%s", fixedname);
		else
			g_snprintf (tmp, MAX_PATH, _("profile%d"), ++self->weird_number);

		/* check if name is a dupe */

		p = self_get_profile (self, tmp);
		if (p) {
			g_object_unref (G_OBJECT (p));
			g_snprintf (tmp, MAX_PATH, _("profile%d"), ++self->weird_number);

			p = self_get_profile (self, tmp);
			if (p) { /* hmpf. */
				g_object_unref (G_OBJECT (p));
				return NULL;
			}
		}

		p = XFCE_MIXER_PROFILE (xfce_mixer_profile_new (tmp));
		return p;
	}}
#line 444 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 171 "mixer-profiles.gob"
XfceMixerProfile * 
xfce_mixer_profiles_get_profile (XfceMixerProfiles * self, gchar const * name)
#line 450 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::get_profile"
#line 171 "mixer-profiles.gob"
	g_return_val_if_fail (self != NULL, (XfceMixerProfile * )0);
#line 171 "mixer-profiles.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PROFILES (self), (XfceMixerProfile * )0);
#line 457 "xfce-mixer-profiles.c"
{
#line 172 "mixer-profiles.gob"
	
		GList *g;
		gchar const *s;
		g = self->profiles;
		if (!name)
			return NULL;

		while (g) {
			s = xfce_mixer_profile_get_title (XFCE_MIXER_PROFILE (g->data));
			if (s) {
				if (g_str_equal (s, name)) {
					g_object_ref (G_OBJECT (g->data));
					return XFCE_MIXER_PROFILE (g->data);
				}
			}
			g = g_list_next (g);
		}

		return NULL;
	}}
#line 480 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 193 "mixer-profiles.gob"
void 
xfce_mixer_profiles_delete_profile (XfceMixerProfiles * self, gchar const * name)
#line 486 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::delete_profile"
#line 193 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 193 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 493 "xfce-mixer-profiles.c"
{
#line 194 "mixer-profiles.gob"
	
		XfceMixerProfile *p;
		if (!name)
			return;

		p = self_get_profile (self, name);
		if (p) {
			g_object_unref (G_OBJECT (p));
			g_object_unref (G_OBJECT (p));
			self->profiles = g_list_remove (self->profiles, p);
		}
	}}
#line 508 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 207 "mixer-profiles.gob"
void 
xfce_mixer_profiles_set_modified (XfceMixerProfiles * self, gboolean modi)
#line 514 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::set_modified"
#line 207 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 207 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 521 "xfce-mixer-profiles.c"
{
#line 208 "mixer-profiles.gob"
	
		self->modified = modi;
	}}
#line 527 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 212 "mixer-profiles.gob"
gboolean 
xfce_mixer_profiles_get_modified (XfceMixerProfiles * self)
#line 533 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::get_modified"
#line 212 "mixer-profiles.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 212 "mixer-profiles.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PROFILES (self), (gboolean )0);
#line 540 "xfce-mixer-profiles.c"
{
#line 213 "mixer-profiles.gob"
	
		return self->modified;
	}}
#line 546 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 217 "mixer-profiles.gob"
XfceMixerProfiles * 
xfce_mixer_profiles_new (gchar const * device)
#line 552 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::new"
{
#line 218 "mixer-profiles.gob"
	
		XfceMixerProfiles *p;
		p = XFCE_MIXER_PROFILES (GET_NEW);
		p->device = g_strdup (device);
		return p;
	}}
#line 563 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___xfce_mixer_profiles_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))GET_NEW_VARG)();
	((void (*)(void))self_clear)();
	((void (*)(void))self_goto_device)();
	((void (*)(void))self_load)();
	((void (*)(void))self_xml_text_child)();
	((void (*)(void))self_save)();
	((void (*)(void))self_create_profile)();
	((void (*)(void))self_get_profile)();
	((void (*)(void))self_delete_profile)();
	((void (*)(void))self_set_modified)();
	((void (*)(void))self_get_modified)();
	((void (*)(void))self_new)();
	___xfce_mixer_profiles_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */

