/* Generated by GOB (v2.0.9) on Wed Jul 21 21:09:32 2004
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 9

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "xfce-mixer-profilebox-detail.h"

#include "xfce-mixer-profilebox-detail-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-profilebox-detail.gob"

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#line 33 "xfce-mixer-profilebox-detail.c"

#line 6 "mixer-profilebox-detail.gob"

#include <gtk/gtk.h>
#include "vc.h"
#include "xfce-mixer-profile.h"

#line 41 "xfce-mixer-profilebox-detail.c"

#line 11 "mixer-profilebox-detail.gob"

#include <libxfce4util/libxfce4util.h>
#include "xfce-mixer-cache-vc.h"
#include "xfce-mixer-mcs-client.h"
#include "helpers3.inc"
#define emit

extern GtkTooltips * tooltips;

static void each_vccache_cb (volcontrol_t *vci, gpointer userdata);

extern XfceMixerMcsClient *mcsc;

static gboolean 
true_hfe_cb(gchar const *k, gint v, gpointer user_data)
{
	return TRUE;
}

#define COLUMN_ACTIVE (gint)0
#define COLUMN_PRETTY_NAME (gint)1
#define COLUMN_TYPE (gint)2
#define COLUMN_VCNAME (gint)3
#define COLUMN_LOCATION (gint)4


#line 70 "xfce-mixer-profilebox-detail.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_PROFILEBOX_DETAIL(x)
#define SELF_CONST(x) XFCE_MIXER_PROFILEBOX_DETAIL_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_PROFILEBOX_DETAIL(x)
#define TYPE_SELF XFCE_TYPE_MIXER_PROFILEBOX_DETAIL
#define SELF_CLASS(x) XFCE_MIXER_PROFILEBOX_DETAIL_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_PROFILEBOX_DETAIL_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerProfileboxDetail Self;
typedef XfceMixerProfileboxDetailClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_profilebox_detail_class_init (XfceMixerProfileboxDetailClass * c) G_GNUC_UNUSED;
static void xfce_mixer_profilebox_detail_init (XfceMixerProfileboxDetail * self) G_GNUC_UNUSED;
static void xfce_mixer_profilebox_detail_set_loc (XfceMixerProfileboxDetail * self, GtkTreeIter * iter, gchar tyc) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkVBoxClass *parent_class = NULL;

/* Short form macros */
#define self_check_all xfce_mixer_profilebox_detail_check_all
#define self_set_profile xfce_mixer_profilebox_detail_set_profile
#define self_up_clicked_cb xfce_mixer_profilebox_detail_up_clicked_cb
#define self_down_clicked_cb xfce_mixer_profilebox_detail_down_clicked_cb
#define self_clear xfce_mixer_profilebox_detail_clear
#define self_get_name xfce_mixer_profilebox_detail_get_name
#define self_save xfce_mixer_profilebox_detail_save
#define self_fill xfce_mixer_profilebox_detail_fill
#define self_unfill xfce_mixer_profilebox_detail_unfill
#define self_filln xfce_mixer_profilebox_detail_filln
#define self_each_profile_item_cb xfce_mixer_profilebox_detail_each_profile_item_cb
#define self_set_loc xfce_mixer_profilebox_detail_set_loc
#define self_each_vccache_cb xfce_mixer_profilebox_detail_each_vccache_cb
#define self_rows_reordered_cb xfce_mixer_profilebox_detail_rows_reordered_cb
#define self_new xfce_mixer_profilebox_detail_new
GType
xfce_mixer_profilebox_detail_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerProfileboxDetailClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_profilebox_detail_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerProfileboxDetail),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_profilebox_detail_init,
			NULL
		};

		type = g_type_register_static (GTK_TYPE_VBOX, "XfceMixerProfileboxDetail", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerProfileboxDetail *)g_object_new(xfce_mixer_profilebox_detail_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerProfileboxDetail * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerProfileboxDetail *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerProfileboxDetail *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerProfileboxDetail *)g_object_new_valist (xfce_mixer_profilebox_detail_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___dispose (GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::dispose"
	XfceMixerProfileboxDetail *self G_GNUC_UNUSED = XFCE_MIXER_PROFILEBOX_DETAIL (obj_self);
	if (G_OBJECT_CLASS (parent_class)->dispose) \
		(* G_OBJECT_CLASS (parent_class)->dispose) (obj_self);
#line 46 "mixer-profilebox-detail.gob"
	if(self->profile) { ((*(void (*)(void *))g_object_unref)) (self->profile); self->profile = NULL; }
#line 160 "xfce-mixer-profilebox-detail.c"
}
#undef __GOB_FUNCTION__


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::finalize"
	XfceMixerProfileboxDetail *self  G_GNUC_UNUSED = XFCE_MIXER_PROFILEBOX_DETAIL (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 48 "mixer-profilebox-detail.gob"
	if(self->valids) { ((*(void (*)(void *))g_free)) (self->valids); self->valids = NULL; }
#line 174 "xfce-mixer-profilebox-detail.c"
#line 50 "mixer-profilebox-detail.gob"
	if(self->presents) { ((*(void (*)(void *))g_hash_table_destroy)) (self->presents); self->presents = NULL; }
#line 177 "xfce-mixer-profilebox-detail.c"
}
#undef __GOB_FUNCTION__

static void 
xfce_mixer_profilebox_detail_class_init (XfceMixerProfileboxDetailClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (GTK_TYPE_VBOX);

	g_object_class->dispose = ___dispose;
	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__
#line 124 "mixer-profilebox-detail.gob"
static void 
xfce_mixer_profilebox_detail_init (XfceMixerProfileboxDetail * self G_GNUC_UNUSED)
#line 196 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::init"
#line 11 "mixer-profilebox-detail.gob"
	self->dofill = FALSE;
#line 201 "xfce-mixer-profilebox-detail.c"
#line 11 "mixer-profilebox-detail.gob"
	self->profile = NULL;
#line 204 "xfce-mixer-profilebox-detail.c"
#line 11 "mixer-profilebox-detail.gob"
	self->valids = NULL;
#line 207 "xfce-mixer-profilebox-detail.c"
#line 11 "mixer-profilebox-detail.gob"
	self->presents = NULL;
#line 210 "xfce-mixer-profilebox-detail.c"
 {
#line 125 "mixer-profilebox-detail.gob"

		GtkBox *nbox;
		GtkWidget *dlabel;
		GtkWidget *detail_hb;
		GtkWidget *detail_vbb;

		self->presents = g_hash_table_new_full (g_str_hash, g_str_equal, g_free, NULL);

		self->detail_box = GTK_BOX (self);
		gtk_box_set_spacing (self->detail_box, 5);

		self->detail_sw = GTK_SCROLLED_WINDOW (gtk_scrolled_window_new (NULL, NULL));
		gtk_scrolled_window_set_policy (self->detail_sw, GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
		gtk_widget_show (GTK_WIDGET (self->detail_sw));

		self->detail_model = GTK_TREE_STORE (gtk_tree_store_new (
			5, G_TYPE_BOOLEAN, G_TYPE_STRING, G_TYPE_STRING,
			G_TYPE_STRING, G_TYPE_STRING
		));

		self->detail_tv = GTK_TREE_VIEW (gtk_tree_view_new ());

		gtk_tree_view_append_column (self->detail_tv, 
			tree_new_check_column ("", 0, GTK_TREE_MODEL (self->detail_model)
		));
		gtk_tree_view_append_column (self->detail_tv, 
			tree_new_text_column (_("Control"), 1
		));
		gtk_tree_view_append_column (self->detail_tv, 
			tree_new_text_column (_("Type"), 2
		));
		/*gtk_tree_view_append_column (self->detail_tv, 
			tree_new_text_column (_("Location"), 3
		));*/

		gtk_tree_view_set_model (self->detail_tv, GTK_TREE_MODEL (self->detail_model));
		gtk_tree_view_set_headers_visible (self->detail_tv, TRUE);

		gtk_widget_show (GTK_WIDGET (self->detail_tv));

		self->detail_up_button = GTK_BUTTON (
			gtk_button_new_with_mnemonic (_("Up"))
		);
		self->detail_down_button = GTK_BUTTON (
			gtk_button_new_with_mnemonic (_("Down"))
		);

		gtk_widget_show (GTK_WIDGET (self->detail_up_button));
		gtk_widget_show (GTK_WIDGET (self->detail_down_button));

		gtk_tooltips_set_tip (tooltips, GTK_WIDGET (self->detail_up_button), 
			_("Move Entry Up"), NULL);

		gtk_tooltips_set_tip (tooltips, GTK_WIDGET (self->detail_down_button), 
			_("Move Entry Down"), NULL);

		g_signal_connect_swapped (G_OBJECT (self->detail_up_button), "clicked", 
			G_CALLBACK (self_up_clicked_cb), self);
		g_signal_connect_swapped (G_OBJECT (self->detail_down_button), "clicked", 
			G_CALLBACK (self_down_clicked_cb), self);

		gtk_container_add (GTK_CONTAINER (self->detail_sw), GTK_WIDGET (self->detail_tv));

		dlabel = gtk_label_new (_("Profile Name:"));
		gtk_widget_show (dlabel);

		self->detail_name_entry = GTK_ENTRY (gtk_entry_new ());
		gtk_entry_set_max_length (self->detail_name_entry, 79);
		gtk_widget_show (GTK_WIDGET (self->detail_name_entry));

		nbox = GTK_BOX (gtk_hbox_new (FALSE, 5));
		gtk_box_pack_start (nbox, GTK_WIDGET (dlabel), FALSE, FALSE, 0);
		gtk_box_pack_start (nbox, GTK_WIDGET (self->detail_name_entry), TRUE, TRUE, 0);
		gtk_widget_show (GTK_WIDGET (nbox));

		gtk_box_pack_start (GTK_BOX (self->detail_box), GTK_WIDGET (nbox), FALSE, FALSE, 0);

		detail_hb = gtk_hbox_new (FALSE, 5);

		detail_vbb = gtk_vbutton_box_new ();
		gtk_container_set_border_width (GTK_CONTAINER (detail_vbb), 5);
		gtk_box_pack_start (GTK_BOX (detail_vbb), GTK_WIDGET (self->detail_up_button), FALSE, FALSE, 0);
		gtk_box_pack_start (GTK_BOX (detail_vbb), GTK_WIDGET (self->detail_down_button), FALSE, FALSE, 0);

		gtk_widget_show (GTK_WIDGET (detail_vbb));

		gtk_box_pack_start (GTK_BOX (detail_hb), GTK_WIDGET (self->detail_sw), TRUE, TRUE, 0);
		gtk_box_pack_start (GTK_BOX (detail_hb), GTK_WIDGET (detail_vbb), FALSE, FALSE, 0);
		gtk_widget_show (GTK_WIDGET (detail_hb));

		gtk_box_pack_start (GTK_BOX (self->detail_box), GTK_WIDGET (detail_hb), TRUE, TRUE, 0);

		gtk_tree_view_set_reorderable (self->detail_tv, TRUE);
		g_signal_connect_swapped (G_OBJECT (self->detail_model),
			"rows-reordered", G_CALLBACK (self_rows_reordered_cb),
			self);

		gtk_entry_set_activates_default (self->detail_name_entry, TRUE);

	
#line 313 "xfce-mixer-profilebox-detail.c"
 }
}
#undef __GOB_FUNCTION__


#line 54 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_check_all (XfceMixerProfileboxDetail * self)
#line 322 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::check_all"
#line 54 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 54 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 329 "xfce-mixer-profilebox-detail.c"
{
#line 55 "mixer-profilebox-detail.gob"
	
		gboolean b;
		GtkTreeIter iter;

		b = gtk_tree_model_get_iter_first (GTK_TREE_MODEL (self->detail_model), &iter);
		if (!b)
			return;

		while (b) {
			gtk_tree_store_set (self->detail_model, &iter,
				COLUMN_ACTIVE, TRUE, -1);

			b = gtk_tree_model_iter_next (GTK_TREE_MODEL (self->detail_model), &iter);
		}

	}}
#line 348 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 72 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_set_profile (XfceMixerProfileboxDetail * self, XfceMixerProfile * p)
#line 354 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::set_profile"
#line 72 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 72 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 361 "xfce-mixer-profilebox-detail.c"
{
#line 73 "mixer-profilebox-detail.gob"
	
		gchar const *t;
		if (self->profile) {
			g_object_unref (G_OBJECT (self->profile));
			self->profile = NULL;
		}

		if (p) {
			self->profile = p;
			g_object_ref (G_OBJECT (p));
			t = xfce_mixer_profile_get_title (p);
			self_filln (self, t);
		} else
			self_unfill (self);
	}}
#line 379 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 89 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_up_clicked_cb (XfceMixerProfileboxDetail * self, GtkButton * b)
#line 385 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::up_clicked_cb"
#line 89 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 89 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 392 "xfce-mixer-profilebox-detail.c"
{
#line 90 "mixer-profilebox-detail.gob"
	
		GtkTreeSelection *sel;
		GtkTreeIter iter;
		GtkTreeModel *model;
		gboolean b;
		sel = gtk_tree_view_get_selection (self->detail_tv);
		if (!sel)
			return;

		b = gtk_tree_selection_get_selected (sel, &model, &iter);
		if (!b)
			return;

		g_warning ("move");
		gtk_tree_store_move_before (self->detail_model, &iter, &iter);
	}}
#line 411 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 107 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_down_clicked_cb (XfceMixerProfileboxDetail * self, GtkButton * b)
#line 417 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::down_clicked_cb"
#line 107 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 107 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 424 "xfce-mixer-profilebox-detail.c"
{
#line 108 "mixer-profilebox-detail.gob"
	
		GtkTreeSelection *sel;
		GtkTreeIter iter;
		GtkTreeModel *model;
		gboolean b;
		sel = gtk_tree_view_get_selection (self->detail_tv);
		if (!sel)
			return;

		b = gtk_tree_selection_get_selected (sel, &model, &iter);
		if (!b)
			return;

		gtk_tree_store_move_after (self->detail_model, &iter, &iter);
	}}
#line 442 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__


#line 226 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_clear (XfceMixerProfileboxDetail * self)
#line 449 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::clear"
#line 226 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 226 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 456 "xfce-mixer-profilebox-detail.c"
{
#line 227 "mixer-profilebox-detail.gob"
	
		gtk_entry_set_text (GTK_ENTRY (self->detail_name_entry), "");
		gtk_tree_store_clear (self->detail_model);
		g_hash_table_foreach_remove (self->presents, (GHRFunc)true_hfe_cb, self);
	}}
#line 464 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 233 "mixer-profilebox-detail.gob"
gchar const * 
xfce_mixer_profilebox_detail_get_name (XfceMixerProfileboxDetail * self)
#line 470 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::get_name"
#line 233 "mixer-profilebox-detail.gob"
	g_return_val_if_fail (self != NULL, (gchar const * )0);
#line 233 "mixer-profilebox-detail.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self), (gchar const * )0);
#line 477 "xfce-mixer-profilebox-detail.c"
{
#line 234 "mixer-profilebox-detail.gob"
	
		return gtk_entry_get_text (self->detail_name_entry);
	}}
#line 483 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 238 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_save (XfceMixerProfileboxDetail * self)
#line 489 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::save"
#line 238 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 238 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 496 "xfce-mixer-profilebox-detail.c"
{
#line 239 "mixer-profilebox-detail.gob"
	
		t_mixer_profile_item *it;
		gint orderno;
		gboolean b;
		gboolean active;
		gchar *vcname;
		GtkTreeIter iter;
		gchar *location;

		b = gtk_tree_model_get_iter_first (GTK_TREE_MODEL (self->detail_model), &iter);
		if (!b)
			return;

		it = g_new0 (t_mixer_profile_item, 1);

		orderno = 1;

		while (b) {
			gtk_tree_model_get (GTK_TREE_MODEL (self->detail_model),
				&iter,
				COLUMN_ACTIVE, &active,
				COLUMN_VCNAME, &vcname,
				COLUMN_LOCATION, &location,
				-1
			);

			if(vcname) {
				if (active)
					it->orderno = orderno;
				else
					it->orderno = -1;

				it->vcname = vcname;

				it->location = location;

				if (self->profile)
					xfce_mixer_profile_update_control (self->profile, it);
				
				g_free (vcname);
			}

			if (location)
				g_free (location);

			++orderno;
			b = gtk_tree_model_iter_next (GTK_TREE_MODEL (self->detail_model), &iter);
		}
		
		g_free (it);
	}}
#line 550 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 291 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_fill (XfceMixerProfileboxDetail * self)
#line 556 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::fill"
#line 291 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 291 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 563 "xfce-mixer-profilebox-detail.c"
{
#line 292 "mixer-profilebox-detail.gob"
	
		GList *go;
		GList *g;
		t_mixer_profile_item *it;

		self->dofill = TRUE;
		self_clear (self);
		/* 1. add profile data */
		/* 2. add possible, but yet-to-be-used controls (which are not in profile) */

		/* 1.: */
		go = NULL;
		if (self->profile)
			go = xfce_mixer_profile_get_control_list (self->profile);

		if (go) {
			g = go;
			for(; g; g = g_list_next (g)) {
				it = (t_mixer_profile_item *)g->data;
				if (!it)
					continue;

				self_each_profile_item_cb (self, it);
			}
			xfce_mixer_profile_free_control_list (self->profile, go);
		}

		if (self->valids)
			g_free (self->valids);
		self->valids = NULL;

		if (mcsc)
			self->valids = xfce_mixer_mcs_client_get_useful_controls (mcsc,
                                vc_get_device ());

		xfce_mixer_cache_vc_foreach ((GFunc)each_vccache_cb, self);
		gtk_widget_set_sensitive (GTK_WIDGET (self), TRUE);
		if (self->valids) {
			g_free (self->valids);
			self->valids = NULL;
		}
	}}
#line 608 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 335 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_unfill (XfceMixerProfileboxDetail * self)
#line 614 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::unfill"
#line 335 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 335 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 621 "xfce-mixer-profilebox-detail.c"
{
#line 336 "mixer-profilebox-detail.gob"
	
		self->dofill = FALSE;
		gtk_widget_set_sensitive (GTK_WIDGET (self), FALSE);
		self_clear (self);
	}}
#line 629 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 342 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_filln (XfceMixerProfileboxDetail * self, char const * pname)
#line 635 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::filln"
#line 342 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 342 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 642 "xfce-mixer-profilebox-detail.c"
{
#line 343 "mixer-profilebox-detail.gob"
	
		self_fill (self);
		gtk_entry_set_text (GTK_ENTRY (self->detail_name_entry), pname);
	}}
#line 649 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 348 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_each_profile_item_cb (XfceMixerProfileboxDetail * self, t_mixer_profile_item * it)
#line 655 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::each_profile_item_cb"
#line 348 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 348 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 662 "xfce-mixer-profilebox-detail.c"
{
#line 349 "mixer-profilebox-detail.gob"
	
		GtkTreeIter iter;
		gchar tyc;
		gchar *ty;
		/*gchar const *loc;*/

		/* it is not NULL */

		if (!it->vcname || !xfce_mixer_cache_vc_valid (it->vcname))
			return;

		if (self->presents && g_hash_table_lookup (self->presents, it->vcname)) {
			/* already there. */
			return;
		}

		if (self->presents) 
			g_hash_table_insert (self->presents, g_strdup (it->vcname), self);

		tyc = xfce_mixer_cache_vc_get_type (it->vcname);

		ty = _("<unknown>");
		switch(tyc) {
		case 'S': ty = _("<slider>"); break;
		case 'O': ty = _("<onoff>"); break;
		case 'C': ty = _("<select>"); break;
		default:
			return;
		}

		gtk_tree_store_append (self->detail_model, &iter, NULL);
		gtk_tree_store_set (self->detail_model, &iter, 
			COLUMN_ACTIVE, TRUE,
			COLUMN_PRETTY_NAME, it->vcname,
			COLUMN_TYPE, ty,
			COLUMN_VCNAME, it->vcname,
		-1);

		self_set_loc(self, &iter, tyc);
	}}
#line 705 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 390 "mixer-profilebox-detail.gob"
static void 
xfce_mixer_profilebox_detail_set_loc (XfceMixerProfileboxDetail * self, GtkTreeIter * iter, gchar tyc)
#line 711 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::set_loc"
#line 390 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 390 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 718 "xfce-mixer-profilebox-detail.c"
{
#line 391 "mixer-profilebox-detail.gob"
	
		gchar const *loc;
		loc = NULL;
		switch(tyc) {
		case 'S': loc = "sliders"; break;
		case 'O': loc = "switches"; break;
		case 'C': loc = "switches"; break;
		default:
			return;
		}
		gtk_tree_store_set (self->detail_model, iter,
			COLUMN_LOCATION, loc, -1);
	}}
#line 734 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 405 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_each_vccache_cb (XfceMixerProfileboxDetail * self, volcontrol_t * vci, gboolean on_s)
#line 740 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::each_vccache_cb"
#line 405 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 405 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 747 "xfce-mixer-profilebox-detail.c"
{
#line 406 "mixer-profilebox-detail.gob"
	
		GtkTreeIter iter;
		gchar *ty;
		gchar *uct;
		gchar tyc;
		gboolean b;

		b = FALSE;

		if (self->valids) {
			uct = g_strdup_printf ("@%s@", vci->name);
			if (uct) {
				b = g_strrstr (self->valids, uct) != NULL;
                                /*printf ("%s %s %d", uc , uct, (int)b );*/
				g_free (uct);
                        }   
                }

		if (!b)
			return;

		if (self->presents && g_hash_table_lookup (self->presents, vci->name)) {
			/* already there. */
			return;
		}

		if (self->presents) 
			g_hash_table_insert (self->presents, g_strdup (vci->name), self);

		ty = _("<unknown>");
		switch(vci->type) {
		case CT_SLIDER: ty = _("<slider>"); break;
		case CT_ONOFF: ty = _("<onoff>"); break;
		case CT_SELECT: ty = _("<select>"); break;
		}

		tyc = xfce_mixer_cache_vc_get_type (vci->name);

		b = on_s;

		gtk_tree_store_append (self->detail_model, &iter, NULL);
		gtk_tree_store_set (self->detail_model, &iter, 
			COLUMN_ACTIVE, b,
			COLUMN_PRETTY_NAME, vci->name,
			COLUMN_TYPE, ty,
			COLUMN_VCNAME, vci->name, -1);
		self_set_loc(self, &iter, tyc);
	}}
#line 798 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 455 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_rows_reordered_cb (XfceMixerProfileboxDetail * self, GtkTreePath * arg1, GtkTreeIter * arg2, gpointer arg3, GtkTreeModel * model)
#line 804 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::rows_reordered_cb"
#line 455 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 455 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 811 "xfce-mixer-profilebox-detail.c"
{
#line 457 "mixer-profilebox-detail.gob"
	
		g_warning ("reordered");
	}}
#line 817 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 462 "mixer-profilebox-detail.gob"
XfceMixerProfileboxDetail * 
xfce_mixer_profilebox_detail_new (void)
#line 823 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::new"
{
#line 462 "mixer-profilebox-detail.gob"
	
		return XFCE_MIXER_PROFILEBOX_DETAIL (GET_NEW);
	}}
#line 831 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 467 "mixer-profilebox-detail.gob"

static void each_vccache_cb (volcontrol_t *vci, gpointer userdata)
{
	XfceMixerProfileboxDetail *d;
	d = XFCE_MIXER_PROFILEBOX_DETAIL (userdata);

	if (vci && vci->name) {
		xfce_mixer_profilebox_detail_each_vccache_cb (d, vci, FALSE);
	}
}

#line 846 "xfce-mixer-profilebox-detail.c"
