/* Generated by GOB (v2.0.9) on Sun Mar 27 22:16:04 2005
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 9

#define selfp (self->_priv)

#include "xfce-mixer-slider.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-slider.gob"

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#line 32 "xfce-mixer-slider.c"

#line 8 "mixer-slider.gob"

#include "xfce-mixer-control.h"

#line 38 "xfce-mixer-slider.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_SLIDER(x)
#define SELF_CONST(x) XFCE_MIXER_SLIDER_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_SLIDER(x)
#define TYPE_SELF XFCE_TYPE_MIXER_SLIDER
#define SELF_CLASS(x) XFCE_MIXER_SLIDER_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_SLIDER_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerSlider Self;
typedef XfceMixerSliderClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_slider_class_init (XfceMixerSliderClass * c) G_GNUC_UNUSED;
static void xfce_mixer_slider_slider_changed_cb (GtkRange * range, gpointer user_data) G_GNUC_UNUSED;
static void xfce_mixer_slider_init (XfceMixerSlider * self) G_GNUC_UNUSED;
static void ___4_xfce_mixer_slider_value_changed (XfceMixerControl * pself) G_GNUC_UNUSED;
static void ___5_xfce_mixer_slider_vcname_changed (XfceMixerControl * pself) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static XfceMixerControlClass *parent_class = NULL;

/* Short form macros */
#define self_slider_changed_cb xfce_mixer_slider_slider_changed_cb
#define self_new xfce_mixer_slider_new
GType
xfce_mixer_slider_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerSliderClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_slider_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerSlider),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_slider_init,
			NULL
		};

		type = g_type_register_static (XFCE_TYPE_MIXER_CONTROL, "XfceMixerSlider", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerSlider *)g_object_new(xfce_mixer_slider_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerSlider * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerSlider *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerSlider *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerSlider *)g_object_new_valist (xfce_mixer_slider_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
xfce_mixer_slider_class_init (XfceMixerSliderClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider::class_init"
	XfceMixerControlClass *xfce_mixer_control_class = (XfceMixerControlClass *)c;

	parent_class = g_type_class_ref (XFCE_TYPE_MIXER_CONTROL);

#line 58 "mixer-slider.gob"
	xfce_mixer_control_class->value_changed = ___4_xfce_mixer_slider_value_changed;
#line 70 "mixer-slider.gob"
	xfce_mixer_control_class->vcname_changed = ___5_xfce_mixer_slider_vcname_changed;
#line 119 "xfce-mixer-slider.c"
}
#undef __GOB_FUNCTION__
#line 31 "mixer-slider.gob"
static void 
xfce_mixer_slider_init (XfceMixerSlider * self G_GNUC_UNUSED)
#line 125 "xfce-mixer-slider.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider::init"
#line 8 "mixer-slider.gob"
	self->scale = NULL;
#line 130 "xfce-mixer-slider.c"
#line 8 "mixer-slider.gob"
	self->label = NULL;
#line 133 "xfce-mixer-slider.c"
#line 8 "mixer-slider.gob"
	self->hbox = NULL;
#line 136 "xfce-mixer-slider.c"
#line 8 "mixer-slider.gob"
	self->eventbox = NULL;
#line 139 "xfce-mixer-slider.c"
 {
#line 32 "mixer-slider.gob"

		self->label = GTK_LABEL (gtk_label_new (""));
		gtk_widget_show (GTK_WIDGET (self->label));

		self->eventbox = GTK_WIDGET (gtk_event_box_new ());
		gtk_container_add (GTK_CONTAINER (self->eventbox), GTK_WIDGET (self->label));
		gtk_widget_show (self->eventbox);
	
		gtk_box_pack_start (GTK_BOX (self), GTK_WIDGET (self->eventbox), FALSE, FALSE, 5);

		self->scale = GTK_SCALE (gtk_vscale_new_with_range (0.0, 100.0, 1.0));
		gtk_widget_show (GTK_WIDGET (self->scale));

		gtk_scale_set_draw_value (self->scale, FALSE);
		gtk_range_set_inverted (GTK_RANGE (self->scale), TRUE);

		g_signal_connect (G_OBJECT (self->scale), "value-changed", G_CALLBACK (self_slider_changed_cb), self);

		gtk_box_pack_start (GTK_BOX (self), GTK_WIDGET (self->scale), TRUE, TRUE, 5);
	
#line 162 "xfce-mixer-slider.c"
 }
}
#undef __GOB_FUNCTION__


#line 18 "mixer-slider.gob"
static void 
xfce_mixer_slider_slider_changed_cb (GtkRange * range, gpointer user_data)
#line 171 "xfce-mixer-slider.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider::slider_changed_cb"
{
#line 19 "mixer-slider.gob"
	
		XfceMixerSlider *xms;
		gdouble val;
		gchar *tmp;

		xms = XFCE_MIXER_SLIDER (user_data);
		val = gtk_range_get_value (range);
		tmp = g_strdup_printf("%d", (gint) val);
		g_object_set (G_OBJECT (xms), "value", tmp, NULL);
		g_free (tmp);
	}}
#line 187 "xfce-mixer-slider.c"
#undef __GOB_FUNCTION__


#line 53 "mixer-slider.gob"
XfceMixerControl * 
xfce_mixer_slider_new (void)
#line 194 "xfce-mixer-slider.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider::new"
{
#line 54 "mixer-slider.gob"
	
		return XFCE_MIXER_CONTROL(GET_NEW);
	}}
#line 202 "xfce-mixer-slider.c"
#undef __GOB_FUNCTION__

#line 58 "mixer-slider.gob"
static void 
___4_xfce_mixer_slider_value_changed (XfceMixerControl * pself G_GNUC_UNUSED)
#line 208 "xfce-mixer-slider.c"
#define PARENT_HANDLER(___pself) \
	{ if(XFCE_MIXER_CONTROL_CLASS(parent_class)->value_changed) \
		(* XFCE_MIXER_CONTROL_CLASS(parent_class)->value_changed)(___pself); }
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider::value_changed"
#line 58 "mixer-slider.gob"
	g_return_if_fail (pself != NULL);
#line 58 "mixer-slider.gob"
	g_return_if_fail (XFCE_IS_MIXER_CONTROL (pself));
#line 218 "xfce-mixer-slider.c"
{
#line 60 "mixer-slider.gob"
	
		gint v;
		Self *self;
		self = SELF (pself);

		v = xfce_mixer_control_calc_num_value (pself);

		gtk_range_set_value (GTK_RANGE (self->scale), (gdouble) v);
	}}
#line 230 "xfce-mixer-slider.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 70 "mixer-slider.gob"
static void 
___5_xfce_mixer_slider_vcname_changed (XfceMixerControl * pself G_GNUC_UNUSED)
#line 237 "xfce-mixer-slider.c"
#define PARENT_HANDLER(___pself) \
	{ if(XFCE_MIXER_CONTROL_CLASS(parent_class)->vcname_changed) \
		(* XFCE_MIXER_CONTROL_CLASS(parent_class)->vcname_changed)(___pself); }
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider::vcname_changed"
#line 70 "mixer-slider.gob"
	g_return_if_fail (pself != NULL);
#line 70 "mixer-slider.gob"
	g_return_if_fail (XFCE_IS_MIXER_CONTROL (pself));
#line 247 "xfce-mixer-slider.c"
{
#line 72 "mixer-slider.gob"
	
		Self *self;
		char *sanename;

		self = SELF (pself);
		PARENT_HANDLER (pself);

		sanename = xfce_mixer_control_calc_sanename (pself);
		gtk_label_set_text (GTK_LABEL (self->label), sanename);
		g_free (sanename);
	}}
#line 261 "xfce-mixer-slider.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER
