/* Generated by GOB (v2.0.6)   (do not edit directly) */

#ifndef __XFCE_MIXER_PROFILEBOX_DETAIL_PRIVATE_H__
#define __XFCE_MIXER_PROFILEBOX_DETAIL_PRIVATE_H__

#include "xfce-mixer-profilebox-detail.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include "vc.h"
#include "xfce-mixer-profile.h"

#line 6 "mixer-profilebox-detail.gob"
#line 20 "xfce-mixer-profilebox-detail-private.h"
void 	xfce_mixer_profilebox_detail_fill	(XfceMixerProfileboxDetail * self);
void 	xfce_mixer_profilebox_detail_unfill	(XfceMixerProfileboxDetail * self);
void 	xfce_mixer_profilebox_detail_rows_reordered_cb	(XfceMixerProfileboxDetail * self, GtkTreePath * arg1, GtkTreeIter * arg2, gpointer arg3, GtkTreeModel * model);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
