/* Generated by GOB (v2.0.6) on Wed Jul 21 20:45:32 2004
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 6

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "xfce-mixer-profiles.h"

#include "xfce-mixer-profiles-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-profiles.gob"

#include <gtk/gtk.h>
#include "xfce-mixer-profile.h"
#include "xfce-mixer-pxml.h"

#line 33 "xfce-mixer-profiles.c"

#line 6 "mixer-profiles.gob"

#include <libxfce4util/libxfce4util.h>
#define emit
#define PROFILES_ROOT "Profiles"
#ifndef MAX_PATH
#define MAX_PATH 4096
#endif

static void profiles_free (GList *profiles)
{
	GList *g;
	g = profiles;
	while (g) {
		g_object_unref (G_OBJECT (g->data));
		g = g_list_next (g);
	}
	g_list_free (profiles);
}


#line 56 "xfce-mixer-profiles.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_PROFILES(x)
#define SELF_CONST(x) XFCE_MIXER_PROFILES_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_PROFILES(x)
#define TYPE_SELF XFCE_TYPE_MIXER_PROFILES
#define SELF_CLASS(x) XFCE_MIXER_PROFILES_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_PROFILES_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerProfiles Self;
typedef XfceMixerProfilesClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_profiles_class_init (XfceMixerProfilesClass * c) G_GNUC_UNUSED;
static void xfce_mixer_profiles_init (XfceMixerProfiles * self) G_GNUC_UNUSED;

/*
 * Signal connection wrapper macro shortcuts
 */
#define self_connect__profiles_changed(object,func,data)	xfce_mixer_profiles_connect__profiles_changed((object),(func),(data))
#define self_connect_after__profiles_changed(object,func,data)	xfce_mixer_profiles_connect_after__profiles_changed((object),(func),(data))
#define self_connect_data__profiles_changed(object,func,data,destroy_data,flags)	xfce_mixer_profiles_connect_data__profiles_changed((object),(func),(data),(destroy_data),(flags))

enum {
	PROFILES_CHANGED_SIGNAL,
	LAST_SIGNAL
};

static guint object_signals[LAST_SIGNAL] = {0};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define self_profiles_changed(args...) xfce_mixer_profiles_profiles_changed(args)
#define self_clear(args...) xfce_mixer_profiles_clear(args)
#define self_get_profile_names(args...) xfce_mixer_profiles_get_profile_names(args)
#define self_goto_device(args...) xfce_mixer_profiles_goto_device(args)
#define self_load_profile(args...) xfce_mixer_profiles_load_profile(args)
#define self_load(args...) xfce_mixer_profiles_load(args)
#define self_xml_text_child(args...) xfce_mixer_profiles_xml_text_child(args)
#define self_save_profile(args...) xfce_mixer_profiles_save_profile(args)
#define self_save(args...) xfce_mixer_profiles_save(args)
#define self_add_profile(args...) xfce_mixer_profiles_add_profile(args)
#define self_get_profile(args...) xfce_mixer_profiles_get_profile(args)
#define self_delete_profile(args...) xfce_mixer_profiles_delete_profile(args)
#define self_set_modified(args...) xfce_mixer_profiles_set_modified(args)
#define self_delayed_pc_cb(args...) xfce_mixer_profiles_delayed_pc_cb(args)
#define self_get_modified(args...) xfce_mixer_profiles_get_modified(args)
#define self_new(args...) xfce_mixer_profiles_new(args)
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static void (* const self_profiles_changed) (XfceMixerProfiles * self) = xfce_mixer_profiles_profiles_changed;
static void (* const self_clear) (XfceMixerProfiles * self) = xfce_mixer_profiles_clear;
static GList * (* const self_get_profile_names) (XfceMixerProfiles * self) = xfce_mixer_profiles_get_profile_names;
static void (* const self_goto_device) (XfceMixerProfiles * self) = xfce_mixer_profiles_goto_device;
static void (* const self_load_profile) (XfceMixerProfiles * self, XfceMixerProfile * p) = xfce_mixer_profiles_load_profile;
static void (* const self_load) (XfceMixerProfiles * self) = xfce_mixer_profiles_load;
static void (* const self_xml_text_child) (XfceMixerProfiles * self, gchar const * tagname) = xfce_mixer_profiles_xml_text_child;
static void (* const self_save_profile) (XfceMixerProfiles * self, XfceMixerProfile * p) = xfce_mixer_profiles_save_profile;
static void (* const self_save) (XfceMixerProfiles * self) = xfce_mixer_profiles_save;
static void (* const self_add_profile) (XfceMixerProfiles * self, XfceMixerProfile * pn) = xfce_mixer_profiles_add_profile;
static XfceMixerProfile * (* const self_get_profile) (XfceMixerProfiles * self, gchar const * name) = xfce_mixer_profiles_get_profile;
static void (* const self_delete_profile) (XfceMixerProfiles * self, gchar const * name) = xfce_mixer_profiles_delete_profile;
static void (* const self_set_modified) (XfceMixerProfiles * self, gboolean modi) = xfce_mixer_profiles_set_modified;
static gboolean (* const self_delayed_pc_cb) (XfceMixerProfiles * self) = xfce_mixer_profiles_delayed_pc_cb;
static gboolean (* const self_get_modified) (XfceMixerProfiles * self) = xfce_mixer_profiles_get_modified;
static XfceMixerProfiles * (* const self_new) (gchar const * device) = xfce_mixer_profiles_new;

GType
xfce_mixer_profiles_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerProfilesClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_profiles_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerProfiles),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_profiles_init,
		};

		type = g_type_register_static (G_TYPE_OBJECT, "XfceMixerProfiles", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerProfiles *)g_object_new(xfce_mixer_profiles_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerProfiles * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerProfiles *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerProfiles *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerProfiles *)g_object_new_valist (xfce_mixer_profiles_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___dispose (GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::dispose"
	XfceMixerProfiles *self = XFCE_MIXER_PROFILES (obj_self);
	if (G_OBJECT_CLASS (parent_class)->dispose) \
		(* G_OBJECT_CLASS (parent_class)->dispose) (obj_self);
#line 47 "mixer-profiles.gob"
	if(self->xml) { ((*(void (*)(void *))g_object_unref)) (self->xml); self->xml = NULL; }
#line 180 "xfce-mixer-profiles.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::finalize"
	XfceMixerProfiles *self = XFCE_MIXER_PROFILES (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 29 "mixer-profiles.gob"
	if(self->device) { ((*(void (*)(void *))g_free)) (self->device); self->device = NULL; }
#line 196 "xfce-mixer-profiles.c"
#line 31 "mixer-profiles.gob"
	if(self->fname) { ((*(void (*)(void *))g_free)) (self->fname); self->fname = NULL; }
#line 199 "xfce-mixer-profiles.c"
#define profilesChangedDelayed (self->profilesChangedDelayed)
#define VAR profilesChangedDelayed
	{
#line 35 "mixer-profiles.gob"
	
			if (VAR) g_source_remove (VAR);
			VAR = 0;
		}
#line 208 "xfce-mixer-profiles.c"
	memset(&profilesChangedDelayed, 0, sizeof(profilesChangedDelayed));
#undef VAR
#undef profilesChangedDelayed
#define profiles (self->profiles)
#define VAR profiles
	{
#line 41 "mixer-profiles.gob"
	
			profiles_free(VAR);
			VAR = NULL;
		}
#line 220 "xfce-mixer-profiles.c"
	memset(&profiles, 0, sizeof(profiles));
#undef VAR
#undef profiles
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__

static void 
xfce_mixer_profiles_class_init (XfceMixerProfilesClass * c)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::class_init"
	GObjectClass *g_object_class = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	object_signals[PROFILES_CHANGED_SIGNAL] =
		g_signal_new ("profiles_changed",
			G_TYPE_FROM_CLASS (g_object_class),
			(GSignalFlags)(G_SIGNAL_RUN_FIRST | G_SIGNAL_ACTION),
			G_STRUCT_OFFSET (XfceMixerProfilesClass, profiles_changed),
			NULL, NULL,
			g_cclosure_marshal_VOID__VOID,
			G_TYPE_NONE, 0);

	c->profiles_changed = NULL;
	g_object_class->dispose = ___dispose;
	g_object_class->finalize = ___finalize;
	return;
	c = NULL;
	g_object_class = NULL;
}
#undef __GOB_FUNCTION__
#line 54 "mixer-profiles.gob"
static void 
xfce_mixer_profiles_init (XfceMixerProfiles * self)
#line 257 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::init"
#line 6 "mixer-profiles.gob"
	self->device = NULL;
#line 262 "xfce-mixer-profiles.c"
#line 6 "mixer-profiles.gob"
	self->fname = NULL;
#line 265 "xfce-mixer-profiles.c"
#line 6 "mixer-profiles.gob"
	self->modified = FALSE;
#line 268 "xfce-mixer-profiles.c"
#line 6 "mixer-profiles.gob"
	self->weird_number = 0;
#line 271 "xfce-mixer-profiles.c"
#line 6 "mixer-profiles.gob"
	self->profilesChangedDelayed = 0;
#line 274 "xfce-mixer-profiles.c"
#line 35 "mixer-profiles.gob"
	self->profiles = NULL;
#line 277 "xfce-mixer-profiles.c"
#line 41 "mixer-profiles.gob"
	self->xml = NULL;
#line 280 "xfce-mixer-profiles.c"
 {
#line 55 "mixer-profiles.gob"

		self->fname = xfce_get_userfile ("xfce4-mixer", "profiles.xml", NULL);
		self->xml = xfce_mixer_pxml_new (PROFILES_ROOT);
		g_object_set (G_OBJECT (self->xml), "fname", self->fname, NULL);
	
#line 288 "xfce-mixer-profiles.c"
 }
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__


#line 49 "mixer-profiles.gob"
void 
xfce_mixer_profiles_profiles_changed (XfceMixerProfiles * self)
#line 299 "xfce-mixer-profiles.c"
{
	GValue ___param_values[1];
	GValue ___return_val = {0};

#line 49 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 49 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 308 "xfce-mixer-profiles.c"

	___param_values[0].g_type = 0;
	g_value_init (&___param_values[0], G_TYPE_FROM_INSTANCE (self));
	g_value_set_instance (&___param_values[0], (gpointer) self);

	g_signal_emitv (___param_values,
		object_signals[PROFILES_CHANGED_SIGNAL],
		0 /* detail */,
		&___return_val);

	g_value_unset (&___param_values[0]);
}


#line 61 "mixer-profiles.gob"
void 
xfce_mixer_profiles_clear (XfceMixerProfiles * self)
#line 326 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::clear"
#line 61 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 61 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 333 "xfce-mixer-profiles.c"
{
#line 62 "mixer-profiles.gob"
	
		profiles_free (self->profiles);
		self->weird_number = 0;
		self->profiles = NULL;
	}}
#line 341 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 68 "mixer-profiles.gob"
GList * 
xfce_mixer_profiles_get_profile_names (XfceMixerProfiles * self)
#line 347 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::get_profile_names"
#line 68 "mixer-profiles.gob"
	g_return_val_if_fail (self != NULL, (GList * )0);
#line 68 "mixer-profiles.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PROFILES (self), (GList * )0);
#line 354 "xfce-mixer-profiles.c"
{
#line 69 "mixer-profiles.gob"
	
		GList *g;
		GList *gn;
		XfceMixerProfile *p;
		gchar const *so;
		gn = NULL;
		g = self->profiles;
		while (g) {
			p = XFCE_MIXER_PROFILE (g->data);
			so = xfce_mixer_profile_get_title (p);

			gn = g_list_append (gn, g_strdup (so));

			g = g_list_next (g);
		}

		return gn;
	}}
#line 375 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 88 "mixer-profiles.gob"
void 
xfce_mixer_profiles_goto_device (XfceMixerProfiles * self)
#line 381 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::goto_device"
#line 88 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 88 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 388 "xfce-mixer-profiles.c"
{
#line 89 "mixer-profiles.gob"
	
		gchar *n;
		xfce_mixer_pxml_goto_root (self->xml);
		xfce_mixer_pxml_goto_children (self->xml);
		while (self->xml->node) {
			if (xfce_mixer_pxml_check_tag (self->xml, "device")) {
				n = xfce_mixer_pxml_get_prop (self->xml, "name");
				if (n && self->device && g_str_equal (n, self->device)) {
					g_free (n);
					return;
				}
				if (n)
					g_free (n);
			}

			xfce_mixer_pxml_goto_next (self->xml);
		}

		/* device does not exist yet in xml */
		self->xml->node = NULL;
		xfce_mixer_pxml_goto_root (self->xml);
		self->xml->node = xfce_mixer_pxml_create_text_child (self->xml, "device", NULL);
		xfce_mixer_pxml_set_prop (self->xml, "name", self->device);
	}}
#line 415 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 114 "mixer-profiles.gob"
void 
xfce_mixer_profiles_load_profile (XfceMixerProfiles * self, XfceMixerProfile * p)
#line 421 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::load_profile"
#line 114 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 114 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 428 "xfce-mixer-profiles.c"
{
#line 115 "mixer-profiles.gob"
	
		xfce_mixer_profile_load (p, self->xml);
	}}
#line 434 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 119 "mixer-profiles.gob"
void 
xfce_mixer_profiles_load (XfceMixerProfiles * self)
#line 440 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::load"
#line 119 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 119 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 447 "xfce-mixer-profiles.c"
{
#line 120 "mixer-profiles.gob"
	
		gchar *n;
		XfceMixerProfile *p;
		xmlNodePtr parent;
		self_clear (self);
		self_goto_device (self);

		xfce_mixer_pxml_goto_children (self->xml);
		while (self->xml->node) {
			parent = self->xml->node;
			if (xfce_mixer_pxml_check_tag (self->xml, "profile")) {
				n = xfce_mixer_pxml_get_prop (self->xml, "name");
				if (n) {
					p = XFCE_MIXER_PROFILE (xfce_mixer_profile_new (n));
					if (p) {
						self_load_profile (self, p);

						self_add_profile (self, p);
						g_object_unref (G_OBJECT (p));
					}
				}
			}
			self->xml->node = parent;

			xfce_mixer_pxml_goto_next (self->xml);
		}

	}}
#line 478 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 149 "mixer-profiles.gob"
void 
xfce_mixer_profiles_xml_text_child (XfceMixerProfiles * self, gchar const * tagname)
#line 484 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::xml_text_child"
#line 149 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 149 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 491 "xfce-mixer-profiles.c"
{
#line 150 "mixer-profiles.gob"
	
		self->xml->node = xfce_mixer_pxml_create_text_child (self->xml, tagname, NULL);
	}}
#line 497 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 154 "mixer-profiles.gob"
void 
xfce_mixer_profiles_save_profile (XfceMixerProfiles * self, XfceMixerProfile * p)
#line 503 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::save_profile"
#line 154 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 154 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 510 "xfce-mixer-profiles.c"
{
#line 155 "mixer-profiles.gob"
	
		xfce_mixer_profile_save (p, self->xml);
	}}
#line 516 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 159 "mixer-profiles.gob"
void 
xfce_mixer_profiles_save (XfceMixerProfiles * self)
#line 522 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::save"
#line 159 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 159 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 529 "xfce-mixer-profiles.c"
{
#line 160 "mixer-profiles.gob"
	
		xmlNodePtr profilesx;
		XfceMixerProfile *p;
		GList *g;
		gchar const *n;

		if (!self_get_modified (self))
			return;

		xfce_mixer_pxml_goto_root (self->xml);
		self_goto_device (self);

		profilesx = self->xml->node;

		xfce_mixer_pxml_eat_children (self->xml, NULL);

		g = self->profiles;
		while (g) {
			p = XFCE_MIXER_PROFILE (g->data);

			n = xfce_mixer_profile_get_title (p);
			xfce_mixer_pxml_goto_node (self->xml, profilesx);
			self_xml_text_child (self, "profile");
			xfce_mixer_pxml_set_prop (self->xml, "name", n);

			self_save_profile (self, p);
			

			g = g_list_next (g);
		}

		self_set_modified (self, FALSE);
	}}
#line 565 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 194 "mixer-profiles.gob"
void 
xfce_mixer_profiles_add_profile (XfceMixerProfiles * self, XfceMixerProfile * pn)
#line 571 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::add_profile"
#line 194 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 194 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 578 "xfce-mixer-profiles.c"
{
#line 195 "mixer-profiles.gob"
	
		XfceMixerProfile *p;
		gchar const *fixedname;
		gchar tmp[MAX_PATH];
		if (!pn)
			return;

		fixedname = xfce_mixer_profile_get_title (pn);

		if (fixedname)
			g_snprintf (tmp, MAX_PATH, "%s", fixedname);
		else
			g_snprintf (tmp, MAX_PATH, _("profile%d"), ++self->weird_number);

		/* check if name is a dupe */

		p = self_get_profile (self, tmp);
		if (p) {
			g_object_unref (G_OBJECT (p));
			g_snprintf (tmp, MAX_PATH, _("profile%d"), ++self->weird_number);

			p = self_get_profile (self, tmp);
			if (p) { /* hmpf. */
				g_object_unref (G_OBJECT (p));
				return;
			}
		}

		g_object_ref (G_OBJECT (pn));
		self->profiles = g_list_append (self->profiles, pn);
		self_set_modified (self, TRUE);
	}}
#line 613 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 235 "mixer-profiles.gob"
XfceMixerProfile * 
xfce_mixer_profiles_get_profile (XfceMixerProfiles * self, gchar const * name)
#line 619 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::get_profile"
#line 235 "mixer-profiles.gob"
	g_return_val_if_fail (self != NULL, (XfceMixerProfile * )0);
#line 235 "mixer-profiles.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PROFILES (self), (XfceMixerProfile * )0);
#line 626 "xfce-mixer-profiles.c"
{
#line 236 "mixer-profiles.gob"
	
		GList *g;
		gchar const *s;
		g = self->profiles;
		if (!name)
			return NULL;

		while (g) {
			s = xfce_mixer_profile_get_title (XFCE_MIXER_PROFILE (g->data));
			if (s) {
				if (g_str_equal (s, name)) {
					g_object_ref (G_OBJECT (g->data));
					return XFCE_MIXER_PROFILE (g->data);
				}
			}
			g = g_list_next (g);
		}

		return NULL;
	}}
#line 649 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 257 "mixer-profiles.gob"
void 
xfce_mixer_profiles_delete_profile (XfceMixerProfiles * self, gchar const * name)
#line 655 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::delete_profile"
#line 257 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 257 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 662 "xfce-mixer-profiles.c"
{
#line 258 "mixer-profiles.gob"
	
		XfceMixerProfile *p;
		if (!name)
			return;

		p = self_get_profile (self, name);
		if (p) {
			g_object_unref (G_OBJECT (p));
			g_object_unref (G_OBJECT (p));
			self->profiles = g_list_remove (self->profiles, p);
			self_set_modified (self, TRUE);
		}
	}}
#line 678 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 272 "mixer-profiles.gob"
void 
xfce_mixer_profiles_set_modified (XfceMixerProfiles * self, gboolean modi)
#line 684 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::set_modified"
#line 272 "mixer-profiles.gob"
	g_return_if_fail (self != NULL);
#line 272 "mixer-profiles.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILES (self));
#line 691 "xfce-mixer-profiles.c"
{
#line 273 "mixer-profiles.gob"
	
		self->modified = modi;
		if (modi) {
			if (self->profilesChangedDelayed) {
				g_source_remove (self->profilesChangedDelayed);
				self->profilesChangedDelayed = 0;
			}

			self->profilesChangedDelayed = g_timeout_add (500, 
				(GSourceFunc)self_delayed_pc_cb, self);
		}
	}}
#line 706 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 286 "mixer-profiles.gob"
gboolean 
xfce_mixer_profiles_delayed_pc_cb (XfceMixerProfiles * self)
#line 712 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::delayed_pc_cb"
#line 286 "mixer-profiles.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 286 "mixer-profiles.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PROFILES (self), (gboolean )0);
#line 719 "xfce-mixer-profiles.c"
{
#line 287 "mixer-profiles.gob"
	
		emit self_profiles_changed (self);
		return FALSE;
	}}
#line 726 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 292 "mixer-profiles.gob"
gboolean 
xfce_mixer_profiles_get_modified (XfceMixerProfiles * self)
#line 732 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::get_modified"
#line 292 "mixer-profiles.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 292 "mixer-profiles.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PROFILES (self), (gboolean )0);
#line 739 "xfce-mixer-profiles.c"
{
#line 293 "mixer-profiles.gob"
	
		return self->modified;
	}}
#line 745 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__

#line 297 "mixer-profiles.gob"
XfceMixerProfiles * 
xfce_mixer_profiles_new (gchar const * device)
#line 751 "xfce-mixer-profiles.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiles::new"
{
#line 298 "mixer-profiles.gob"
	
		XfceMixerProfiles *p;
		p = XFCE_MIXER_PROFILES (GET_NEW);
		p->device = g_strdup (device);
		return p;
	}}
#line 762 "xfce-mixer-profiles.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___xfce_mixer_profiles_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))GET_NEW_VARG)();
	((void (*)(void))self_profiles_changed)();
	((void (*)(void))self_clear)();
	((void (*)(void))self_get_profile_names)();
	((void (*)(void))self_goto_device)();
	((void (*)(void))self_load_profile)();
	((void (*)(void))self_load)();
	((void (*)(void))self_xml_text_child)();
	((void (*)(void))self_save_profile)();
	((void (*)(void))self_save)();
	((void (*)(void))self_add_profile)();
	((void (*)(void))self_get_profile)();
	((void (*)(void))self_delete_profile)();
	((void (*)(void))self_set_modified)();
	((void (*)(void))self_delayed_pc_cb)();
	((void (*)(void))self_get_modified)();
	((void (*)(void))self_new)();
	___xfce_mixer_profiles_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */

