/* Generated by GOB (v2.0.6) on Sat Jan 10 23:32:44 2004
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 6

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "xfce-mixer-profilebox-detail.h"

#include "xfce-mixer-profilebox-detail-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-profilebox-detail.gob"

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#line 33 "xfce-mixer-profilebox-detail.c"

#line 6 "mixer-profilebox-detail.gob"

#include <gtk/gtk.h>
#include "vc.h"
#include "xfce-mixer-profile.h"

#line 41 "xfce-mixer-profilebox-detail.c"

#line 11 "mixer-profilebox-detail.gob"

#include <libxfce4util/i18n.h>
#include "xfce-mixer-cache-vc.h"
#include "xfce-mixer-mcs-client.h"
#include "helpers3.inc"
#define emit

static void each_vccache_cb (volcontrol_t *vci, gpointer userdata);

extern XfceMixerMcsClient *mcsc;


#line 56 "xfce-mixer-profilebox-detail.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_PROFILEBOX_DETAIL(x)
#define SELF_CONST(x) XFCE_MIXER_PROFILEBOX_DETAIL_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_PROFILEBOX_DETAIL(x)
#define TYPE_SELF XFCE_TYPE_MIXER_PROFILEBOX_DETAIL
#define SELF_CLASS(x) XFCE_MIXER_PROFILEBOX_DETAIL_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_PROFILEBOX_DETAIL_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerProfileboxDetail Self;
typedef XfceMixerProfileboxDetailClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_profilebox_detail_class_init (XfceMixerProfileboxDetailClass * c) G_GNUC_UNUSED;
static void xfce_mixer_profilebox_detail_init (XfceMixerProfileboxDetail * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkVBoxClass *parent_class = NULL;

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define self_set_profile(args...) xfce_mixer_profilebox_detail_set_profile(args)
#define self_clear(args...) xfce_mixer_profilebox_detail_clear(args)
#define self_get_name(args...) xfce_mixer_profilebox_detail_get_name(args)
#define self_fill(args...) xfce_mixer_profilebox_detail_fill(args)
#define self_unfill(args...) xfce_mixer_profilebox_detail_unfill(args)
#define self_filln(args...) xfce_mixer_profilebox_detail_filln(args)
#define self_each_vccache_cb(args...) xfce_mixer_profilebox_detail_each_vccache_cb(args)
#define self_rows_reordered_cb(args...) xfce_mixer_profilebox_detail_rows_reordered_cb(args)
#define self_new() xfce_mixer_profilebox_detail_new()
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static void (* const self_set_profile) (XfceMixerProfileboxDetail * self, XfceMixerProfile * p) = xfce_mixer_profilebox_detail_set_profile;
static void (* const self_clear) (XfceMixerProfileboxDetail * self) = xfce_mixer_profilebox_detail_clear;
static gchar const * (* const self_get_name) (XfceMixerProfileboxDetail * self) = xfce_mixer_profilebox_detail_get_name;
static void (* const self_fill) (XfceMixerProfileboxDetail * self) = xfce_mixer_profilebox_detail_fill;
static void (* const self_unfill) (XfceMixerProfileboxDetail * self) = xfce_mixer_profilebox_detail_unfill;
static void (* const self_filln) (XfceMixerProfileboxDetail * self, char const * pname) = xfce_mixer_profilebox_detail_filln;
static void (* const self_each_vccache_cb) (XfceMixerProfileboxDetail * self, volcontrol_t * vci) = xfce_mixer_profilebox_detail_each_vccache_cb;
static void (* const self_rows_reordered_cb) (XfceMixerProfileboxDetail * self, GtkTreePath * arg1, GtkTreeIter * arg2, gpointer arg3, GtkTreeModel * model) = xfce_mixer_profilebox_detail_rows_reordered_cb;
static XfceMixerProfileboxDetail * (* const self_new) (void) = xfce_mixer_profilebox_detail_new;

GType
xfce_mixer_profilebox_detail_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerProfileboxDetailClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_profilebox_detail_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerProfileboxDetail),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_profilebox_detail_init,
		};

		type = g_type_register_static (GTK_TYPE_VBOX, "XfceMixerProfileboxDetail", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerProfileboxDetail *)g_object_new(xfce_mixer_profilebox_detail_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerProfileboxDetail * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerProfileboxDetail *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerProfileboxDetail *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerProfileboxDetail *)g_object_new_valist (xfce_mixer_profilebox_detail_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___dispose (GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::dispose"
	XfceMixerProfileboxDetail *self = XFCE_MIXER_PROFILEBOX_DETAIL (obj_self);
	if (G_OBJECT_CLASS (parent_class)->dispose) \
		(* G_OBJECT_CLASS (parent_class)->dispose) (obj_self);
#line 32 "mixer-profilebox-detail.gob"
	if(self->profile) { ((*(void (*)(void *))g_object_unref)) (self->profile); self->profile = NULL; }
#line 152 "xfce-mixer-profilebox-detail.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::finalize"
	XfceMixerProfileboxDetail *self = XFCE_MIXER_PROFILEBOX_DETAIL (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 34 "mixer-profilebox-detail.gob"
	if(self->valids) { ((*(void (*)(void *))g_free)) (self->valids); self->valids = NULL; }
#line 168 "xfce-mixer-profilebox-detail.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__

static void 
xfce_mixer_profilebox_detail_class_init (XfceMixerProfileboxDetailClass * c)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::class_init"
	GObjectClass *g_object_class = (GObjectClass*) c;

	parent_class = g_type_class_ref (GTK_TYPE_VBOX);

	g_object_class->dispose = ___dispose;
	g_object_class->finalize = ___finalize;
	return;
	c = NULL;
	g_object_class = NULL;
}
#undef __GOB_FUNCTION__
#line 53 "mixer-profilebox-detail.gob"
static void 
xfce_mixer_profilebox_detail_init (XfceMixerProfileboxDetail * self)
#line 192 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::init"
#line 11 "mixer-profilebox-detail.gob"
	self->dofill = FALSE;
#line 197 "xfce-mixer-profilebox-detail.c"
#line 11 "mixer-profilebox-detail.gob"
	self->profile = NULL;
#line 200 "xfce-mixer-profilebox-detail.c"
#line 11 "mixer-profilebox-detail.gob"
	self->valids = NULL;
#line 203 "xfce-mixer-profilebox-detail.c"
 {
#line 54 "mixer-profilebox-detail.gob"

		GtkBox *nbox;
		GtkWidget *dlabel;

		self->detail_box = GTK_BOX (self);
		gtk_box_set_spacing (self->detail_box, 5);

		self->detail_sw = GTK_SCROLLED_WINDOW (gtk_scrolled_window_new (NULL, NULL));
		gtk_scrolled_window_set_policy (self->detail_sw, GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
		gtk_widget_show (GTK_WIDGET (self->detail_sw));

		self->detail_model = GTK_TREE_STORE (gtk_tree_store_new (
			4, G_TYPE_BOOLEAN, G_TYPE_STRING, G_TYPE_STRING,
			G_TYPE_STRING
		));

		self->detail_tv = GTK_TREE_VIEW (gtk_tree_view_new ());

		gtk_tree_view_append_column (self->detail_tv, 
			tree_new_check_column ("", 0, GTK_TREE_MODEL (self->detail_model)
		));
		gtk_tree_view_append_column (self->detail_tv, 
			tree_new_text_column (_("Control"), 1
		));
		gtk_tree_view_append_column (self->detail_tv, 
			tree_new_text_column (_("Type"), 2
		));
		/*gtk_tree_view_append_column (self->detail_tv, 
			tree_new_text_column (_("Location"), 3
		));*/

		gtk_tree_view_set_model (self->detail_tv, GTK_TREE_MODEL (self->detail_model));
		gtk_tree_view_set_headers_visible (self->detail_tv, TRUE);

		gtk_widget_show (GTK_WIDGET (self->detail_tv));

		gtk_container_add (GTK_CONTAINER (self->detail_sw), GTK_WIDGET (self->detail_tv));

		dlabel = gtk_label_new (_("Profile Name:"));
		gtk_widget_show (dlabel);

		self->detail_name_entry = GTK_ENTRY (gtk_entry_new ());
		gtk_entry_set_max_length (self->detail_name_entry, 79);
		gtk_widget_show (GTK_WIDGET (self->detail_name_entry));

		nbox = GTK_BOX (gtk_hbox_new (FALSE, 5));
		gtk_box_pack_start (nbox, GTK_WIDGET (dlabel), FALSE, FALSE, 0);
		gtk_box_pack_start (nbox, GTK_WIDGET (self->detail_name_entry), TRUE, TRUE, 0);
		gtk_widget_show (GTK_WIDGET (nbox));

		gtk_box_pack_start (GTK_BOX (self->detail_box), GTK_WIDGET (nbox), FALSE, FALSE, 0);

		gtk_box_pack_start (GTK_BOX (self->detail_box), GTK_WIDGET (self->detail_sw), TRUE, TRUE, 0);

		gtk_tree_view_set_reorderable (self->detail_tv, TRUE);
		g_signal_connect_swapped (G_OBJECT (self->detail_model),
			"rows-reordered", G_CALLBACK (self_rows_reordered_cb),
			self);

		gtk_entry_set_activates_default (self->detail_name_entry, TRUE);
	
#line 267 "xfce-mixer-profilebox-detail.c"
 }
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__


#line 36 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_set_profile (XfceMixerProfileboxDetail * self, XfceMixerProfile * p)
#line 278 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::set_profile"
#line 36 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 36 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 285 "xfce-mixer-profilebox-detail.c"
{
#line 37 "mixer-profilebox-detail.gob"
	
		gchar const *t;
		if (self->profile) {
			g_object_unref (G_OBJECT (self->profile));
			self->profile = NULL;
		}

		if (p) {
			self->profile = p;
			g_object_ref (G_OBJECT (p));
			t = xfce_mixer_profile_get_title (p);
			self_filln (self, t);
		} else
			self_unfill (self);
	}}
#line 303 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__


#line 116 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_clear (XfceMixerProfileboxDetail * self)
#line 310 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::clear"
#line 116 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 116 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 317 "xfce-mixer-profilebox-detail.c"
{
#line 117 "mixer-profilebox-detail.gob"
	
		gtk_entry_set_text (GTK_ENTRY (self->detail_name_entry), "");
		gtk_tree_store_clear (self->detail_model);
	}}
#line 324 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 122 "mixer-profilebox-detail.gob"
gchar const * 
xfce_mixer_profilebox_detail_get_name (XfceMixerProfileboxDetail * self)
#line 330 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::get_name"
#line 122 "mixer-profilebox-detail.gob"
	g_return_val_if_fail (self != NULL, (gchar const * )0);
#line 122 "mixer-profilebox-detail.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self), (gchar const * )0);
#line 337 "xfce-mixer-profilebox-detail.c"
{
#line 123 "mixer-profilebox-detail.gob"
	
		return gtk_entry_get_text (self->detail_name_entry);
	}}
#line 343 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 127 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_fill (XfceMixerProfileboxDetail * self)
#line 349 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::fill"
#line 127 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 127 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 356 "xfce-mixer-profilebox-detail.c"
{
#line 128 "mixer-profilebox-detail.gob"
	
		self->dofill = TRUE;
		gtk_tree_store_clear (self->detail_model);
		if (self->valids)
			g_free (self->valids);
		self->valids = NULL;

		if (mcsc)
			self->valids = xfce_mixer_mcs_client_get_useful_controls (mcsc,
                                vc_get_device ());

		xfce_mixer_cache_vc_foreach ((GFunc)each_vccache_cb, self);
		gtk_widget_set_sensitive (GTK_WIDGET (self), TRUE);
		g_free (self->valids);
		self->valids = NULL;
	}}
#line 375 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 145 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_unfill (XfceMixerProfileboxDetail * self)
#line 381 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::unfill"
#line 145 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 145 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 388 "xfce-mixer-profilebox-detail.c"
{
#line 146 "mixer-profilebox-detail.gob"
	
		self->dofill = FALSE;
		gtk_widget_set_sensitive (GTK_WIDGET (self), FALSE);
		self_clear (self);
	}}
#line 396 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 152 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_filln (XfceMixerProfileboxDetail * self, char const * pname)
#line 402 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::filln"
#line 152 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 152 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 409 "xfce-mixer-profilebox-detail.c"
{
#line 153 "mixer-profilebox-detail.gob"
	
		gtk_entry_set_text (GTK_ENTRY (self->detail_name_entry), pname);
		self_fill (self);
	}}
#line 416 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 158 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_each_vccache_cb (XfceMixerProfileboxDetail * self, volcontrol_t * vci)
#line 422 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::each_vccache_cb"
#line 158 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 158 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 429 "xfce-mixer-profilebox-detail.c"
{
#line 159 "mixer-profilebox-detail.gob"
	
		GtkTreeIter iter;
		gchar *ty;
		gchar *uct;
		gboolean b;

		b = FALSE;

		if (self->valids) {
			uct = g_strdup_printf ("@%s@", vci->name);
			if (uct) {
				b = g_strrstr (self->valids, uct) != NULL;
                                /*printf ("%s %s %d", uc , uct, (int)b );*/
				g_free (uct);
                        }   
                }

		if (!b) {
			return;
		}

		ty = _("<unknown>");
		switch(vci->type) {
		case CT_SLIDER: ty = _("<slider>"); break;
		case CT_ONOFF: ty = _("<onoff>"); break;
		case CT_SELECT: ty = _("<select>"); break;
		}

		gtk_tree_store_append (self->detail_model, &iter, NULL);
		gtk_tree_store_set (self->detail_model, &iter, 
			0, TRUE,
			1, vci->name, 
			2, ty,
		-1);
	}}
#line 467 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 195 "mixer-profilebox-detail.gob"
void 
xfce_mixer_profilebox_detail_rows_reordered_cb (XfceMixerProfileboxDetail * self, GtkTreePath * arg1, GtkTreeIter * arg2, gpointer arg3, GtkTreeModel * model)
#line 473 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::rows_reordered_cb"
#line 195 "mixer-profilebox-detail.gob"
	g_return_if_fail (self != NULL);
#line 195 "mixer-profilebox-detail.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX_DETAIL (self));
#line 480 "xfce-mixer-profilebox-detail.c"
{
#line 197 "mixer-profilebox-detail.gob"
	
		g_warning ("reordered");
	}}
#line 486 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__

#line 202 "mixer-profilebox-detail.gob"
XfceMixerProfileboxDetail * 
xfce_mixer_profilebox_detail_new (void)
#line 492 "xfce-mixer-profilebox-detail.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox:Detail::new"
{
#line 202 "mixer-profilebox-detail.gob"
	
		return XFCE_MIXER_PROFILEBOX_DETAIL (GET_NEW);
	}}
#line 500 "xfce-mixer-profilebox-detail.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___xfce_mixer_profilebox_detail_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))GET_NEW_VARG)();
	((void (*)(void))self_set_profile)();
	((void (*)(void))self_clear)();
	((void (*)(void))self_get_name)();
	((void (*)(void))self_fill)();
	((void (*)(void))self_unfill)();
	((void (*)(void))self_filln)();
	((void (*)(void))self_each_vccache_cb)();
	((void (*)(void))self_rows_reordered_cb)();
	((void (*)(void))self_new)();
	___xfce_mixer_profilebox_detail_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */


#line 207 "mixer-profilebox-detail.gob"

static void each_vccache_cb (volcontrol_t *vci, gpointer userdata)
{
	XfceMixerProfileboxDetail *d;
	d = XFCE_MIXER_PROFILEBOX_DETAIL (userdata);

	if (vci && vci->name) {
		xfce_mixer_profilebox_detail_each_vccache_cb (d, vci);
	}
}

#line 540 "xfce-mixer-profilebox-detail.c"
