/* Generated by GOB (v2.0.9) on Mon Nov 22 22:45:37 2004
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 9

#define selfp (self->_priv)

#include "xfce-mixer-profiledlg.h"

#include "xfce-mixer-profiledlg-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-profiledlg.gob"

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#line 34 "xfce-mixer-profiledlg.c"

#line 6 "mixer-profiledlg.gob"

#include <gtk/gtk.h>
#include "xfce-mixer-profilebox.h"

#line 41 "xfce-mixer-profiledlg.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_PROFILEDLG(x)
#define SELF_CONST(x) XFCE_MIXER_PROFILEDLG_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_PROFILEDLG(x)
#define TYPE_SELF XFCE_TYPE_MIXER_PROFILEDLG
#define SELF_CLASS(x) XFCE_MIXER_PROFILEDLG_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_PROFILEDLG_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerProfiledlg Self;
typedef XfceMixerProfiledlgClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_profiledlg_class_init (XfceMixerProfiledlgClass * c) G_GNUC_UNUSED;
static void xfce_mixer_profiledlg_init (XfceMixerProfiledlg * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkDialogClass *parent_class = NULL;

/* Short form macros */
#define self_response_cb xfce_mixer_profiledlg_response_cb
#define self_new xfce_mixer_profiledlg_new
GType
xfce_mixer_profiledlg_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerProfiledlgClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_profiledlg_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerProfiledlg),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_profiledlg_init,
			NULL
		};

		type = g_type_register_static (GTK_TYPE_DIALOG, "XfceMixerProfiledlg", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerProfiledlg *)g_object_new(xfce_mixer_profiledlg_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerProfiledlg * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerProfiledlg *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerProfiledlg *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerProfiledlg *)g_object_new_valist (xfce_mixer_profiledlg_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
xfce_mixer_profiledlg_class_init (XfceMixerProfiledlgClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiledlg::class_init"

	parent_class = g_type_class_ref (GTK_TYPE_DIALOG);

}
#undef __GOB_FUNCTION__
#line 14 "mixer-profiledlg.gob"
static void 
xfce_mixer_profiledlg_init (XfceMixerProfiledlg * self G_GNUC_UNUSED)
#line 119 "xfce-mixer-profiledlg.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiledlg::init"
#line 6 "mixer-profiledlg.gob"
	self->pbox = NULL;
#line 124 "xfce-mixer-profiledlg.c"
 {
#line 15 "mixer-profiledlg.gob"

		self->pbox = xfce_mixer_profilebox_new ();
		gtk_widget_show (GTK_WIDGET (self->pbox));
		gtk_box_pack_start (GTK_BOX (GTK_DIALOG (self)->vbox), 
			GTK_WIDGET (self->pbox), TRUE, TRUE, 0
		);

		gtk_dialog_add_buttons (GTK_DIALOG (self),
			GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL,
			GTK_STOCK_OK, GTK_RESPONSE_OK,
			NULL);

		g_signal_connect_swapped (G_OBJECT (self), "response",
			G_CALLBACK (self_response_cb), self);
	
#line 142 "xfce-mixer-profiledlg.c"
 }
}
#undef __GOB_FUNCTION__



#line 31 "mixer-profiledlg.gob"
void 
xfce_mixer_profiledlg_response_cb (XfceMixerProfiledlg * self, gint rc, GtkDialog * d)
#line 152 "xfce-mixer-profiledlg.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiledlg::response_cb"
#line 31 "mixer-profiledlg.gob"
	g_return_if_fail (self != NULL);
#line 31 "mixer-profiledlg.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEDLG (self));
#line 159 "xfce-mixer-profiledlg.c"
{
#line 32 "mixer-profiledlg.gob"
	
		if (rc == GTK_RESPONSE_OK) {
			if (self->pbox)
				xfce_mixer_profilebox_save (self->pbox);
		}
	}}
#line 168 "xfce-mixer-profiledlg.c"
#undef __GOB_FUNCTION__

#line 39 "mixer-profiledlg.gob"
XfceMixerProfiledlg * 
xfce_mixer_profiledlg_new (void)
#line 174 "xfce-mixer-profiledlg.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profiledlg::new"
{
#line 40 "mixer-profiledlg.gob"
	
		return XFCE_MIXER_PROFILEDLG (GET_NEW);
	}}
#line 182 "xfce-mixer-profiledlg.c"
#undef __GOB_FUNCTION__
