/* Generated by GOB (v2.0.9)   (do not edit directly) */

#ifndef __XFCE_MIXER_SWITCH_PRIVATE_H__
#define __XFCE_MIXER_SWITCH_PRIVATE_H__

#include "xfce-mixer-switch.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include "xfce-mixer-control.h"

#line 7 "mixer-switch.gob"
#line 19 "xfce-mixer-switch-private.h"
void 	xfce_mixer_switch_changed_cb	(XfceMixerSwitch * self, gpointer userdata);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
