/* Generated by GOB (v2.0.6) on Tue Feb 24 18:42:21 2004
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 6

#define selfp (self->_priv)

#include "xfce-mixer-profilebox.h"

#include "xfce-mixer-profilebox-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-profilebox.gob"

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#line 31 "xfce-mixer-profilebox.c"

#line 6 "mixer-profilebox.gob"

#include <gtk/gtk.h>
#include "xfce-mixer-profilebox-detail.h"
#include "xfce-mixer-profiles.h"
#include "xfce-mixer-profile.h"

#line 40 "xfce-mixer-profilebox.c"

#line 12 "mixer-profilebox.gob"

#include <libxfce4util/i18n.h>
#define NO_TREE_CHECK_COLUMN
#include "helpers3.inc"
#include "stringlist.inc"
#include "msgdlg.inc"
#include "main.h"

static void profile_insert_cb (GtkWidget *w, gpointer user_data);
static void profile_delete_cb (GtkWidget *w, gpointer user_data);

/*static GList *list_remove_nth (GList *go, gint i, void ())
{
	gpointer d;
	d = g_list_nth_data (go, i);
	return g_list_remove (go, d);
}*/

static void each_selstring_cb (GtkTreeModel *model, GtkTreePath *path, GtkTreeIter *iter, gpointer data)
{
	GList **gg;
	gchar *s;
	gg = (GList **)data;

	gtk_tree_model_get (model, iter, 0, &s, -1);
	if (s) {
		*gg = g_list_append (*gg, s);
	}
}

/*
static void profiles_free (GList *go)
{
	GList *g;
	GObject *p;
	g = go;
	while (g) {
		p = G_OBJECT (g->data);
		g_object_unref (p);

		g = g_list_next (g);
	}

	if (go)
		g_list_free (go);
}
*/


#line 92 "xfce-mixer-profilebox.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_PROFILEBOX(x)
#define SELF_CONST(x) XFCE_MIXER_PROFILEBOX_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_PROFILEBOX(x)
#define TYPE_SELF XFCE_TYPE_MIXER_PROFILEBOX
#define SELF_CLASS(x) XFCE_MIXER_PROFILEBOX_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_PROFILEBOX_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerProfilebox Self;
typedef XfceMixerProfileboxClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_profilebox_class_init (XfceMixerProfileboxClass * c) G_GNUC_UNUSED;
static void xfce_mixer_profilebox_init (XfceMixerProfilebox * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkVBoxClass *parent_class = NULL;

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define self_destroy_cb(args...) xfce_mixer_profilebox_destroy_cb(args)
#define self_profiles_changed_cb(args...) xfce_mixer_profilebox_profiles_changed_cb(args)
#define self_save(args...) xfce_mixer_profilebox_save(args)
#define self_sel_changed_cb(args...) xfce_mixer_profilebox_sel_changed_cb(args)
#define self_profile_exists(args...) xfce_mixer_profilebox_profile_exists(args)
#define self_row_inserted_cb(args...) xfce_mixer_profilebox_row_inserted_cb(args)
#define self_row_deleted_cb(args...) xfce_mixer_profilebox_row_deleted_cb(args)
#define self_rowcnt_updated_cb(args...) xfce_mixer_profilebox_rowcnt_updated_cb(args)
#define self_profile_insert_cb(args...) xfce_mixer_profilebox_profile_insert_cb(args)
#define self_delete_profile(args...) xfce_mixer_profilebox_delete_profile(args)
#define self_profile_delete_cb(args...) xfce_mixer_profilebox_profile_delete_cb(args)
#define self_profiles_updated(args...) xfce_mixer_profilebox_profiles_updated(args)
#define self_select_last(args...) xfce_mixer_profilebox_select_last(args)
#define self_new_dlg(args...) xfce_mixer_profilebox_new_dlg(args)
#define self_new() xfce_mixer_profilebox_new()
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static void (* const self_destroy_cb) (XfceMixerProfilebox * self, GtkWidget * w) = xfce_mixer_profilebox_destroy_cb;
static void (* const self_profiles_changed_cb) (XfceMixerProfilebox * self, GObject * obj) = xfce_mixer_profilebox_profiles_changed_cb;
static void (* const self_save) (XfceMixerProfilebox * self) = xfce_mixer_profilebox_save;
static void (* const self_sel_changed_cb) (XfceMixerProfilebox * self, GtkTreeSelection * sel) = xfce_mixer_profilebox_sel_changed_cb;
static gboolean (* const self_profile_exists) (XfceMixerProfilebox * self, gchar const * name) = xfce_mixer_profilebox_profile_exists;
static void (* const self_row_inserted_cb) (XfceMixerProfilebox * self, GtkTreePath * path, GtkTreeIter * iter, GtkTreeModel * model) = xfce_mixer_profilebox_row_inserted_cb;
static void (* const self_row_deleted_cb) (XfceMixerProfilebox * self, GtkTreePath * path, GtkTreeModel * model) = xfce_mixer_profilebox_row_deleted_cb;
static void (* const self_rowcnt_updated_cb) (XfceMixerProfilebox * self) = xfce_mixer_profilebox_rowcnt_updated_cb;
static void (* const self_profile_insert_cb) (XfceMixerProfilebox * self) = xfce_mixer_profilebox_profile_insert_cb;
static void (* const self_delete_profile) (XfceMixerProfilebox * self, gchar const * name) = xfce_mixer_profilebox_delete_profile;
static void (* const self_profile_delete_cb) (XfceMixerProfilebox * self) = xfce_mixer_profilebox_profile_delete_cb;
static void (* const self_profiles_updated) (XfceMixerProfilebox * self) = xfce_mixer_profilebox_profiles_updated;
static void (* const self_select_last) (XfceMixerProfilebox * self) = xfce_mixer_profilebox_select_last;
static void (* const self_new_dlg) (XfceMixerProfilebox * self) = xfce_mixer_profilebox_new_dlg;
static XfceMixerProfilebox * (* const self_new) (void) = xfce_mixer_profilebox_new;

GType
xfce_mixer_profilebox_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerProfileboxClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_profilebox_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerProfilebox),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_profilebox_init,
		};

		type = g_type_register_static (GTK_TYPE_VBOX, "XfceMixerProfilebox", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerProfilebox *)g_object_new(xfce_mixer_profilebox_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerProfilebox * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerProfilebox *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerProfilebox *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerProfilebox *)g_object_new_valist (xfce_mixer_profilebox_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
xfce_mixer_profilebox_class_init (XfceMixerProfileboxClass * c)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::class_init"

	parent_class = g_type_class_ref (GTK_TYPE_VBOX);

	return;
	c = NULL;
}
#undef __GOB_FUNCTION__
#line 79 "mixer-profilebox.gob"
static void 
xfce_mixer_profilebox_init (XfceMixerProfilebox * self)
#line 204 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::init"
#line 12 "mixer-profilebox.gob"
	self->detail = NULL;
#line 209 "xfce-mixer-profilebox.c"
#line 12 "mixer-profilebox.gob"
	self->profiles_updated_lock = 0;
#line 212 "xfce-mixer-profilebox.c"
 {
#line 80 "mixer-profilebox.gob"

		GtkBox *devbox;
		GtkWidget *d1label;
		GtkWidget *dal;
		gchar const *dd;
		GtkTreeSelection *sels;

		devbox = GTK_BOX (gtk_hbox_new (FALSE, 5));
		d1label = gtk_label_new (_("Device:"));
		gtk_widget_show (GTK_WIDGET (d1label));
		gtk_box_pack_start (devbox, d1label, FALSE, FALSE, 0);

		dd = device;
		if (!dd)
			dd = "";

		self->device_label = GTK_LABEL (gtk_label_new (dd));
		gtk_widget_show (GTK_WIDGET (self->device_label));

		gtk_box_pack_start (devbox, GTK_WIDGET (self->device_label), FALSE, FALSE, 0);
		gtk_widget_show (GTK_WIDGET (devbox));

		self->hbox = GTK_BOX (gtk_hbox_new (FALSE, 0));
		gtk_widget_show (GTK_WIDGET (self->hbox));

		dal = gtk_alignment_new (0.5, 0.5, 0.0, 0.0);
		gtk_widget_show (GTK_WIDGET (dal));

		gtk_container_add (GTK_CONTAINER (dal), GTK_WIDGET (devbox));

		self->sep2 = gtk_hseparator_new ();
		gtk_widget_show (self->sep2);

		gtk_box_pack_start (GTK_BOX (self), GTK_WIDGET (dal), FALSE, FALSE, 0);
		gtk_box_pack_start (GTK_BOX (self), GTK_WIDGET (self->sep2), FALSE, FALSE, 3);
		gtk_box_pack_start (GTK_BOX (self), GTK_WIDGET (self->hbox), TRUE, TRUE, 3);

		self->detail = xfce_mixer_profilebox_detail_new ();
		gtk_widget_show (GTK_WIDGET (self->detail));

		self->sep1 = gtk_vseparator_new ();
		gtk_widget_show (self->sep1);

		self->profiles_box = GTK_BOX (gtk_vbox_new (FALSE, 0));
		gtk_widget_show (GTK_WIDGET (self->profiles_box));

		self->profiles_toolbar = GTK_TOOLBAR (gtk_toolbar_new ());

#if 0
		gtk_toolbar_append_item (self->profiles_toolbar,
			"test", "testtip", NULL, NULL/*icon*/, NULL/*callback*/,
			NULL/*user_data*/
		);
#endif

		gtk_toolbar_set_style (self->profiles_toolbar,
			GTK_TOOLBAR_ICONS
		);

		self->profiles_insert_button =
			gtk_toolbar_insert_stock (self->profiles_toolbar,
			GTK_STOCK_ADD,
			_("Create new profile"),
			NULL,
			(GtkSignalFunc)profile_insert_cb /*cb*/,
			(gpointer)self,
			-1
		);
		self->profiles_delete_button =
			gtk_toolbar_insert_stock (self->profiles_toolbar,
			GTK_STOCK_REMOVE,
			_("Delete this profile"),
			NULL,
			(GtkSignalFunc)profile_delete_cb /*cb*/,
			(gpointer)self,
			-1
		);

		gtk_widget_show (GTK_WIDGET (self->profiles_toolbar));

		self->profiles_sw = GTK_SCROLLED_WINDOW (gtk_scrolled_window_new (NULL, NULL));
		gtk_scrolled_window_set_policy (self->profiles_sw, GTK_POLICY_NEVER, GTK_POLICY_AUTOMATIC);
		gtk_widget_show (GTK_WIDGET (self->profiles_sw));

		self->profiles_model = GTK_TREE_STORE (gtk_tree_store_new (1, G_TYPE_STRING));

		self->profiles_tv = GTK_TREE_VIEW (gtk_tree_view_new ());
		gtk_tree_view_set_model (self->profiles_tv, GTK_TREE_MODEL (self->profiles_model));

		gtk_tree_view_append_column (self->profiles_tv, 
			tree_new_text_column (_("Profile"), 0
		));

		gtk_tree_view_set_headers_visible (self->profiles_tv, FALSE);

		gtk_widget_show (GTK_WIDGET (self->profiles_tv));

		gtk_container_add (GTK_CONTAINER (self->profiles_sw), GTK_WIDGET (self->profiles_tv));

		gtk_box_pack_start (GTK_BOX (self->profiles_box), GTK_WIDGET (self->profiles_toolbar), FALSE, FALSE, 0);
		gtk_box_pack_start (GTK_BOX (self->profiles_box), GTK_WIDGET (self->profiles_sw), TRUE, TRUE, 0);

		gtk_box_pack_start (GTK_BOX (self->hbox), GTK_WIDGET (self->profiles_box), TRUE, TRUE, 0);
		gtk_box_pack_start (GTK_BOX (self->hbox), GTK_WIDGET (self->sep1), FALSE, FALSE, 0);
		gtk_box_pack_start (GTK_BOX (self->hbox), GTK_WIDGET (self->detail), TRUE, TRUE, 0);
		gtk_box_set_spacing (GTK_BOX (self->hbox), 3);

		gtk_widget_set_size_request (GTK_WIDGET (self->hbox), -1, 200);

		/*self->profiles_insert_button;*/
		/*gtk_widget_set_sensitive (self->profiles_delete_button, FALSE);*/

		g_signal_connect_swapped (G_OBJECT (self->profiles_model),
			"row-inserted", G_CALLBACK (self_row_inserted_cb),
			self);

		g_signal_connect_swapped (G_OBJECT (self->profiles_model),
			"row-deleted", G_CALLBACK (self_row_inserted_cb),
			self);

		sels = gtk_tree_view_get_selection (self->profiles_tv);
		g_signal_connect_swapped (G_OBJECT (sels),
			"changed", G_CALLBACK (self_sel_changed_cb),
			self
		);

		self->changed_handle = g_signal_connect_swapped (G_OBJECT (profiles), 
			"profiles-changed",
			G_CALLBACK (self_profiles_changed_cb), self);

		g_signal_connect_swapped (G_OBJECT (self),
			"destroy", G_CALLBACK (self_destroy_cb),
			self
		);

		self_profiles_updated (self);

		self_rowcnt_updated_cb (self);

		/*self_load (self);*/

	
#line 357 "xfce-mixer-profilebox.c"
 }
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__



#line 223 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_destroy_cb (XfceMixerProfilebox * self, GtkWidget * w)
#line 369 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::destroy_cb"
#line 223 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 223 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 376 "xfce-mixer-profilebox.c"
{
#line 224 "mixer-profilebox.gob"
	
		g_signal_handler_disconnect (G_OBJECT (profiles), self->changed_handle);
	}}
#line 382 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 228 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_profiles_changed_cb (XfceMixerProfilebox * self, GObject * obj)
#line 388 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::profiles_changed_cb"
#line 228 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 228 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 395 "xfce-mixer-profilebox.c"
{
#line 229 "mixer-profilebox.gob"
	
		self_profiles_updated (self);
	}}
#line 401 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 233 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_save (XfceMixerProfilebox * self)
#line 407 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::save"
#line 233 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 233 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 414 "xfce-mixer-profilebox.c"
{
#line 234 "mixer-profilebox.gob"
	
		if (self->detail)
			xfce_mixer_profilebox_detail_save (self->detail);
	}}
#line 421 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 239 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_sel_changed_cb (XfceMixerProfilebox * self, GtkTreeSelection * sel)
#line 427 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::sel_changed_cb"
#line 239 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 239 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 434 "xfce-mixer-profilebox.c"
{
#line 240 "mixer-profilebox.gob"
	
		gboolean issel;
		GtkTreeModel *model;
		GtkTreeIter iter;
		gchar *s;
		XfceMixerProfile *p;

		/* save current "detail" */
		xfce_mixer_profilebox_detail_save (self->detail);

		issel = gtk_tree_selection_get_selected (sel, &model, &iter);

		if (issel) {
			gtk_tree_model_get (GTK_TREE_MODEL (self->profiles_model),
				&iter, 0, &s, -1);

			p = xfce_mixer_profiles_get_profile (profiles, s);

			xfce_mixer_profile_set_title (p, s);

			g_free (s);

			xfce_mixer_profilebox_detail_set_profile (self->detail, p);
		} else {
			xfce_mixer_profilebox_detail_set_profile (self->detail, NULL);
		}

	}}
#line 465 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 292 "mixer-profilebox.gob"
gboolean 
xfce_mixer_profilebox_profile_exists (XfceMixerProfilebox * self, gchar const * name)
#line 471 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::profile_exists"
#line 292 "mixer-profilebox.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 292 "mixer-profilebox.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PROFILEBOX (self), (gboolean )0);
#line 478 "xfce-mixer-profilebox.c"
{
#line 293 "mixer-profilebox.gob"
	
		XfceMixerProfile *p;
		if (!name)
			return TRUE;

		p = xfce_mixer_profiles_get_profile (profiles, name);
		if (p) {
			g_object_unref (G_OBJECT (p));
			return TRUE;
		}

		return FALSE;
	}}
#line 494 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 307 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_row_inserted_cb (XfceMixerProfilebox * self, GtkTreePath * path, GtkTreeIter * iter, GtkTreeModel * model)
#line 500 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::row_inserted_cb"
#line 307 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 307 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 507 "xfce-mixer-profilebox.c"
{
#line 308 "mixer-profilebox.gob"
	
		if (self->profiles_updated_lock)
			return;

		self_rowcnt_updated_cb (self);
	}}
#line 516 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 315 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_row_deleted_cb (XfceMixerProfilebox * self, GtkTreePath * path, GtkTreeModel * model)
#line 522 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::row_deleted_cb"
#line 315 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 315 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 529 "xfce-mixer-profilebox.c"
{
#line 316 "mixer-profilebox.gob"
	
		if (self->profiles_updated_lock)
			return;

		xfce_mixer_profilebox_detail_set_profile (self->detail, NULL);

		self_rowcnt_updated_cb (self);
	}}
#line 540 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 325 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_rowcnt_updated_cb (XfceMixerProfilebox * self)
#line 546 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::rowcnt_updated_cb"
#line 325 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 325 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 553 "xfce-mixer-profilebox.c"
{
#line 326 "mixer-profilebox.gob"
	
		gboolean b;

		b = gtk_tree_model_iter_n_children (GTK_TREE_MODEL (self->profiles_model), NULL) > 0;
		gtk_widget_set_sensitive (GTK_WIDGET (self->profiles_delete_button), b);
		gtk_widget_set_sensitive (GTK_WIDGET (self->detail), b);
	}}
#line 563 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 334 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_profile_insert_cb (XfceMixerProfilebox * self)
#line 569 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::profile_insert_cb"
#line 334 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 334 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 576 "xfce-mixer-profilebox.c"
{
#line 335 "mixer-profilebox.gob"
	

		self_new_dlg (self);
	}}
#line 583 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 340 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_delete_profile (XfceMixerProfilebox * self, gchar const * name)
#line 589 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::delete_profile"
#line 340 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 340 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 596 "xfce-mixer-profilebox.c"
{
#line 341 "mixer-profilebox.gob"
	
		xfce_mixer_profiles_delete_profile (profiles, name);

		self_profiles_updated (self);
	}}
#line 604 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 347 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_profile_delete_cb (XfceMixerProfilebox * self)
#line 610 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::profile_delete_cb"
#line 347 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 347 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 617 "xfce-mixer-profilebox.c"
{
#line 348 "mixer-profilebox.gob"
	
		GtkTreeSelection *sels;
		GList *g;
		GList *gg;
		gint cnt;
		gchar const *q;
		gchar const *name;
		gchar *s;
		GtkResponseType rc;
		GtkWindow *parent;

		parent = GTK_WINDOW (gtk_widget_get_toplevel (GTK_WIDGET (self)));

		sels = gtk_tree_view_get_selection (self->profiles_tv);
		if (!sels)
			return;

		g = NULL;

		gtk_tree_selection_selected_foreach (sels, each_selstring_cb, (gpointer) &g);

		if (!g) /* nothing selected */
			return;

		cnt = g_list_length (g);
		if (cnt > 1) {
			q = _("Really delete those %d profiles?");
			s = g_strdup_printf (q, cnt);
		} else {
			q = _("Really delete profile \"%s\"?");
			s = g_strdup_printf (q, (gchar const *)g->data);
		}

		rc = annoy_user (parent, GTK_MESSAGE_QUESTION, GTK_BUTTONS_YES_NO, "%s", s);
		g_free (s);

		if (rc == GTK_RESPONSE_YES) {
			/* really delete */
			gg = g;
			while (gg) {
				name = (char const *)gg->data;
				if (name) {
					self_delete_profile (self, name);
				}
				gg = g_list_next (gg);
			}

			/* unfill right side */

			xfce_mixer_profilebox_detail_set_profile (self->detail, NULL);
		}

		if (g)
			stringlist_free (g);
	}}
#line 675 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 404 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_profiles_updated (XfceMixerProfilebox * self)
#line 681 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::profiles_updated"
#line 404 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 404 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 688 "xfce-mixer-profilebox.c"
{
#line 405 "mixer-profilebox.gob"
	
		GtkTreeStore *store;
		GtkTreeSelection *sels;
		GList *g;
		gchar const *s;
		gchar *prevsel;
		GList *profile_names;
		GtkTreeIter iter;
		GtkTreeModel *model;

		if (self->profiles_updated_lock)
			return;

		self->profiles_updated_lock = 1;

		store = self->profiles_model;

		sels = gtk_tree_view_get_selection (self->profiles_tv);
		prevsel = NULL;
		if (gtk_tree_selection_get_selected (sels, &model, &iter)) {
			gtk_tree_model_get (model, &iter, 0, &prevsel, -1);
		}

		gtk_tree_store_clear (store);

		profile_names = xfce_mixer_profiles_get_profile_names (profiles);

		g = profile_names;
		while (g) {
			s = (gchar const *)g->data;
			gtk_tree_store_append (store, &iter, NULL);
			gtk_tree_store_set (store, &iter,
				0, s,
				-1
			);

			if (s && prevsel && g_str_equal (s, prevsel))
				gtk_tree_selection_select_iter (sels, &iter);

			g = g_list_next (g);
		}
		if (prevsel) {
			g_free (prevsel);
			prevsel = NULL;
		}

		stringlist_free (profile_names);

		self_rowcnt_updated_cb (self);

		self->profiles_updated_lock = 0;
	}}
#line 743 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 458 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_select_last (XfceMixerProfilebox * self)
#line 749 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::select_last"
#line 458 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 458 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 756 "xfce-mixer-profilebox.c"
{
#line 459 "mixer-profilebox.gob"
	
		gboolean b;
		GtkTreeSelection *sels;
		GtkTreeIter iter;
		GtkTreeIter piter;

		sels = gtk_tree_view_get_selection (self->profiles_tv);
		b = gtk_tree_model_get_iter_first (GTK_TREE_MODEL (self->profiles_model), &iter);
		if (b) {
			while (b) {
				piter = iter;
				b = gtk_tree_model_iter_next (
					GTK_TREE_MODEL (self->profiles_model), 
					&iter
				);
			}
			gtk_tree_selection_select_iter (sels, &piter);
		}
	}}
#line 778 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 479 "mixer-profilebox.gob"
void 
xfce_mixer_profilebox_new_dlg (XfceMixerProfilebox * self)
#line 784 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::new_dlg"
#line 479 "mixer-profilebox.gob"
	g_return_if_fail (self != NULL);
#line 479 "mixer-profilebox.gob"
	g_return_if_fail (XFCE_IS_MIXER_PROFILEBOX (self));
#line 791 "xfce-mixer-profilebox.c"
{
#line 480 "mixer-profilebox.gob"
	
		GtkDialog *dlg;
		gchar *s;
		GtkWindow *parent;
		XfceMixerProfileboxDetail *detail;
		XfceMixerProfile *p;
		gboolean retry;
		gchar const *name;
		parent =  GTK_WINDOW (gtk_widget_get_toplevel (GTK_WIDGET (self)));

		s = g_strdup_printf (
			_("%s - New"),
			gtk_window_get_title (parent)
		);
		dlg = GTK_DIALOG (gtk_dialog_new_with_buttons (
			s, parent,
			GTK_DIALOG_DESTROY_WITH_PARENT | GTK_DIALOG_MODAL,
			GTK_STOCK_CANCEL, GTK_RESPONSE_CANCEL,
			GTK_STOCK_OK, GTK_RESPONSE_OK,
			NULL
		));
		g_free (s);

		gtk_dialog_set_default_response (dlg, GTK_RESPONSE_OK);

		detail = xfce_mixer_profilebox_detail_new ();
		gtk_widget_show (GTK_WIDGET (detail));
		gtk_box_pack_start (GTK_BOX (dlg->vbox), GTK_WIDGET (detail), TRUE, TRUE, 0);

		gtk_widget_set_size_request (GTK_WIDGET (detail), -1, 200);

		p = XFCE_MIXER_PROFILE (xfce_mixer_profile_new (""));
		xfce_mixer_profilebox_detail_set_profile (detail, p);

		xfce_mixer_profilebox_detail_check_all (detail);

		retry = TRUE;
		while (retry) {
			gtk_window_present (GTK_WINDOW (dlg));
			if (gtk_dialog_run (dlg) != GTK_RESPONSE_OK)
				break;

			xfce_mixer_profilebox_detail_save (detail);
			retry = FALSE;
			name = xfce_mixer_profilebox_detail_get_name (detail);
			if (!name || !name[0]) {
				annoy_user (parent, GTK_MESSAGE_ERROR,
					GTK_BUTTONS_OK, "%s", 
				_("A profile needs a name"));
				retry = TRUE;
			} else if (!self_profile_exists (self, name)) {
				xfce_mixer_profile_set_title (p, name);
				xfce_mixer_profiles_add_profile (profiles, p);
				g_object_unref (G_OBJECT (p));
				/* TODO really insert */
				p = NULL;

				self_profiles_updated (self);
				self_select_last (self);
			} else {
				annoy_user (parent, GTK_MESSAGE_ERROR,
					GTK_BUTTONS_OK, "%s", 
				_("A profile with that name already exists"));
				retry = TRUE;
			}

		}
		gtk_widget_destroy (GTK_WIDGET (dlg));
		if (p) {
			g_object_unref (G_OBJECT (p));
		}
	}}
#line 866 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__

#line 553 "mixer-profilebox.gob"
XfceMixerProfilebox * 
xfce_mixer_profilebox_new (void)
#line 872 "xfce-mixer-profilebox.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Profilebox::new"
{
#line 554 "mixer-profilebox.gob"
	
		return XFCE_MIXER_PROFILEBOX (GET_NEW);
	}}
#line 880 "xfce-mixer-profilebox.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___xfce_mixer_profilebox_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))GET_NEW_VARG)();
	((void (*)(void))self_destroy_cb)();
	((void (*)(void))self_profiles_changed_cb)();
	((void (*)(void))self_save)();
	((void (*)(void))self_sel_changed_cb)();
	((void (*)(void))self_profile_exists)();
	((void (*)(void))self_row_inserted_cb)();
	((void (*)(void))self_row_deleted_cb)();
	((void (*)(void))self_rowcnt_updated_cb)();
	((void (*)(void))self_profile_insert_cb)();
	((void (*)(void))self_delete_profile)();
	((void (*)(void))self_profile_delete_cb)();
	((void (*)(void))self_profiles_updated)();
	((void (*)(void))self_select_last)();
	((void (*)(void))self_new_dlg)();
	((void (*)(void))self_new)();
	___xfce_mixer_profilebox_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */


#line 559 "mixer-profilebox.gob"

static void profile_insert_cb (GtkWidget *w, gpointer user_data)
{
	XfceMixerProfilebox *pb;
	pb = XFCE_MIXER_PROFILEBOX (user_data);
	xfce_mixer_profilebox_profile_insert_cb (pb);
}

static void profile_delete_cb (GtkWidget *w, gpointer user_data)
{
	XfceMixerProfilebox *pb;
	pb = XFCE_MIXER_PROFILEBOX (user_data);
	xfce_mixer_profilebox_profile_delete_cb (pb);
}


#line 931 "xfce-mixer-profilebox.c"
