/* Generated by GOB (v2.0.6) on Wed Feb 11 19:24:33 2004
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 6

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "xfce-mixer-window.h"

#include "xfce-mixer-window-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-window.gob"

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#line 33 "xfce-mixer-window.c"

#line 7 "mixer-window.gob"

#include <gtk/gtk.h>
#include "xfce-mixer-view.h"
#include "xfce-mixer-profile.h"
#include "main.h"
#include "xfce-mixer-mcs-client.h"

#line 43 "xfce-mixer-window.c"

#line 14 "mixer-window.gob"

#include <gtk/gtk.h>
#include <libxfce4util/i18n.h>
#include <libxfce4util/util.h>
#include "menus.h"
#include "main.h"
#include "stringlist.inc"
#define CHANNEL "sound"
#define MIXER_ROOT "Mixer"


#line 57 "xfce-mixer-window.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_WINDOW(x)
#define SELF_CONST(x) XFCE_MIXER_WINDOW_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_WINDOW(x)
#define TYPE_SELF XFCE_TYPE_MIXER_WINDOW
#define SELF_CLASS(x) XFCE_MIXER_WINDOW_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_WINDOW_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerWindow Self;
typedef XfceMixerWindowClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_window_class_init (XfceMixerWindowClass * c) G_GNUC_UNUSED;
static void xfce_mixer_window_init (XfceMixerWindow * self) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static GtkWindowClass *parent_class = NULL;

/* Short form macros */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define self_set_profile(args...) xfce_mixer_window_set_profile(args)
#define self_xml_goto_device(args...) xfce_mixer_window_xml_goto_device(args)
#define self_load_window_state(args...) xfce_mixer_window_load_window_state(args)
#define self_save_window_state(args...) xfce_mixer_window_save_window_state(args)
#define self_destroy_cb(args...) xfce_mixer_window_destroy_cb(args)
#define self_mcs_changed_cb(args...) xfce_mixer_window_mcs_changed_cb(args)
#define self_profiles_changed_cb(args...) xfce_mixer_window_profiles_changed_cb(args)
#define self_view_profile_activate_cb(args...) xfce_mixer_window_view_profile_activate_cb(args)
#define self_update_profiles_menu(args...) xfce_mixer_window_update_profiles_menu(args)
#define self_new() xfce_mixer_window_new()
#define self_refresh(args...) xfce_mixer_window_refresh(args)
#define self_reset_profile(args...) xfce_mixer_window_reset_profile(args)
#define self_refresh_value(args...) xfce_mixer_window_refresh_value(args)
#endif /* __GNUC__ && !__STRICT_ANSI__ */

/* Short form pointers */
static void (* const self_set_profile) (XfceMixerWindow * self, XfceMixerProfile * p) = xfce_mixer_window_set_profile;
static void (* const self_xml_goto_device) (XfceMixerWindow * self, XfceMixerPxml * xml) = xfce_mixer_window_xml_goto_device;
static void (* const self_load_window_state) (XfceMixerWindow * self) = xfce_mixer_window_load_window_state;
static void (* const self_save_window_state) (XfceMixerWindow * self) = xfce_mixer_window_save_window_state;
static void (* const self_destroy_cb) (XfceMixerWindow * self, GtkWidget * widget) = xfce_mixer_window_destroy_cb;
static void (* const self_mcs_changed_cb) (XfceMixerWindow * self, GtkWidget * widget) = xfce_mixer_window_mcs_changed_cb;
static void (* const self_profiles_changed_cb) (XfceMixerWindow * self, GObject * profiles) = xfce_mixer_window_profiles_changed_cb;
static void (* const self_view_profile_activate_cb) (XfceMixerWindow * self, GtkWidget * w) = xfce_mixer_window_view_profile_activate_cb;
static void (* const self_update_profiles_menu) (XfceMixerWindow * self) = xfce_mixer_window_update_profiles_menu;
static GtkWidget * (* const self_new) (void) = xfce_mixer_window_new;
static void (* const self_refresh) (XfceMixerWindow * self) = xfce_mixer_window_refresh;
static void (* const self_reset_profile) (XfceMixerWindow * self) = xfce_mixer_window_reset_profile;
static void (* const self_refresh_value) (XfceMixerWindow * self, gchar const * vcname) = xfce_mixer_window_refresh_value;

GType
xfce_mixer_window_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerWindowClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_window_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerWindow),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_window_init,
		};

		type = g_type_register_static (GTK_TYPE_WINDOW, "XfceMixerWindow", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerWindow *)g_object_new(xfce_mixer_window_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerWindow * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerWindow *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerWindow *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerWindow *)g_object_new_valist (xfce_mixer_window_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___dispose (GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::dispose"
	XfceMixerWindow *self = XFCE_MIXER_WINDOW (obj_self);
	if (G_OBJECT_CLASS (parent_class)->dispose) \
		(* G_OBJECT_CLASS (parent_class)->dispose) (obj_self);
#line 32 "mixer-window.gob"
	if(self->profile) { ((*(void (*)(void *))g_object_unref)) (self->profile); self->profile = NULL; }
#line 161 "xfce-mixer-window.c"
#line 35 "mixer-window.gob"
	if(self->mcsc) { ((*(void (*)(void *))g_object_unref)) (self->mcsc); self->mcsc = NULL; }
#line 164 "xfce-mixer-window.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::finalize"
	XfceMixerWindow *self = XFCE_MIXER_WINDOW (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#line 38 "mixer-window.gob"
	if(self->fname) { ((*(void (*)(void *))g_free)) (self->fname); self->fname = NULL; }
#line 180 "xfce-mixer-window.c"
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__

static void 
xfce_mixer_window_class_init (XfceMixerWindowClass * c)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::class_init"
	GObjectClass *g_object_class = (GObjectClass*) c;

	parent_class = g_type_class_ref (GTK_TYPE_WINDOW);

	g_object_class->dispose = ___dispose;
	g_object_class->finalize = ___finalize;
	return;
	c = NULL;
	g_object_class = NULL;
}
#undef __GOB_FUNCTION__
#line 52 "mixer-window.gob"
static void 
xfce_mixer_window_init (XfceMixerWindow * self)
#line 204 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::init"
#line 14 "mixer-window.gob"
	self->view = NULL;
#line 209 "xfce-mixer-window.c"
#line 14 "mixer-window.gob"
	self->box = NULL;
#line 212 "xfce-mixer-window.c"
#line 14 "mixer-window.gob"
	self->menubar = NULL;
#line 215 "xfce-mixer-window.c"
#line 14 "mixer-window.gob"
	self->profile = NULL;
#line 218 "xfce-mixer-window.c"
#line 14 "mixer-window.gob"
	self->accelgroup = NULL;
#line 221 "xfce-mixer-window.c"
#line 14 "mixer-window.gob"
	self->mcsc = NULL;
#line 224 "xfce-mixer-window.c"
#line 14 "mixer-window.gob"
	self->fname = NULL;
#line 227 "xfce-mixer-window.c"
 {
#line 53 "mixer-window.gob"

		XfceMixerProfile *p;
		self->box = GTK_BOX (gtk_vbox_new (FALSE, 0));
		gtk_widget_show (GTK_WIDGET (self->box));

		self->accelgroup = GTK_ACCEL_GROUP (gtk_accel_group_new ());
		self->menubar = xfce_mixer_create_main_menu (
			GTK_WINDOW (self), self->accelgroup
		);

		gtk_window_add_accel_group (GTK_WINDOW (self), self->accelgroup);

		g_object_unref (G_OBJECT (self->accelgroup));

		/*self->menubar = GTK_MENU_BAR (gtk_menu_bar_new ());*/
		gtk_widget_show (GTK_WIDGET (self->menubar));

		gtk_box_pack_start (self->box, GTK_WIDGET (self->menubar), FALSE, FALSE, 0);



		self->view = xfce_mixer_view_new ();

		gtk_widget_set_size_request (GTK_WIDGET (self->view), 600, -1);

		p = XFCE_MIXER_PROFILE (xfce_mixer_profile_new ("noname"));
		self_set_profile (self, p);
		g_object_unref (G_OBJECT (p));

		/*g_object_unref (G_OBJECT (self->profile));*/

		g_signal_connect_swapped (G_OBJECT (profiles),
			"profiles-changed", 
			G_CALLBACK (self_profiles_changed_cb),
			self);


		gtk_widget_show (GTK_WIDGET (self->view));

		gtk_box_pack_start (self->box, GTK_WIDGET (self->view), TRUE, TRUE, 0);

		gtk_container_add (GTK_CONTAINER (self), GTK_WIDGET (self->box));

		gtk_window_set_title (GTK_WINDOW (self), _("Volume Control"));

		self->mcsc = xfce_mixer_mcs_client_new ();
		g_object_set (self->mcsc, "channel", CHANNEL, NULL);
		g_signal_connect_swapped (G_OBJECT (self->mcsc), "changed", 
			G_CALLBACK(self_mcs_changed_cb), self);

		self_update_profiles_menu (self);

		g_signal_connect_swapped (G_OBJECT (self), "destroy",
			G_CALLBACK(self_destroy_cb), self);

		self->fname = xfce_get_userfile ("xfce4-mixer", "config.xml", NULL);
		self_load_window_state (self);
	
#line 288 "xfce-mixer-window.c"
 }
	return;
	self = NULL;
}
#undef __GOB_FUNCTION__


#line 40 "mixer-window.gob"
void 
xfce_mixer_window_set_profile (XfceMixerWindow * self, XfceMixerProfile * p)
#line 299 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::set_profile"
#line 40 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 40 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 306 "xfce-mixer-window.c"
{
#line 41 "mixer-window.gob"
	
		if (p)
			g_object_ref (p);

		if (self->profile)
			g_object_unref (self->profile);

		self->profile = p;
		xfce_mixer_view_set_profile (self->view, p);
	}}
#line 319 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__


#line 114 "mixer-window.gob"
void 
xfce_mixer_window_xml_goto_device (XfceMixerWindow * self, XfceMixerPxml * xml)
#line 326 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::xml_goto_device"
#line 114 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 114 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 333 "xfce-mixer-window.c"
{
#line 115 "mixer-window.gob"
	
		gchar *n;
		xfce_mixer_pxml_goto_root (xml);
		xfce_mixer_pxml_goto_children (xml);
		while (xml->node) {
			if (xfce_mixer_pxml_check_tag (xml, "device")) {
				n = xfce_mixer_pxml_get_prop (xml, "name");
				if (n && device && g_str_equal (n, device)) {
					g_free (n);
					return;
				}
				if (n)
					g_free (n);
			}

			xfce_mixer_pxml_goto_next (xml);
		}

		/* device does not exist yet in xml */
		xml->node = NULL;
		xfce_mixer_pxml_goto_root (xml);
		xml->node = xfce_mixer_pxml_create_text_child (xml, "device", NULL);
		xfce_mixer_pxml_set_prop (xml, "name", device);
	}}
#line 360 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 140 "mixer-window.gob"
void 
xfce_mixer_window_load_window_state (XfceMixerWindow * self)
#line 366 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::load_window_state"
#line 140 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 140 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 373 "xfce-mixer-window.c"
{
#line 141 "mixer-window.gob"
	
		XfceMixerPxml *xml;
		gint x, y;
		gint width, height;

		xml = xfce_mixer_pxml_new (MIXER_ROOT);
		g_object_set (G_OBJECT (xml), "fname", self->fname, NULL);

		self_xml_goto_device (self, xml);
		if (xfce_mixer_pxml_goto_child_tag (xml, "position")) {
			if (xfce_mixer_pxml_get_prop_int (xml, "width", &width)
			&& xfce_mixer_pxml_get_prop_int (xml, "height", &height)) {
				gtk_widget_set_size_request (GTK_WIDGET (self), width, height);
			}
		}

		self_xml_goto_device (self, xml);
		if (xfce_mixer_pxml_goto_child_tag (xml, "size")) {
			if (xfce_mixer_pxml_get_prop_int (xml, "x", &x) 
			&& xfce_mixer_pxml_get_prop_int (xml, "y", &y)) {
				gtk_window_move (GTK_WINDOW (self), x, y);
			}
		}

		g_object_unref (G_OBJECT (xml));
	}}
#line 402 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 168 "mixer-window.gob"
void 
xfce_mixer_window_save_window_state (XfceMixerWindow * self)
#line 408 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::save_window_state"
#line 168 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 168 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 415 "xfce-mixer-window.c"
{
#line 169 "mixer-window.gob"
	
		XfceMixerPxml *xml;
		GtkRequisition req;
		gint x, y;

		xml = xfce_mixer_pxml_new (MIXER_ROOT);
		g_object_set (G_OBJECT (xml), "fname", self->fname, NULL);

		gtk_widget_size_request (GTK_WIDGET (self), &req);
		gtk_window_get_position (GTK_WINDOW (self), &x, &y);

		g_warning ("save pos %d %d, size %d %d", x, y, req.width, req.height);

		self_xml_goto_device (self, xml);

		if (!xfce_mixer_pxml_goto_child_tag (xml, "position")) 
			xfce_mixer_pxml_goto_node (xml, 
				xfce_mixer_pxml_create_text_child (xml, "position", NULL)
			);

		xfce_mixer_pxml_set_prop_int (xml, "x", x);
		xfce_mixer_pxml_set_prop_int (xml, "y", y);

		self_xml_goto_device (self, xml);
		if (!xfce_mixer_pxml_goto_child_tag (xml, "size"))
			xfce_mixer_pxml_goto_node (xml, 
				xfce_mixer_pxml_create_text_child (xml, "size", NULL)
			);
		xfce_mixer_pxml_set_prop_int (xml, "width", req.width);
		xfce_mixer_pxml_set_prop_int (xml, "height", req.height);

		/*xfce_mixer_pxml_set_file (xml, NULL);*/

		g_object_unref (G_OBJECT (xml));
	}}
#line 453 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 205 "mixer-window.gob"
void 
xfce_mixer_window_destroy_cb (XfceMixerWindow * self, GtkWidget * widget)
#line 459 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::destroy_cb"
#line 205 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 205 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 466 "xfce-mixer-window.c"
{
#line 206 "mixer-window.gob"
	
		self_save_window_state(self);
	}}
#line 472 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 210 "mixer-window.gob"
void 
xfce_mixer_window_mcs_changed_cb (XfceMixerWindow * self, GtkWidget * widget)
#line 478 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::mcs_changed_cb"
#line 210 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 210 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 485 "xfce-mixer-window.c"
{
#line 211 "mixer-window.gob"
	
		/*g_warning ("mcs changed");*/
		self_reset_profile (self);
	}}
#line 492 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 216 "mixer-window.gob"
void 
xfce_mixer_window_profiles_changed_cb (XfceMixerWindow * self, GObject * profiles)
#line 498 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::profiles_changed_cb"
#line 216 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 216 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 505 "xfce-mixer-window.c"
{
#line 217 "mixer-window.gob"
	
		/* TODO avoid loop? */
		if (!self->view || !self->menubar)
			return;

		self_update_profiles_menu (self);
	}}
#line 515 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 225 "mixer-window.gob"
void 
xfce_mixer_window_view_profile_activate_cb (XfceMixerWindow * self, GtkWidget * w)
#line 521 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::view_profile_activate_cb"
#line 225 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 225 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 528 "xfce-mixer-window.c"
{
#line 226 "mixer-window.gob"
	
		GList *g, *gp;
		gchar const *n;
		XfceMixerProfile *p;

		if (!gtk_check_menu_item_get_active (
			GTK_CHECK_MENU_ITEM (w)
		))
			return;

		g = gtk_container_get_children (GTK_CONTAINER (w));
		gp = g;
		n = NULL;
		if (gp)
			n = gtk_label_get_text (GTK_LABEL (gp->data));

		if (!n) {
			g_list_free (g);
			return;
		}

		p = xfce_mixer_profiles_get_profile (profiles, n);
		if (p) {
			/*g_warning ("profile_activate_cb init %X", (int)p);
			g_warning ("profile name %s", xfce_mixer_profile_get_title (p));*/
			self_set_profile (self, p);
			/*self_reset_profile (self);TODO remove this*/
			g_object_unref (G_OBJECT (p));
			/*g_warning ("profile_activate_cb done");*/
		}

		if (g)
			g_list_free (g);
	}}
#line 565 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 261 "mixer-window.gob"
void 
xfce_mixer_window_update_profiles_menu (XfceMixerWindow * self)
#line 571 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::update_profiles_menu"
#line 261 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 261 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 578 "xfce-mixer-window.c"
{
#line 262 "mixer-window.gob"
	
		XfceMixerProfile const *currentp;
		GtkContainer *container;
		GList *g, *gp;
		GtkWidget *mi;
		gchar const *currentpn;
		gchar const *n;
		GSList *group;
		currentpn = NULL;
		currentp = xfce_mixer_view_get_profile (self->view);
		if (currentp)
			currentpn = xfce_mixer_profile_get_title ((XfceMixerProfile *)currentp);

		/* self->menubar, View menu: */
		/* for each v.child(): */
		/*   if child == seperator: break */
		/*   child.destroy() */

		container = GTK_CONTAINER (self->menubar);
		if (!container)
			return;

		g = gtk_container_get_children (container);
		if (!g)
			return;

		mi = GTK_WIDGET (g_list_nth_data (g, 1));
		if (!mi) {
			g_list_free (g);
			return;
		}

		container = GTK_CONTAINER (gtk_menu_item_get_submenu (GTK_MENU_ITEM (mi)));

		g_list_free (g);

		if (!container)
			return;

		g = gtk_container_get_children (container);
		if (!g)
			return;
		gp = g;
		while (gp) {
			if (!GTK_IS_RADIO_MENU_ITEM (gp->data))
				break;

			gtk_widget_destroy (GTK_WIDGET (gp->data));
			gp = g_list_next (gp);
		}

		if (g)
			g_list_free (g);


		/* profiles.load() */
		/* for n in profiles.get_profile_names() */
		/*   v.insert(0, gtk.MenuItem(n).show()) */

		g = xfce_mixer_profiles_get_profile_names (profiles);

		/*g = g_list_append (g, g_strdup ("dummy"));*/
		/*g = g_list_append (g, g_strdup ("dummy2"));*/

		gp = g;
		group = NULL;
		while (gp) {
			n = (gchar const *)gp->data;
			mi = gtk_radio_menu_item_new_with_label (group, n);

			group = gtk_radio_menu_item_get_group (GTK_RADIO_MENU_ITEM (mi));

			g_signal_connect_swapped (G_OBJECT (mi),
				"activate", G_CALLBACK (self_view_profile_activate_cb),
				self);

			if (currentpn && g_str_equal (currentpn, n)) {
				gtk_check_menu_item_set_active (GTK_CHECK_MENU_ITEM (mi), TRUE);
			}

			/* make mi checkmenuitems */
			gtk_widget_show (GTK_WIDGET (mi));
			gtk_menu_shell_prepend (GTK_MENU_SHELL (container), mi);

			gp = g_list_next (gp);
		}
		if (g)
			stringlist_free (g);

	}}
#line 671 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 353 "mixer-window.gob"
GtkWidget * 
xfce_mixer_window_new (void)
#line 677 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::new"
{
#line 354 "mixer-window.gob"
	
		return GTK_WIDGET (GET_NEW);
	}}
#line 685 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 358 "mixer-window.gob"
void 
xfce_mixer_window_refresh (XfceMixerWindow * self)
#line 691 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::refresh"
#line 358 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 358 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 698 "xfce-mixer-window.c"
{
#line 359 "mixer-window.gob"
	
		if (self->profile)
			xfce_mixer_profile_refresh_views (self->profile);
	}}
#line 705 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 364 "mixer-window.gob"
void 
xfce_mixer_window_reset_profile (XfceMixerWindow * self)
#line 711 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::reset_profile"
#line 364 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 364 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 718 "xfce-mixer-window.c"
{
#line 365 "mixer-window.gob"
	
		if (self->view)
			xfce_mixer_view_set_profile (self->view, self->profile);

		/*
		if (self->profile)
			xfce_mixer_profile_refresh_views (self->profile);

		automatic.
		*/
	}}
#line 732 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__

#line 377 "mixer-window.gob"
void 
xfce_mixer_window_refresh_value (XfceMixerWindow * self, gchar const * vcname)
#line 738 "xfce-mixer-window.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Window::refresh_value"
#line 377 "mixer-window.gob"
	g_return_if_fail (self != NULL);
#line 377 "mixer-window.gob"
	g_return_if_fail (XFCE_IS_MIXER_WINDOW (self));
#line 745 "xfce-mixer-window.c"
{
#line 378 "mixer-window.gob"
	
		if (self->view)
			xfce_mixer_view_refresh_value (self->view, vcname);
	}}
#line 752 "xfce-mixer-window.c"
#undef __GOB_FUNCTION__


#if (!defined __GNUC__) || (defined __GNUC__ && defined __STRICT_ANSI__)
/*REALLY BAD HACK
  This is to avoid unused warnings if you don't call
  some method.  I need to find a better way to do
  this, not needed in GCC since we use some gcc
  extentions to make saner, faster code */
static void
___xfce_mixer_window_really_bad_hack_to_avoid_warnings(void)
{
	((void (*)(void))GET_NEW_VARG)();
	((void (*)(void))self_set_profile)();
	((void (*)(void))self_xml_goto_device)();
	((void (*)(void))self_load_window_state)();
	((void (*)(void))self_save_window_state)();
	((void (*)(void))self_destroy_cb)();
	((void (*)(void))self_mcs_changed_cb)();
	((void (*)(void))self_profiles_changed_cb)();
	((void (*)(void))self_view_profile_activate_cb)();
	((void (*)(void))self_update_profiles_menu)();
	((void (*)(void))self_new)();
	((void (*)(void))self_refresh)();
	((void (*)(void))self_reset_profile)();
	((void (*)(void))self_refresh_value)();
	___xfce_mixer_window_really_bad_hack_to_avoid_warnings();
}
#endif /* !__GNUC__ || (__GNUC__ && __STRICT_ANSI__) */

