/* Generated by GOB (v2.0.14)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 14

#define selfp (self->_priv)

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <string.h> /* memset() */

#include "xfce-mixer-pxml.h"

#include "xfce-mixer-pxml-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-pxml.gob"

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif
#include <stdio.h>
#ifdef HAVE_STDLIB_H
#include <stdlib.h>
#endif
/* <benny> freebsd needs sys/types.h prior to sys/stat.h */ 
#ifdef HAVE_SYS_TYPES_H
#include <sys/types.h>
#endif
#ifdef HAVE_SYS_STAT_H
#include <sys/stat.h>
#endif


#line 47 "xfce-mixer-pxml.c"

#line 18 "mixer-pxml.gob"


#include <gtk/gtk.h>
#include <libxml/parser.h>
#include <libxml/tree.h>


#line 57 "xfce-mixer-pxml.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_PXML(x)
#define SELF_CONST(x) XFCE_MIXER_PXML_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_PXML(x)
#define TYPE_SELF XFCE_TYPE_MIXER_PXML
#define SELF_CLASS(x) XFCE_MIXER_PXML_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_PXML_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerPxml Self;
typedef XfceMixerPxmlClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void xfce_mixer_pxml_class_init (XfceMixerPxmlClass * c) G_GNUC_UNUSED;
static void xfce_mixer_pxml_init (XfceMixerPxml * self) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_FNAME
};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_set_document xfce_mixer_pxml_set_document
#define self_free_document xfce_mixer_pxml_free_document
#define self_set_file xfce_mixer_pxml_set_file
#define self_eat_children xfce_mixer_pxml_eat_children
#define self_goto_next xfce_mixer_pxml_goto_next
#define self_check_tag xfce_mixer_pxml_check_tag
#define self_goto_child_tag xfce_mixer_pxml_goto_child_tag
#define self_has_parent xfce_mixer_pxml_has_parent
#define self_goto_parent xfce_mixer_pxml_goto_parent
#define self_goto_children xfce_mixer_pxml_goto_children
#define self_goto_root xfce_mixer_pxml_goto_root
#define self_goto_node xfce_mixer_pxml_goto_node
#define self_has_children xfce_mixer_pxml_has_children
#define self_get_prop xfce_mixer_pxml_get_prop
#define self_get_prop_int xfce_mixer_pxml_get_prop_int
#define self_set_prop_int xfce_mixer_pxml_set_prop_int
#define self_set_prop xfce_mixer_pxml_set_prop
#define self_create_text_child xfce_mixer_pxml_create_text_child
#define self_new xfce_mixer_pxml_new
#define self_get_text_child xfce_mixer_pxml_get_text_child
GType
xfce_mixer_pxml_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerPxmlClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_pxml_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerPxml),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_pxml_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "XfceMixerPxml", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerPxml *)g_object_new(xfce_mixer_pxml_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerPxml * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerPxml *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerPxml *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerPxml *)g_object_new_valist (xfce_mixer_pxml_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::finalize"
	XfceMixerPxml *self G_GNUC_UNUSED = XFCE_MIXER_PXML (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#define root (self->root)
#define VAR root
	{
#line 28 "mixer-pxml.gob"
	
			if (VAR) {
				g_free (VAR);
				VAR = NULL;
			}
		}
#line 166 "xfce-mixer-pxml.c"
	memset(&root, 0, sizeof(root));
#undef VAR
#undef root
#define fname (self->fname)
#define VAR fname
	{
#line 38 "mixer-pxml.gob"
	
			self_set_file (self, NULL);
		}
#line 177 "xfce-mixer-pxml.c"
	memset(&fname, 0, sizeof(fname));
#undef VAR
#undef fname
#define document (self->document)
#define VAR document
	{
#line 44 "mixer-pxml.gob"
	
			self_free_document (self);
		}
#line 188 "xfce-mixer-pxml.c"
	memset(&document, 0, sizeof(document));
#undef VAR
#undef document
}
#undef __GOB_FUNCTION__

static void 
xfce_mixer_pxml_class_init (XfceMixerPxmlClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("fname" /* name */,
		 "File name and path" /* nick */,
		 "Filename and path to use, if any" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_FNAME,
		param_spec);
    }
}
#undef __GOB_FUNCTION__
#line 131 "mixer-pxml.gob"
static void 
xfce_mixer_pxml_init (XfceMixerPxml * self G_GNUC_UNUSED)
#line 224 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::init"
#line 18 "mixer-pxml.gob"
	self->root = NULL;
#line 229 "xfce-mixer-pxml.c"
#line 28 "mixer-pxml.gob"
	self->foreignDoc = TRUE;
#line 232 "xfce-mixer-pxml.c"
#line 28 "mixer-pxml.gob"
	self->fname = NULL;
#line 235 "xfce-mixer-pxml.c"
#line 38 "mixer-pxml.gob"
	self->document = NULL;
#line 238 "xfce-mixer-pxml.c"
#line 55 "mixer-pxml.gob"
	self->node = NULL;
#line 241 "xfce-mixer-pxml.c"
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::set_property"
{
	XfceMixerPxml *self G_GNUC_UNUSED;

	self = XFCE_MIXER_PXML (object);

	switch (property_id) {
	case PROP_FNAME:
		{
#line 55 "mixer-pxml.gob"

		self_set_file (self, g_value_get_string (VAL));
	
#line 263 "xfce-mixer-pxml.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::get_property"
{
	XfceMixerPxml *self G_GNUC_UNUSED;

	self = XFCE_MIXER_PXML (object);

	switch (property_id) {
	case PROP_FNAME:
		{
#line 52 "mixer-pxml.gob"

		g_value_set_string (VAL, self->fname);
	
#line 296 "xfce-mixer-pxml.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__


#line 61 "mixer-pxml.gob"
void 
xfce_mixer_pxml_set_document (XfceMixerPxml * self, xmlDocPtr doc)
#line 315 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::set_document"
#line 61 "mixer-pxml.gob"
	g_return_if_fail (self != NULL);
#line 61 "mixer-pxml.gob"
	g_return_if_fail (XFCE_IS_MIXER_PXML (self));
#line 322 "xfce-mixer-pxml.c"
{
#line 62 "mixer-pxml.gob"
	
		self->foreignDoc = TRUE;
		self->document = doc;
	}}
#line 329 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 67 "mixer-pxml.gob"
void 
xfce_mixer_pxml_free_document (XfceMixerPxml * self)
#line 335 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::free_document"
#line 67 "mixer-pxml.gob"
	g_return_if_fail (self != NULL);
#line 67 "mixer-pxml.gob"
	g_return_if_fail (XFCE_IS_MIXER_PXML (self));
#line 342 "xfce-mixer-pxml.c"
{
#line 68 "mixer-pxml.gob"
	
		if (!self->foreignDoc && self->document) {
			xmlFreeDoc (self->document);
		}
		self->document = NULL;
	}}
#line 351 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 75 "mixer-pxml.gob"
void 
xfce_mixer_pxml_set_file (XfceMixerPxml * self, gchar const * fnamen)
#line 357 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::set_file"
#line 75 "mixer-pxml.gob"
	g_return_if_fail (self != NULL);
#line 75 "mixer-pxml.gob"
	g_return_if_fail (XFCE_IS_MIXER_PXML (self));
#line 364 "xfce-mixer-pxml.c"
{
#line 76 "mixer-pxml.gob"
	
		gchar *dir;
		self->node = NULL;

		if (self->fname && self->document) {
			/* store blahblah if required */
			xmlSaveFormatFile (self->fname, self->document, 1);
			xmlFreeDoc (self->document);
			self->document = NULL;

			g_free (self->fname);
			self->fname = NULL;
		}

		if (fnamen) {
			self->fname = g_strdup (fnamen);
			if (!self->fname) {
				/* eeek TODO exception */
			}

			if (g_file_test (self->fname, G_FILE_TEST_EXISTS)) {
				/* TODO backup */
				self->document = xmlParseFile (self->fname);
				self->foreignDoc = FALSE;
			} else {
				/* create directory */
				dir = g_path_get_dirname (self->fname);
				if (dir && !g_file_test (dir, G_FILE_TEST_IS_DIR))
					mkdir (dir, S_IRWXU | S_IRGRP 
					| S_IXGRP | S_IROTH | S_IXOTH);

				if (dir)
					g_free (dir);
			}

			/* create document etc */

			if (!self->document && self->root) {
				self->document = xmlNewDoc ("1.0");
				self->document->children = xmlNewDocRawNode (self->document, NULL, self->root, NULL);
				self->foreignDoc = FALSE;
				xmlDocSetRootElement (self->document, self->document->children);
			}

			if (!self->document)
				return;

			self_goto_root (self);
			if (!self->node) { /* no root */
				xmlFreeDoc (self->document);
				self->document = NULL;
			}
		}
	}}
#line 421 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__


#line 135 "mixer-pxml.gob"
void 
xfce_mixer_pxml_eat_children (XfceMixerPxml * self, GList * exceptions)
#line 428 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::eat_children"
#line 135 "mixer-pxml.gob"
	g_return_if_fail (self != NULL);
#line 135 "mixer-pxml.gob"
	g_return_if_fail (XFCE_IS_MIXER_PXML (self));
#line 435 "xfce-mixer-pxml.c"
{
#line 136 "mixer-pxml.gob"
	
		xmlNodePtr nodex;
		xmlNodePtr nnodex;
		GList *g;
		gchar *tagname;
		gboolean found;
		/* todo */
		if (!self->node)
			return;

		nodex = self->node->children;
		if (!nodex)
			return;

		while (nodex) {
			nnodex = nodex->next;

			/* if not nodex.tagname in exceptions:
				nodex.del()
			*/
			tagname = (gchar *)nodex->name;
			found = FALSE;
			g = exceptions;
			while (g) {
				if (g_str_equal ((gchar *)g->data, tagname)) {
					found = TRUE;
					break;
				}
				g = g_list_next (g);
			}

			if (!found) {
				/* delete node */
				xmlUnlinkNode (nodex);
				xmlFreeNode (nodex);
			}

			nodex = nnodex;
		}
	}}
#line 478 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 177 "mixer-pxml.gob"
gboolean 
xfce_mixer_pxml_goto_next (XfceMixerPxml * self)
#line 484 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::goto_next"
#line 177 "mixer-pxml.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 177 "mixer-pxml.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PXML (self), (gboolean )0);
#line 491 "xfce-mixer-pxml.c"
{
#line 178 "mixer-pxml.gob"
	
		if (!self->node)
			return FALSE;

		self->node = self->node->next;
		if (self->node)
			return TRUE;

		return FALSE;
	}}
#line 504 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 189 "mixer-pxml.gob"
gboolean 
xfce_mixer_pxml_check_tag (XfceMixerPxml * self, gchar const * tagname)
#line 510 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::check_tag"
#line 189 "mixer-pxml.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 189 "mixer-pxml.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PXML (self), (gboolean )0);
#line 517 "xfce-mixer-pxml.c"
{
#line 190 "mixer-pxml.gob"
	
		if (!self->node)
			return FALSE;

		return (xmlStrEqual(self->node->name, (const xmlChar *)tagname));
	}}
#line 526 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 197 "mixer-pxml.gob"
gboolean 
xfce_mixer_pxml_goto_child_tag (XfceMixerPxml * self, gchar const * tagname)
#line 532 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::goto_child_tag"
#line 197 "mixer-pxml.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 197 "mixer-pxml.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PXML (self), (gboolean )0);
#line 539 "xfce-mixer-pxml.c"
{
#line 198 "mixer-pxml.gob"
	
		xmlNodePtr nodex;
		if (!self->node)
			return FALSE;

		nodex = self->node->children;
		while (nodex) {
			if (xmlStrEqual(nodex->name, (const xmlChar *)tagname)) {
				self->node = nodex;
				return TRUE;
			}
			nodex = nodex->next;
		}

		return FALSE;
	}}
#line 558 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 215 "mixer-pxml.gob"
gboolean 
xfce_mixer_pxml_has_parent (XfceMixerPxml * self)
#line 564 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::has_parent"
#line 215 "mixer-pxml.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 215 "mixer-pxml.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PXML (self), (gboolean )0);
#line 571 "xfce-mixer-pxml.c"
{
#line 216 "mixer-pxml.gob"
	
		if (!self->node)
			return FALSE;

		return (self->node->parent != NULL);
	}}
#line 580 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 223 "mixer-pxml.gob"
void 
xfce_mixer_pxml_goto_parent (XfceMixerPxml * self)
#line 586 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::goto_parent"
#line 223 "mixer-pxml.gob"
	g_return_if_fail (self != NULL);
#line 223 "mixer-pxml.gob"
	g_return_if_fail (XFCE_IS_MIXER_PXML (self));
#line 593 "xfce-mixer-pxml.c"
{
#line 224 "mixer-pxml.gob"
	
		if (!self->node)
			return;

		self->node = self->node->parent;
	}}
#line 602 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 231 "mixer-pxml.gob"
void 
xfce_mixer_pxml_goto_children (XfceMixerPxml * self)
#line 608 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::goto_children"
#line 231 "mixer-pxml.gob"
	g_return_if_fail (self != NULL);
#line 231 "mixer-pxml.gob"
	g_return_if_fail (XFCE_IS_MIXER_PXML (self));
#line 615 "xfce-mixer-pxml.c"
{
#line 232 "mixer-pxml.gob"
	
		if (!self->node)
			return;

		self->node = self->node->children;
	}}
#line 624 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 239 "mixer-pxml.gob"
void 
xfce_mixer_pxml_goto_root (XfceMixerPxml * self)
#line 630 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::goto_root"
#line 239 "mixer-pxml.gob"
	g_return_if_fail (self != NULL);
#line 239 "mixer-pxml.gob"
	g_return_if_fail (XFCE_IS_MIXER_PXML (self));
#line 637 "xfce-mixer-pxml.c"
{
#line 240 "mixer-pxml.gob"
	
		if (!self->document)
			return;

		self->node = xmlDocGetRootElement (self->document);

		if (self->root && !self_check_tag (self, self->root)) {
			self->node = NULL;
		}
	}}
#line 650 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 251 "mixer-pxml.gob"
void 
xfce_mixer_pxml_goto_node (XfceMixerPxml * self, xmlNodePtr nn)
#line 656 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::goto_node"
#line 251 "mixer-pxml.gob"
	g_return_if_fail (self != NULL);
#line 251 "mixer-pxml.gob"
	g_return_if_fail (XFCE_IS_MIXER_PXML (self));
#line 663 "xfce-mixer-pxml.c"
{
#line 252 "mixer-pxml.gob"
	
		self->node = nn;
	}}
#line 669 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 256 "mixer-pxml.gob"
gboolean 
xfce_mixer_pxml_has_children (XfceMixerPxml * self)
#line 675 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::has_children"
#line 256 "mixer-pxml.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 256 "mixer-pxml.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PXML (self), (gboolean )0);
#line 682 "xfce-mixer-pxml.c"
{
#line 257 "mixer-pxml.gob"
	
		if (!self->node)
			return FALSE;

		return (self->node->children != NULL);
	}}
#line 691 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 264 "mixer-pxml.gob"
gchar * 
xfce_mixer_pxml_get_prop (XfceMixerPxml * self, gchar const * pname)
#line 697 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::get_prop"
#line 264 "mixer-pxml.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 264 "mixer-pxml.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PXML (self), (gchar * )0);
#line 704 "xfce-mixer-pxml.c"
{
#line 265 "mixer-pxml.gob"
	
		return xmlGetProp (self->node, pname);
	}}
#line 710 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 269 "mixer-pxml.gob"
gboolean 
xfce_mixer_pxml_get_prop_int (XfceMixerPxml * self, gchar const * pname, gint * result)
#line 716 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::get_prop_int"
#line 269 "mixer-pxml.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 269 "mixer-pxml.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PXML (self), (gboolean )0);
#line 723 "xfce-mixer-pxml.c"
{
#line 270 "mixer-pxml.gob"
	
		gchar *s;
		gchar *endptr;
		gboolean b;
		s = self_get_prop (self, pname);
		if (!s)
			return FALSE;

		b = FALSE;
		endptr = NULL;
		*result = (gint)strtol (s, &endptr, 0);
		b = (endptr == NULL) || ((*endptr) == 0);

		g_free (s);
		return b;
	}}
#line 742 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 287 "mixer-pxml.gob"
void 
xfce_mixer_pxml_set_prop_int (XfceMixerPxml * self, gchar const * pname, gint v)
#line 748 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::set_prop_int"
#line 287 "mixer-pxml.gob"
	g_return_if_fail (self != NULL);
#line 287 "mixer-pxml.gob"
	g_return_if_fail (XFCE_IS_MIXER_PXML (self));
#line 755 "xfce-mixer-pxml.c"
{
#line 288 "mixer-pxml.gob"
	
		gchar tmp[20];
		g_snprintf (tmp, 20, "%d", v);
		self_set_prop (self, pname, tmp);
	}}
#line 763 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 294 "mixer-pxml.gob"
void 
xfce_mixer_pxml_set_prop (XfceMixerPxml * self, gchar const * pname, gchar const * value)
#line 769 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::set_prop"
#line 294 "mixer-pxml.gob"
	g_return_if_fail (self != NULL);
#line 294 "mixer-pxml.gob"
	g_return_if_fail (XFCE_IS_MIXER_PXML (self));
#line 776 "xfce-mixer-pxml.c"
{
#line 295 "mixer-pxml.gob"
	
		xmlSetProp (self->node, pname, (const xmlChar *) value);
	}}
#line 782 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 299 "mixer-pxml.gob"
xmlNodePtr 
xfce_mixer_pxml_create_text_child (XfceMixerPxml * self, gchar const * name, gchar const * opt_text)
#line 788 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::create_text_child"
#line 299 "mixer-pxml.gob"
	g_return_val_if_fail (self != NULL, (xmlNodePtr )0);
#line 299 "mixer-pxml.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PXML (self), (xmlNodePtr )0);
#line 795 "xfce-mixer-pxml.c"
{
#line 300 "mixer-pxml.gob"
	
		if (!self->node)
			return NULL;

		return xmlNewTextChild (self->node, NULL, (const xmlChar *)name, (const xmlChar *) opt_text);
	}}
#line 804 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 307 "mixer-pxml.gob"
XfceMixerPxml * 
xfce_mixer_pxml_new (gchar const * root)
#line 810 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::new"
{
#line 308 "mixer-pxml.gob"
	
		XfceMixerPxml *p;
		p = XFCE_MIXER_PXML (GET_NEW);
		if (root)
			p->root = g_strdup (root);
		return p;
	}}
#line 822 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__

#line 316 "mixer-pxml.gob"
gchar * 
xfce_mixer_pxml_get_text_child (XfceMixerPxml * self)
#line 828 "xfce-mixer-pxml.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Pxml::get_text_child"
#line 316 "mixer-pxml.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 316 "mixer-pxml.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PXML (self), (gchar * )0);
#line 835 "xfce-mixer-pxml.c"
{
#line 317 "mixer-pxml.gob"
	
		if (!self->node)
			return NULL;

		return xmlNodeListGetString(self->document, self->node->children, 1);
	}}
#line 844 "xfce-mixer-pxml.c"
#undef __GOB_FUNCTION__
