/* Generated by GOB (v2.0.6)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>
#ifndef __XFCE_MIXER_PROFILEDLG_H__
#define __XFCE_MIXER_PROFILEDLG_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include "xfce-mixer-profilebox.h"


/*
 * Type checking and casting macros
 */
#define XFCE_TYPE_MIXER_PROFILEDLG	(xfce_mixer_profiledlg_get_type())
#define XFCE_MIXER_PROFILEDLG(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), xfce_mixer_profiledlg_get_type(), XfceMixerProfiledlg)
#define XFCE_MIXER_PROFILEDLG_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), xfce_mixer_profiledlg_get_type(), XfceMixerProfiledlg const)
#define XFCE_MIXER_PROFILEDLG_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), xfce_mixer_profiledlg_get_type(), XfceMixerProfiledlgClass)
#define XFCE_IS_MIXER_PROFILEDLG(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), xfce_mixer_profiledlg_get_type ())

#define XFCE_MIXER_PROFILEDLG_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), xfce_mixer_profiledlg_get_type(), XfceMixerProfiledlgClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_XFCE_MIXER_PROFILEDLG__
#define __TYPEDEF_XFCE_MIXER_PROFILEDLG__
typedef struct _XfceMixerProfiledlg XfceMixerProfiledlg;
#endif
struct _XfceMixerProfiledlg {
	GtkDialog __parent__;
	/*< private >*/
	XfceMixerProfilebox * pbox; /* protected */
};

/*
 * Class definition
 */
typedef struct _XfceMixerProfiledlgClass XfceMixerProfiledlgClass;
struct _XfceMixerProfiledlgClass {
	GtkDialogClass __parent__;
};


/*
 * Public methods
 */
GType	xfce_mixer_profiledlg_get_type	(void);
XfceMixerProfiledlg * 	xfce_mixer_profiledlg_new	(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
