/* Generated by GOB (v2.0.6)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>
#ifndef __XFCE_MIXER_PROFILEBOX_H__
#define __XFCE_MIXER_PROFILEBOX_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include "xfce-mixer-profilebox-detail.h"
#include "xfce-mixer-profiles.h"
#include "xfce-mixer-profile.h"


/*
 * Type checking and casting macros
 */
#define XFCE_TYPE_MIXER_PROFILEBOX	(xfce_mixer_profilebox_get_type())
#define XFCE_MIXER_PROFILEBOX(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), xfce_mixer_profilebox_get_type(), XfceMixerProfilebox)
#define XFCE_MIXER_PROFILEBOX_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), xfce_mixer_profilebox_get_type(), XfceMixerProfilebox const)
#define XFCE_MIXER_PROFILEBOX_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), xfce_mixer_profilebox_get_type(), XfceMixerProfileboxClass)
#define XFCE_IS_MIXER_PROFILEBOX(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), xfce_mixer_profilebox_get_type ())

#define XFCE_MIXER_PROFILEBOX_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), xfce_mixer_profilebox_get_type(), XfceMixerProfileboxClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_XFCE_MIXER_PROFILEBOX__
#define __TYPEDEF_XFCE_MIXER_PROFILEBOX__
typedef struct _XfceMixerProfilebox XfceMixerProfilebox;
#endif
struct _XfceMixerProfilebox {
	GtkVBox __parent__;
	/*< private >*/
	GtkWidget * sep1; /* protected */
	GtkWidget * sep2; /* protected */
	GtkLabel * device_label; /* protected */
	GtkScrolledWindow * profiles_sw; /* protected */
	GtkTreeView * profiles_tv; /* protected */
	GtkTreeStore * profiles_model; /* protected */
	GtkBox * profiles_box; /* protected */
	GtkWidget * profiles_insert_button; /* protected */
	GtkWidget * profiles_delete_button; /* protected */
	GtkToolbar * profiles_toolbar; /* protected */
	XfceMixerProfileboxDetail * detail; /* protected */
	GtkBox * hbox; /* protected */
	XfceMixerProfiles * profilesa; /* protected */
};

/*
 * Class definition
 */
typedef struct _XfceMixerProfileboxClass XfceMixerProfileboxClass;
struct _XfceMixerProfileboxClass {
	GtkVBoxClass __parent__;
};


/*
 * Public methods
 */
GType	xfce_mixer_profilebox_get_type	(void);
void 	xfce_mixer_profilebox_profile_insert_cb	(XfceMixerProfilebox * self);
void 	xfce_mixer_profilebox_delete_profile	(XfceMixerProfilebox * self,
					gchar const * name);
void 	xfce_mixer_profilebox_profile_delete_cb	(XfceMixerProfilebox * self);
XfceMixerProfilebox * 	xfce_mixer_profilebox_new	(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
