/* Generated by GOB (v2.0.6)   (do not edit directly) */

#ifndef __XFCE_MIXER_PROFILES_PRIVATE_H__
#define __XFCE_MIXER_PROFILES_PRIVATE_H__

#include "xfce-mixer-profiles.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include "xfce-mixer-profile.h"
#include "xfce-mixer-pxml.h"

#line 1 "mixer-profiles.gob"
#line 20 "xfce-mixer-profiles-private.h"
void 	xfce_mixer_profiles_goto_device	(XfceMixerProfiles * self);
void 	xfce_mixer_profiles_load_profile	(XfceMixerProfiles * self, XfceMixerProfile * p);
void 	xfce_mixer_profiles_xml_text_child	(XfceMixerProfiles * self, gchar const * tagname);
void 	xfce_mixer_profiles_save_profile	(XfceMixerProfiles * self, XfceMixerProfile * p);
gboolean 	xfce_mixer_profiles_delayed_pc_cb	(XfceMixerProfiles * self);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
