/* Generated by GOB (v2.0.9) on Wed Jul 21 21:09:32 2004
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 9

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "xfce-mixer-select.h"

#include "xfce-mixer-select-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-select.gob"

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#line 33 "xfce-mixer-select.c"

#line 7 "mixer-select.gob"

#include <gtk/gtk.h>
#include "xfce-mixer-control.h"
#include "xfce-mixer-cache-vc.h"

#line 41 "xfce-mixer-select.c"

#line 12 "mixer-select.gob"

#include "stringlist.inc"
#include "string_option_menu.h"

#line 48 "xfce-mixer-select.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_SELECT(x)
#define SELF_CONST(x) XFCE_MIXER_SELECT_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_SELECT(x)
#define TYPE_SELF XFCE_TYPE_MIXER_SELECT
#define SELF_CLASS(x) XFCE_MIXER_SELECT_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_SELECT_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerSelect Self;
typedef XfceMixerSelectClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_select_class_init (XfceMixerSelectClass * c) G_GNUC_UNUSED;
static void ___2_xfce_mixer_select_value_changed (XfceMixerControl * pself) G_GNUC_UNUSED;
static void xfce_mixer_select_init (XfceMixerSelect * self) G_GNUC_UNUSED;
static void ___5_xfce_mixer_select_vcname_changed (XfceMixerControl * pself) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static XfceMixerControlClass *parent_class = NULL;

/* Short form macros */
#define self_changed_cb xfce_mixer_select_changed_cb
#define self_new xfce_mixer_select_new
GType
xfce_mixer_select_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerSelectClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_select_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerSelect),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_select_init,
			NULL
		};

		type = g_type_register_static (XFCE_TYPE_MIXER_CONTROL, "XfceMixerSelect", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerSelect *)g_object_new(xfce_mixer_select_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerSelect * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerSelect *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerSelect *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerSelect *)g_object_new_valist (xfce_mixer_select_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Select::finalize"
	XfceMixerSelect *self  G_GNUC_UNUSED = XFCE_MIXER_SELECT (obj_self);
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#define choices (self->choices)
#define VAR choices
	{
#line 21 "mixer-select.gob"
	
			stringlist_free(VAR);
			VAR = NULL;
		}
#line 132 "xfce-mixer-select.c"
	memset(&choices, 0, sizeof(choices));
#undef VAR
#undef choices
}
#undef __GOB_FUNCTION__

static void 
xfce_mixer_select_class_init (XfceMixerSelectClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Select::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;
	XfceMixerControlClass *xfce_mixer_control_class = (XfceMixerControlClass *)c;

	parent_class = g_type_class_ref (XFCE_TYPE_MIXER_CONTROL);

#line 41 "mixer-select.gob"
	xfce_mixer_control_class->value_changed = ___2_xfce_mixer_select_value_changed;
#line 75 "mixer-select.gob"
	xfce_mixer_control_class->vcname_changed = ___5_xfce_mixer_select_vcname_changed;
#line 152 "xfce-mixer-select.c"
	g_object_class->finalize = ___finalize;
}
#undef __GOB_FUNCTION__
#line 59 "mixer-select.gob"
static void 
xfce_mixer_select_init (XfceMixerSelect * self G_GNUC_UNUSED)
#line 159 "xfce-mixer-select.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Select::init"
#line 12 "mixer-select.gob"
	self->om = NULL;
#line 164 "xfce-mixer-select.c"
#line 12 "mixer-select.gob"
	self->label = NULL;
#line 167 "xfce-mixer-select.c"
#line 12 "mixer-select.gob"
	self->choices = NULL;
#line 170 "xfce-mixer-select.c"
 {
#line 60 "mixer-select.gob"

		self->label = GTK_LABEL (gtk_label_new (""));
		self->om = GTK_OPTION_MENU (gtk_option_menu_new ());
		gtk_widget_show (GTK_WIDGET (self->label));
		gtk_widget_show (GTK_WIDGET (self->om));
		gtk_box_pack_start (GTK_BOX (self), GTK_WIDGET (self->label), FALSE, FALSE, 0);
		gtk_box_pack_start (GTK_BOX (self), GTK_WIDGET (self->om), FALSE, FALSE, 0);
		g_signal_connect_swapped (G_OBJECT (self->om), "changed", G_CALLBACK (self_changed_cb), self);
	
#line 182 "xfce-mixer-select.c"
 }
}
#undef __GOB_FUNCTION__


#line 26 "mixer-select.gob"
void 
xfce_mixer_select_changed_cb (XfceMixerSelect * self, gpointer om)
#line 191 "xfce-mixer-select.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Select::changed_cb"
#line 26 "mixer-select.gob"
	g_return_if_fail (self != NULL);
#line 26 "mixer-select.gob"
	g_return_if_fail (XFCE_IS_MIXER_SELECT (self));
#line 198 "xfce-mixer-select.c"
{
#line 27 "mixer-select.gob"
	
		gint i;
		gchar const *s;
		s = NULL;
		i = gtk_option_menu_get_history (self->om);
		if (i >= 0) {
			s = g_list_nth_data (self->choices, i);
		}

		if (s) {
			g_object_set (G_OBJECT (self), "value", s, NULL);
		}
	}}
#line 214 "xfce-mixer-select.c"
#undef __GOB_FUNCTION__

#line 41 "mixer-select.gob"
static void 
___2_xfce_mixer_select_value_changed (XfceMixerControl * pself G_GNUC_UNUSED)
#line 220 "xfce-mixer-select.c"
#define PARENT_HANDLER(___pself) \
	{ if(XFCE_MIXER_CONTROL_CLASS(parent_class)->value_changed) \
		(* XFCE_MIXER_CONTROL_CLASS(parent_class)->value_changed)(___pself); }
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Select::value_changed"
#line 41 "mixer-select.gob"
	g_return_if_fail (pself != NULL);
#line 41 "mixer-select.gob"
	g_return_if_fail (XFCE_IS_MIXER_CONTROL (pself));
#line 230 "xfce-mixer-select.c"
{
#line 43 "mixer-select.gob"
	
		gchar *s;
                Self *self;
		gint i;
                self = SELF (pself);

		s = XFCE_MIXER_CONTROL (self)->value;

		if (s)
		for(i = 0; i < g_list_length (self->choices); i++) {
			if (g_str_equal ((gchar *)g_list_nth_data (self->choices, i), s)) {
				gtk_option_menu_set_history (self->om, i);
			}
		}
        }}
#line 248 "xfce-mixer-select.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER


#line 70 "mixer-select.gob"
XfceMixerControl * 
xfce_mixer_select_new (void)
#line 256 "xfce-mixer-select.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Select::new"
{
#line 71 "mixer-select.gob"
	
		return XFCE_MIXER_CONTROL(GET_NEW);
	}}
#line 264 "xfce-mixer-select.c"
#undef __GOB_FUNCTION__

#line 75 "mixer-select.gob"
static void 
___5_xfce_mixer_select_vcname_changed (XfceMixerControl * pself G_GNUC_UNUSED)
#line 270 "xfce-mixer-select.c"
#define PARENT_HANDLER(___pself) \
	{ if(XFCE_MIXER_CONTROL_CLASS(parent_class)->vcname_changed) \
		(* XFCE_MIXER_CONTROL_CLASS(parent_class)->vcname_changed)(___pself); }
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Select::vcname_changed"
#line 75 "mixer-select.gob"
	g_return_if_fail (pself != NULL);
#line 75 "mixer-select.gob"
	g_return_if_fail (XFCE_IS_MIXER_CONTROL (pself));
#line 280 "xfce-mixer-select.c"
{
#line 77 "mixer-select.gob"
	
		Self *self;
		char *sanename;
		gchar *tmp;

		self = SELF (pself);
		PARENT_HANDLER (pself);

		tmp = NULL;
		sanename = xfce_mixer_control_calc_sanename (pself);
		if (sanename)
			tmp = g_strdup_printf ("%s:", sanename);

		gtk_label_set_text (GTK_LABEL (self->label), tmp);
		if (tmp)
			g_free (tmp);

		if (sanename)
			g_free (sanename);

		if (self->choices) {
			stringlist_free (self->choices);
			self->choices = NULL;
		}

		self->choices = xfce_mixer_cache_vc_get_choices (
			XFCE_MIXER_CONTROL(self)->vcname
		);
		fill_string_option_menu (self->om, self->choices);
        }}
#line 313 "xfce-mixer-select.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER
