/* Generated by GOB (v2.0.11) on Sat Dec 24 13:39:23 2005
   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 11

#define selfp (self->_priv)

#include <string.h> /* memset() */

#include "xfce-mixer-preferences.h"

#include "xfce-mixer-preferences-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-preferences.gob"

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#line 33 "xfce-mixer-preferences.c"

#line 6 "mixer-preferences.gob"

#include <gtk/gtk.h>
#include <libxfce4util/libxfce4util.h>

#line 40 "xfce-mixer-preferences.c"

#line 13 "mixer-preferences.gob"

#include "xfce-mixer-cache-vc.h"
#include "vc.h"
#include "helpers.inc"
#include "stringlist.inc"

#define MIXER_ROOT "Mixer"


#line 52 "xfce-mixer-preferences.c"

#line 22 "mixer-preferences.gob"


#line 57 "xfce-mixer-preferences.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_PREFERENCES(x)
#define SELF_CONST(x) XFCE_MIXER_PREFERENCES_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_PREFERENCES(x)
#define TYPE_SELF XFCE_TYPE_MIXER_PREFERENCES
#define SELF_CLASS(x) XFCE_MIXER_PREFERENCES_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_PREFERENCES_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerPreferences Self;
typedef XfceMixerPreferencesClass SelfClass;

/* here are local prototypes */
static void ___object_set_property (GObject *object, guint property_id, const GValue *value, GParamSpec *pspec);
static void ___object_get_property (GObject *object, guint property_id, GValue *value, GParamSpec *pspec);
static void xfce_mixer_preferences_class_init (XfceMixerPreferencesClass * c) G_GNUC_UNUSED;
static void xfce_mixer_preferences_init (XfceMixerPreferences * self) G_GNUC_UNUSED;

enum {
	PROP_0,
	PROP_DEVICE,
	PROP_MASTER,
	PROP_LAUNCHER_COMMAND,
	PROP_LAUNCHER_RUN_IN_TERMINAL,
	PROP_LAUNCHER_USE_STARTUP_NOTIFICATION
};

/* pointer to the class of our parent */
static GObjectClass *parent_class = NULL;

/* Short form macros */
#define self_new xfce_mixer_preferences_new
#define self_fill_probably_master xfce_mixer_preferences_fill_probably_master
#define self_find_probably_master xfce_mixer_preferences_find_probably_master
#define self_load xfce_mixer_preferences_load
#define self_save xfce_mixer_preferences_save
GType
xfce_mixer_preferences_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerPreferencesClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_preferences_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerPreferences),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_preferences_init,
			NULL
		};

		type = g_type_register_static (G_TYPE_OBJECT, "XfceMixerPreferences", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerPreferences *)g_object_new(xfce_mixer_preferences_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerPreferences * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerPreferences *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerPreferences *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerPreferences *)g_object_new_valist (xfce_mixer_preferences_get_type (), first, ap);
	va_end (ap);
	return ret;
}


static void
___finalize(GObject *obj_self)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Preferences::finalize"
	XfceMixerPreferences *self G_GNUC_UNUSED = XFCE_MIXER_PREFERENCES (obj_self);
	gpointer priv G_GNUC_UNUSED = self->_priv;
	if(G_OBJECT_CLASS(parent_class)->finalize) \
		(* G_OBJECT_CLASS(parent_class)->finalize)(obj_self);
#define device (self->_priv->device)
#define VAR device
	{
#line 27 "mixer-preferences.gob"
	
			if (VAR) {
				g_free (VAR);
				VAR = NULL;
			}
		}
#line 156 "xfce-mixer-preferences.c"
	memset(&device, 0, sizeof(device));
#undef VAR
#undef device
#define master (self->_priv->master)
#define VAR master
	{
#line 35 "mixer-preferences.gob"
	
			if (VAR) {
				g_free (VAR);
				VAR = NULL;
			}
		}
#line 170 "xfce-mixer-preferences.c"
	memset(&master, 0, sizeof(master));
#undef VAR
#undef master
#define probably_master (self->probably_master)
#define VAR probably_master
	{
#line 43 "mixer-preferences.gob"
	
			if (VAR) {
				g_free (VAR);
				VAR = NULL;
			}
		}
#line 184 "xfce-mixer-preferences.c"
	memset(&probably_master, 0, sizeof(probably_master));
#undef VAR
#undef probably_master
#define launcher_command (self->_priv->launcher_command)
#define VAR launcher_command
	{
#line 51 "mixer-preferences.gob"
	
			if (VAR) {
				g_free (VAR);
				VAR = NULL;
			}
		}
#line 198 "xfce-mixer-preferences.c"
	memset(&launcher_command, 0, sizeof(launcher_command));
#undef VAR
#undef launcher_command
#define master_lst (self->master_lst)
#define VAR master_lst
	{
#line 62 "mixer-preferences.gob"
	
			stringlist_free(VAR);
			VAR = NULL;
		}
#line 210 "xfce-mixer-preferences.c"
	memset(&master_lst, 0, sizeof(master_lst));
#undef VAR
#undef master_lst
}
#undef __GOB_FUNCTION__

static void 
xfce_mixer_preferences_class_init (XfceMixerPreferencesClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Preferences::class_init"
	GObjectClass *g_object_class G_GNUC_UNUSED = (GObjectClass*) c;

	g_type_class_add_private(c,sizeof(XfceMixerPreferencesPrivate));

	parent_class = g_type_class_ref (G_TYPE_OBJECT);

	g_object_class->finalize = ___finalize;
	g_object_class->get_property = ___object_get_property;
	g_object_class->set_property = ___object_set_property;
    {
	GParamSpec   *param_spec;

	param_spec = g_param_spec_string
		("device" /* name */,
		 "The device to use for this item" /* nick */,
		 "The sound device to use for this item" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_DEVICE,
		param_spec);
	param_spec = g_param_spec_string
		("master" /* name */,
		 "master control name" /* nick */,
		 "The vcname of the master control for the plugin" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_MASTER,
		param_spec);
	param_spec = g_param_spec_string
		("launcher_command" /* name */,
		 "program to start on click" /* nick */,
		 "The command line to start when the plugin is clicked" /* blurb */,
		 NULL /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_LAUNCHER_COMMAND,
		param_spec);
	param_spec = g_param_spec_boolean
		("launcher_run_in_terminal" /* name */,
		 "start the program in a terminal" /* nick */,
		 "start the program in a terminal" /* blurb */,
		 FALSE /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_LAUNCHER_RUN_IN_TERMINAL,
		param_spec);
	param_spec = g_param_spec_boolean
		("launcher_use_startup_notification" /* name */,
		 "use startup notification" /* nick */,
		 "use startup notification" /* blurb */,
		 FALSE /* default_value */,
		 (GParamFlags)(G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (g_object_class,
		PROP_LAUNCHER_USE_STARTUP_NOTIFICATION,
		param_spec);
    }
}
#undef __GOB_FUNCTION__
#line 192 "mixer-preferences.gob"
static void 
xfce_mixer_preferences_init (XfceMixerPreferences * self G_GNUC_UNUSED)
#line 284 "xfce-mixer-preferences.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Preferences::init"
	self->_priv = G_TYPE_INSTANCE_GET_PRIVATE(self,TYPE_SELF,XfceMixerPreferencesPrivate);
#line 22 "mixer-preferences.gob"
	self->_priv->device = NULL;
#line 290 "xfce-mixer-preferences.c"
#line 27 "mixer-preferences.gob"
	self->_priv->master = NULL;
#line 293 "xfce-mixer-preferences.c"
#line 35 "mixer-preferences.gob"
	self->probably_master = NULL;
#line 296 "xfce-mixer-preferences.c"
#line 43 "mixer-preferences.gob"
	self->_priv->launcher_command = NULL;
#line 299 "xfce-mixer-preferences.c"
#line 51 "mixer-preferences.gob"
	self->_priv->launcher_run_in_terminal = FALSE;
#line 302 "xfce-mixer-preferences.c"
#line 51 "mixer-preferences.gob"
	self->_priv->launcher_use_startup_notification = FALSE;
#line 305 "xfce-mixer-preferences.c"
#line 51 "mixer-preferences.gob"
	self->master_lst = NULL;
#line 308 "xfce-mixer-preferences.c"
 {
#line 193 "mixer-preferences.gob"

		self_fill_probably_master (self);
	
#line 314 "xfce-mixer-preferences.c"
 }
}
#undef __GOB_FUNCTION__

static void
___object_set_property (GObject *object,
	guint property_id,
	const GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Xfce:Mixer:Preferences::set_property"
{
	XfceMixerPreferences *self G_GNUC_UNUSED;

	self = XFCE_MIXER_PREFERENCES (object);

	switch (property_id) {
	case PROP_DEVICE:
		{
#line 70 "mixer-preferences.gob"

		if (selfp->device) {
			g_free (selfp->device);
			selfp->device = NULL;
		}
		selfp->device = g_strdup (g_value_get_string (VAL));

		self_fill_probably_master (self);

		if (selfp->master && !xfce_mixer_cache_vc_valid (selfp->master)) {
			g_object_set (G_OBJECT (self), "master", NULL, NULL);
		}
	
#line 347 "xfce-mixer-preferences.c"
		}
		break;
	case PROP_MASTER:
		{
#line 90 "mixer-preferences.gob"

		if (selfp->master) {
			g_free (selfp->master);
			selfp->master = NULL;
		}
		if (VAL)
			selfp->master = g_strdup (g_value_get_string (VAL));
		else
			selfp->master = NULL;
	
#line 363 "xfce-mixer-preferences.c"
		}
		break;
	case PROP_LAUNCHER_COMMAND:
		{
#line 110 "mixer-preferences.gob"

		if (selfp->launcher_command) {
			g_free (self->_priv->launcher_command);
			selfp->launcher_command = NULL;
		}
		selfp->launcher_command = g_strdup (g_value_get_string (VAL));
	
#line 376 "xfce-mixer-preferences.c"
		}
		break;
	case PROP_LAUNCHER_RUN_IN_TERMINAL:
		{
#line 121 "mixer-preferences.gob"
self->_priv->launcher_run_in_terminal = g_value_get_boolean (VAL);
#line 383 "xfce-mixer-preferences.c"
		}
		break;
	case PROP_LAUNCHER_USE_STARTUP_NOTIFICATION:
		{
#line 125 "mixer-preferences.gob"
self->_priv->launcher_use_startup_notification = g_value_get_boolean (VAL);
#line 390 "xfce-mixer-preferences.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__

static void
___object_get_property (GObject *object,
	guint property_id,
	GValue *VAL G_GNUC_UNUSED,
	GParamSpec *pspec G_GNUC_UNUSED)
#define __GOB_FUNCTION__ "Xfce:Mixer:Preferences::get_property"
{
	XfceMixerPreferences *self G_GNUC_UNUSED;

	self = XFCE_MIXER_PREFERENCES (object);

	switch (property_id) {
	case PROP_DEVICE:
		{
#line 83 "mixer-preferences.gob"

		g_value_set_string (VAL, selfp->device);
	
#line 423 "xfce-mixer-preferences.c"
		}
		break;
	case PROP_MASTER:
		{
#line 100 "mixer-preferences.gob"

		if (!self->_priv->master)
			g_value_set_string (VAL, self->probably_master);
		else
			g_value_set_string (VAL, self->_priv->master);
	
#line 435 "xfce-mixer-preferences.c"
		}
		break;
	case PROP_LAUNCHER_COMMAND:
		{
#line 117 "mixer-preferences.gob"

		g_value_set_string (VAL, selfp->launcher_command);
	
#line 444 "xfce-mixer-preferences.c"
		}
		break;
	case PROP_LAUNCHER_RUN_IN_TERMINAL:
		{
#line 121 "mixer-preferences.gob"
g_value_set_boolean (VAL, self->_priv->launcher_run_in_terminal);
#line 451 "xfce-mixer-preferences.c"
		}
		break;
	case PROP_LAUNCHER_USE_STARTUP_NOTIFICATION:
		{
#line 125 "mixer-preferences.gob"
g_value_set_boolean (VAL, self->_priv->launcher_use_startup_notification);
#line 458 "xfce-mixer-preferences.c"
		}
		break;
	default:
/* Apparently in g++ this is needed, glib is b0rk */
#ifndef __PRETTY_FUNCTION__
#  undef G_STRLOC
#  define G_STRLOC	__FILE__ ":" G_STRINGIFY (__LINE__)
#endif
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}
#undef __GOB_FUNCTION__


#line 129 "mixer-preferences.gob"
XfceMixerPreferences * 
xfce_mixer_preferences_new (void)
#line 477 "xfce-mixer-preferences.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Preferences::new"
{
#line 130 "mixer-preferences.gob"
	
		return XFCE_MIXER_PREFERENCES (GET_NEW);
	}}
#line 485 "xfce-mixer-preferences.c"
#undef __GOB_FUNCTION__

#line 134 "mixer-preferences.gob"
void 
xfce_mixer_preferences_fill_probably_master (XfceMixerPreferences * self)
#line 491 "xfce-mixer-preferences.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Preferences::fill_probably_master"
#line 134 "mixer-preferences.gob"
	g_return_if_fail (self != NULL);
#line 134 "mixer-preferences.gob"
	g_return_if_fail (XFCE_IS_MIXER_PREFERENCES (self));
#line 498 "xfce-mixer-preferences.c"
{
#line 135 "mixer-preferences.gob"
	
		if (self->probably_master) {
			g_free (self->probably_master);
			self->probably_master = NULL;
		}
		if (self->master_lst) {
			stringlist_free (self->master_lst);
			self->master_lst = NULL;
		}
		xfce_mixer_cache_vc_foreach (master_enum_cb, &self->master_lst);

		self->probably_master = self_find_probably_master (self);
	}}
#line 514 "xfce-mixer-preferences.c"
#undef __GOB_FUNCTION__

#line 149 "mixer-preferences.gob"
gchar * 
xfce_mixer_preferences_find_probably_master (XfceMixerPreferences * self)
#line 520 "xfce-mixer-preferences.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Preferences::find_probably_master"
#line 149 "mixer-preferences.gob"
	g_return_val_if_fail (self != NULL, (gchar * )0);
#line 149 "mixer-preferences.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_PREFERENCES (self), (gchar * )0);
#line 527 "xfce-mixer-preferences.c"
{
#line 150 "mixer-preferences.gob"
	
		/* search om, find "Master", return index or -1 */
		gchar *r_s;
		gchar *master_s;
		gchar *master1_s;
		gchar *pcm_s;
		GList *g;
		gchar *s;
		master_s = NULL;
		master1_s = NULL;
		pcm_s = NULL;
		r_s = NULL;

		g = self->master_lst;
		while (g) {
			s = (gchar *)g->data;
			if (s) {
				if (g_str_has_prefix (s, "Master,")) master_s = s;
				else if (g_str_has_prefix (s, "Master")) {
					if (!master1_s) 
						master1_s = s;
				}
				else if (g_str_has_prefix (s, "PCM")) {
					pcm_s = s;
				}
			}
			g = g_list_next (g);
		}

		if (master_s)
			r_s = master_s;
		else if (master1_s)
			r_s = master1_s;
		else if (pcm_s)
			r_s = pcm_s;

		if (!r_s)
			return NULL;

		return g_strdup (r_s);
	}}
#line 571 "xfce-mixer-preferences.c"
#undef __GOB_FUNCTION__


#line 197 "mixer-preferences.gob"
void 
xfce_mixer_preferences_load (XfceMixerPreferences * self, XfceRc * rc)
#line 578 "xfce-mixer-preferences.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Preferences::load"
#line 197 "mixer-preferences.gob"
	g_return_if_fail (self != NULL);
#line 197 "mixer-preferences.gob"
	g_return_if_fail (XFCE_IS_MIXER_PREFERENCES (self));
#line 585 "xfce-mixer-preferences.c"
{
#line 198 "mixer-preferences.gob"
	
		/* configurable:
			Device
			LauncherCommand
			LauncherRunInTerminal
			LauncherUseStartupNotification
			MasterControl
		*/

		gchar const* device;
		gchar const* launcher_command;
		gboolean launcher_run_in_terminal;
		gboolean launcher_use_startup_notification;
		gchar const* master_control;

		device = xfce_rc_read_entry (rc, "Device", NULL);
		launcher_command = xfce_rc_read_entry (rc, "LauncherCommand", NULL);
		launcher_run_in_terminal = xfce_rc_read_bool_entry (rc, "LauncherRunInTerminal", FALSE);
		launcher_use_startup_notification = xfce_rc_read_bool_entry (rc, "LauncherUseStartupNotification", FALSE);
		master_control = xfce_rc_read_entry (rc, "MasterControl", NULL);

		if (device) {
			g_object_set (G_OBJECT (self), "device", device, NULL);
		}

		g_object_set (G_OBJECT (self), 
					"launcher_command", launcher_command, 
					"launcher_run_in_terminal", (gboolean) launcher_run_in_terminal,
					"launcher_use_startup_notification", (gboolean) launcher_use_startup_notification,
				NULL);

		if (master_control) {
			g_object_set (G_OBJECT (self), "master", master_control, NULL);
		}
	}}
#line 623 "xfce-mixer-preferences.c"
#undef __GOB_FUNCTION__

#line 234 "mixer-preferences.gob"
void 
xfce_mixer_preferences_save (XfceMixerPreferences * self, XfceRc * rc)
#line 629 "xfce-mixer-preferences.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Preferences::save"
#line 234 "mixer-preferences.gob"
	g_return_if_fail (self != NULL);
#line 234 "mixer-preferences.gob"
	g_return_if_fail (XFCE_IS_MIXER_PREFERENCES (self));
#line 636 "xfce-mixer-preferences.c"
{
#line 235 "mixer-preferences.gob"
	
		/* configurable:
			Device
			LauncherCommand
			LauncherRunInTerminal
			LauncherUseStartupNotification
			MasterControl
		*/

		gchar const* launcher_command;
		gboolean launcher_run_in_terminal;
		gboolean launcher_use_startup_notification;
		gchar const* device;
		gchar const* master_control;

		launcher_command = self->_priv->launcher_command;
		launcher_run_in_terminal = self->_priv->launcher_run_in_terminal;
		launcher_use_startup_notification = self->_priv->launcher_use_startup_notification;
		device = self->_priv->device;
		master_control = self->_priv->master;

		if (device) {
			xfce_rc_write_entry (rc, "Device", device);
		} else {
			xfce_rc_delete_entry (rc, "Device", FALSE);
		}

		if (launcher_command) {
			xfce_rc_write_entry (rc, "LauncherCommand", launcher_command);
		} else {
			xfce_rc_delete_entry (rc, "LauncherCommand", FALSE);
		}

		xfce_rc_write_bool_entry (rc, "LauncherRunInTerminal", launcher_run_in_terminal);
		xfce_rc_write_bool_entry (rc, "LauncherUseStartupNotification", launcher_use_startup_notification);

		if (master_control) {
			xfce_rc_write_entry (rc, "MasterControl", master_control);
		} else {
			xfce_rc_delete_entry (rc, "MasterControl", FALSE);
		}

	}}
#line 682 "xfce-mixer-preferences.c"
#undef __GOB_FUNCTION__
