/* Generated by GOB (v2.0.15)   (do not edit directly) */

#ifndef __XFCE_MIXER_PREFBOX_PRIVATE_H__
#define __XFCE_MIXER_PREFBOX_PRIVATE_H__

#include "xfce-mixer-prefbox.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include <gtk/gtk.h>
#include <libxfcegui4/libxfcegui4.h>
#include <libxfce4util/libxfce4util.h>
#include "xfce-mixer-preferences.h"
#include "vc.h"
#include "xfce-mixer-cache-vc.h"
#include "launcher-entry.h"

/* why is this deprecated when it is needed by combo ? O_o */
GtkWidget *gtk_list_item_new_with_label (const gchar *label);


#line 6 "mixer-prefbox.gob"
#line 28 "xfce-mixer-prefbox-private.h"
struct _XfceMixerPrefboxPrivate {
#line 46 "mixer-prefbox.gob"
	delayer_t device_entry_delayer;
#line 32 "xfce-mixer-prefbox-private.h"
};
void 	xfce_mixer_prefbox_fill_device_list	(XfceMixerPrefbox * self);
void 	xfce_mixer_prefbox_fill_master_list	(XfceMixerPrefbox * self);
gchar * 	xfce_mixer_prefbox_find_name_by_master_i	(XfceMixerPrefbox * self, gint master_i);
gint 	xfce_mixer_prefbox_find_master_by_name	(XfceMixerPrefbox * self, gchar const * name);
void 	xfce_mixer_prefbox_add_command_box	(XfceMixerPrefbox * self);
gboolean 	xfce_mixer_prefbox_device_changed_delayed_cb	(XfceMixerPrefbox * self);
void 	xfce_mixer_prefbox_device_changed_cb	(XfceMixerPrefbox * self, GtkEditable * e);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
