/* Generated by GOB (v2.0.6)   (do not edit directly) */

#include <glib.h>
#include <glib-object.h>
#ifndef __XFCE_MIXER_PXML_H__
#define __XFCE_MIXER_PXML_H__

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */




#include <gtk/gtk.h>
#include <libxml/parser.h>
#include <libxml/tree.h>



/*
 * Type checking and casting macros
 */
#define XFCE_TYPE_MIXER_PXML	(xfce_mixer_pxml_get_type())
#define XFCE_MIXER_PXML(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), xfce_mixer_pxml_get_type(), XfceMixerPxml)
#define XFCE_MIXER_PXML_CONST(obj)	G_TYPE_CHECK_INSTANCE_CAST((obj), xfce_mixer_pxml_get_type(), XfceMixerPxml const)
#define XFCE_MIXER_PXML_CLASS(klass)	G_TYPE_CHECK_CLASS_CAST((klass), xfce_mixer_pxml_get_type(), XfceMixerPxmlClass)
#define XFCE_IS_MIXER_PXML(obj)	G_TYPE_CHECK_INSTANCE_TYPE((obj), xfce_mixer_pxml_get_type ())

#define XFCE_MIXER_PXML_GET_CLASS(obj)	G_TYPE_INSTANCE_GET_CLASS((obj), xfce_mixer_pxml_get_type(), XfceMixerPxmlClass)

/*
 * Main object structure
 */
#ifndef __TYPEDEF_XFCE_MIXER_PXML__
#define __TYPEDEF_XFCE_MIXER_PXML__
typedef struct _XfceMixerPxml XfceMixerPxml;
#endif
struct _XfceMixerPxml {
	GObject __parent__;
	/*< public >*/
	xmlNodePtr node;
	/*< private >*/
	gchar * root; /* protected */
	gchar * fname; /* protected */
	xmlDocPtr document; /* protected */
};

/*
 * Class definition
 */
typedef struct _XfceMixerPxmlClass XfceMixerPxmlClass;
struct _XfceMixerPxmlClass {
	GObjectClass __parent__;
};


/*
 * Public methods
 */
GType	xfce_mixer_pxml_get_type	(void);
void 	xfce_mixer_pxml_set_document	(XfceMixerPxml * self,
					xmlDocPtr doc);
void 	xfce_mixer_pxml_eat_children	(XfceMixerPxml * self,
					GList * exceptions);
gboolean 	xfce_mixer_pxml_goto_next	(XfceMixerPxml * self);
gboolean 	xfce_mixer_pxml_check_tag	(XfceMixerPxml * self,
					gchar const * tagname);
gboolean 	xfce_mixer_pxml_goto_child_tag	(XfceMixerPxml * self,
					gchar const * tagname);
gboolean 	xfce_mixer_pxml_has_parent	(XfceMixerPxml * self);
void 	xfce_mixer_pxml_goto_parent	(XfceMixerPxml * self);
void 	xfce_mixer_pxml_goto_children	(XfceMixerPxml * self);
void 	xfce_mixer_pxml_goto_root	(XfceMixerPxml * self);
void 	xfce_mixer_pxml_goto_node	(XfceMixerPxml * self,
					xmlNodePtr nn);
gboolean 	xfce_mixer_pxml_has_children	(XfceMixerPxml * self);
gchar * 	xfce_mixer_pxml_get_prop	(XfceMixerPxml * self,
					gchar const * pname);
void 	xfce_mixer_pxml_set_prop	(XfceMixerPxml * self,
					gchar const * pname,
					gchar const * value);
xmlNodePtr 	xfce_mixer_pxml_create_text_child	(XfceMixerPxml * self,
					gchar const * name,
					gchar const * opt_text);
XfceMixerPxml * 	xfce_mixer_pxml_new	(gchar const * root);
gchar * 	xfce_mixer_pxml_get_text_child	(XfceMixerPxml * self);

/*
 * Argument wrapping macros
 */
#if defined(__GNUC__) && !defined(__STRICT_ANSI__)
#define XFCE_MIXER_PXML_PROP_FNAME(arg)    	"fname",({gchar *z = (arg); z;})
#define XFCE_MIXER_PXML_GET_PROP_FNAME(arg)	"fname",({gchar **z = (arg); z;})
#else /* __GNUC__ && !__STRICT_ANSI__ */
#define XFCE_MIXER_PXML_PROP_FNAME(arg)    	"fname",(gchar *)(arg)
#define XFCE_MIXER_PXML_GET_PROP_FNAME(arg)	"fname",(gchar **)(arg)
#endif /* __GNUC__ && !__STRICT_ANSI__ */


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
