/* Generated by GOB (v2.0.6)   (do not edit directly) */

#ifndef __XFCE_MIXER_SLIDER_TINY_PRIVATE_H__
#define __XFCE_MIXER_SLIDER_TINY_PRIVATE_H__

#include "xfce-mixer-slider-tiny.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */



#include "xfce-mixer-control.h"

#line 6 "mixer-slider-tiny.gob"
#line 18 "xfce-mixer-slider-tiny-private.h"
void 	xfce_mixer_slider_tiny_set_vval	(XfceMixerSliderTiny * self, gint vval);
gboolean 	xfce_mixer_slider_tiny_button_cb	(XfceMixerSliderTiny * self, GdkEventButton * b, GtkWidget * widget);

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
