/* Generated by GOB (v2.0.15)   (do not edit directly) */

/* End world hunger, donate to the World Food Programme, http://www.wfp.org */

#define GOB_VERSION_MAJOR 2
#define GOB_VERSION_MINOR 0
#define GOB_VERSION_PATCHLEVEL 15

#define selfp (self->_priv)

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif
#include <string.h> /* memset() */

#include "xfce-mixer-slider-tiny.h"

#include "xfce-mixer-slider-tiny-private.h"

#ifdef G_LIKELY
#define ___GOB_LIKELY(expr) G_LIKELY(expr)
#define ___GOB_UNLIKELY(expr) G_UNLIKELY(expr)
#else /* ! G_LIKELY */
#define ___GOB_LIKELY(expr) (expr)
#define ___GOB_UNLIKELY(expr) (expr)
#endif /* G_LIKELY */

#line 1 "mixer-slider-tiny.gob"

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#line 35 "xfce-mixer-slider-tiny.c"

#line 6 "mixer-slider-tiny.gob"

#include "xfce-mixer-control.h"

#line 41 "xfce-mixer-slider-tiny.c"

#line 10 "mixer-slider-tiny.gob"

extern GtkTooltips *tooltips;

#line 47 "xfce-mixer-slider-tiny.c"
/* self casting macros */
#define SELF(x) XFCE_MIXER_SLIDER_TINY(x)
#define SELF_CONST(x) XFCE_MIXER_SLIDER_TINY_CONST(x)
#define IS_SELF(x) XFCE_IS_MIXER_SLIDER_TINY(x)
#define TYPE_SELF XFCE_TYPE_MIXER_SLIDER_TINY
#define SELF_CLASS(x) XFCE_MIXER_SLIDER_TINY_CLASS(x)

#define SELF_GET_CLASS(x) XFCE_MIXER_SLIDER_TINY_GET_CLASS(x)

/* self typedefs */
typedef XfceMixerSliderTiny Self;
typedef XfceMixerSliderTinyClass SelfClass;

/* here are local prototypes */
static void xfce_mixer_slider_tiny_class_init (XfceMixerSliderTinyClass * c) G_GNUC_UNUSED;
static void xfce_mixer_slider_tiny_init (XfceMixerSliderTiny * self) G_GNUC_UNUSED;
static void ___8_xfce_mixer_slider_tiny_value_changed (XfceMixerControl * pself) G_GNUC_UNUSED;
static void ___9_xfce_mixer_slider_tiny_vcname_changed (XfceMixerControl * pself) G_GNUC_UNUSED;

/* pointer to the class of our parent */
static XfceMixerControlClass *parent_class = NULL;

/* Short form macros */
#define self_set_vval xfce_mixer_slider_tiny_set_vval
#define self_scroll_cb xfce_mixer_slider_tiny_scroll_cb
#define self_button_cb xfce_mixer_slider_tiny_button_cb
#define self_figure_out_volume xfce_mixer_slider_tiny_figure_out_volume
#define self_motion_cb xfce_mixer_slider_tiny_motion_cb
#define self_new xfce_mixer_slider_tiny_new
GType
xfce_mixer_slider_tiny_get_type (void)
{
	static GType type = 0;

	if ___GOB_UNLIKELY(type == 0) {
		static const GTypeInfo info = {
			sizeof (XfceMixerSliderTinyClass),
			(GBaseInitFunc) NULL,
			(GBaseFinalizeFunc) NULL,
			(GClassInitFunc) xfce_mixer_slider_tiny_class_init,
			(GClassFinalizeFunc) NULL,
			NULL /* class_data */,
			sizeof (XfceMixerSliderTiny),
			0 /* n_preallocs */,
			(GInstanceInitFunc) xfce_mixer_slider_tiny_init,
			NULL
		};

		type = g_type_register_static (XFCE_TYPE_MIXER_CONTROL, "XfceMixerSliderTiny", &info, (GTypeFlags)0);
	}

	return type;
}

/* a macro for creating a new object of our type */
#define GET_NEW ((XfceMixerSliderTiny *)g_object_new(xfce_mixer_slider_tiny_get_type(), NULL))

/* a function for creating a new object of our type */
#include <stdarg.h>
static XfceMixerSliderTiny * GET_NEW_VARG (const char *first, ...) G_GNUC_UNUSED;
static XfceMixerSliderTiny *
GET_NEW_VARG (const char *first, ...)
{
	XfceMixerSliderTiny *ret;
	va_list ap;
	va_start (ap, first);
	ret = (XfceMixerSliderTiny *)g_object_new_valist (xfce_mixer_slider_tiny_get_type (), first, ap);
	va_end (ap);
	return ret;
}

static void 
xfce_mixer_slider_tiny_class_init (XfceMixerSliderTinyClass * c G_GNUC_UNUSED)
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider:Tiny::class_init"
	XfceMixerControlClass *xfce_mixer_control_class = (XfceMixerControlClass *)c;

	parent_class = g_type_class_ref (XFCE_TYPE_MIXER_CONTROL);

#line 160 "mixer-slider-tiny.gob"
	xfce_mixer_control_class->value_changed = ___8_xfce_mixer_slider_tiny_value_changed;
#line 174 "mixer-slider-tiny.gob"
	xfce_mixer_control_class->vcname_changed = ___9_xfce_mixer_slider_tiny_vcname_changed;
#line 131 "xfce-mixer-slider-tiny.c"
}
#undef __GOB_FUNCTION__
#line 34 "mixer-slider-tiny.gob"
static void 
xfce_mixer_slider_tiny_init (XfceMixerSliderTiny * self G_GNUC_UNUSED)
#line 137 "xfce-mixer-slider-tiny.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider:Tiny::init"
#line 10 "mixer-slider-tiny.gob"
	self->progress = NULL;
#line 142 "xfce-mixer-slider-tiny.c"
#line 10 "mixer-slider-tiny.gob"
	self->eb = NULL;
#line 145 "xfce-mixer-slider-tiny.c"
#line 10 "mixer-slider-tiny.gob"
	self->pressed = FALSE;
#line 148 "xfce-mixer-slider-tiny.c"
 {
#line 35 "mixer-slider-tiny.gob"

		GtkRcStyle *rc;
		GdkColor color;

		self->progress = GTK_PROGRESS_BAR (gtk_progress_bar_new ());
		gtk_progress_bar_set_orientation (self->progress, GTK_PROGRESS_BOTTOM_TO_TOP);

		rc = gtk_widget_get_modifier_style (GTK_WIDGET (self->progress));
		if (!rc)
			rc = gtk_rc_style_new ();

		gdk_color_parse ("#00c000", &color);

		if (rc) {
			rc->color_flags[GTK_STATE_PRELIGHT] |= GTK_RC_BG;
			rc->bg[GTK_STATE_PRELIGHT] = color;
		}

		gtk_widget_modify_style (GTK_WIDGET (self->progress), rc);

		gtk_widget_show (GTK_WIDGET (self->progress));

		self->eb = GTK_EVENT_BOX (gtk_event_box_new ());
		gtk_widget_show (GTK_WIDGET (self->eb));

		gtk_container_add (GTK_CONTAINER (self->eb), GTK_WIDGET (self->progress));

		gtk_box_pack_start (GTK_BOX (self), GTK_WIDGET (self->eb), TRUE, TRUE, 0);

		g_signal_connect_swapped (self->eb, "scroll-event", G_CALLBACK(self_scroll_cb), self);
		g_signal_connect_swapped (self->eb, "button-press-event", G_CALLBACK(self_button_cb), self);
		g_signal_connect_swapped (self->eb, "button-release-event", G_CALLBACK(self_button_cb), self);
		g_signal_connect_swapped (self->eb, "motion-notify-event", G_CALLBACK(self_motion_cb), self);
	
#line 185 "xfce-mixer-slider-tiny.c"
 }
}
#undef __GOB_FUNCTION__


#line 20 "mixer-slider-tiny.gob"
void 
xfce_mixer_slider_tiny_set_vval (XfceMixerSliderTiny * self, gint vval)
#line 194 "xfce-mixer-slider-tiny.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider:Tiny::set_vval"
#line 20 "mixer-slider-tiny.gob"
	g_return_if_fail (self != NULL);
#line 20 "mixer-slider-tiny.gob"
	g_return_if_fail (XFCE_IS_MIXER_SLIDER_TINY (self));
#line 201 "xfce-mixer-slider-tiny.c"
{
#line 21 "mixer-slider-tiny.gob"
	
		gdouble val;
		gchar *tmp;

		val = vval;
		tmp = g_strdup_printf("%d", (gint) val);
		g_object_set (G_OBJECT (self), "value", tmp, NULL);
		g_free (tmp);

		gtk_progress_bar_set_fraction(GTK_PROGRESS_BAR(self->progress),
		  val / 100.0);
	}}
#line 216 "xfce-mixer-slider-tiny.c"
#undef __GOB_FUNCTION__


#line 70 "mixer-slider-tiny.gob"
gboolean 
xfce_mixer_slider_tiny_scroll_cb (XfceMixerSliderTiny * self, GdkEventScroll * event, GtkWidget * w)
#line 223 "xfce-mixer-slider-tiny.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider:Tiny::scroll_cb"
#line 70 "mixer-slider-tiny.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 70 "mixer-slider-tiny.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_SLIDER_TINY (self), (gboolean )0);
#line 230 "xfce-mixer-slider-tiny.c"
{
#line 71 "mixer-slider-tiny.gob"
	
		int	vol;	/* new volume */
		vol = xfce_mixer_control_calc_num_value (XFCE_MIXER_CONTROL (self));
	
		if (event->type != GDK_SCROLL)
			return FALSE;
	
		if (event->direction == GDK_SCROLL_DOWN) {
			vol -= 7;
			if (vol < 0) { vol = 0; }
		} else if (event->direction == GDK_SCROLL_UP) {
			vol += 7;
			if (vol > 100) { vol = 100; }
		}

		self_set_vval (self, vol);
		return TRUE;

	}}
#line 252 "xfce-mixer-slider-tiny.c"
#undef __GOB_FUNCTION__

#line 91 "mixer-slider-tiny.gob"
gboolean 
xfce_mixer_slider_tiny_button_cb (XfceMixerSliderTiny * self, GdkEventButton * b, GtkWidget * widget)
#line 258 "xfce-mixer-slider-tiny.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider:Tiny::button_cb"
#line 91 "mixer-slider-tiny.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 91 "mixer-slider-tiny.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_SLIDER_TINY (self), (gboolean )0);
#line 265 "xfce-mixer-slider-tiny.c"
{
#line 92 "mixer-slider-tiny.gob"
	
		int        y;

		y = (int) b->y; /* pos */

		if (b->button == 3 || b->button == 2) {
			if (b->type == GDK_BUTTON_PRESS) {
				/* mute */
				y = 0;
			} else {
				return TRUE;
			}
		} else if (b->button == 1) {
			if (b->type == GDK_BUTTON_PRESS) {
				y = self_figure_out_volume(self, widget, y);
				self->pressed = TRUE;
			} else if (b->type == GDK_BUTTON_RELEASE){
				y = self_figure_out_volume(self, widget, y);
				self->pressed = FALSE;
			} else {
				return TRUE;
			}
		} else {
			return FALSE;
		}
		self_set_vval (self, y);
		return TRUE;
	}}
#line 296 "xfce-mixer-slider-tiny.c"
#undef __GOB_FUNCTION__

#line 122 "mixer-slider-tiny.gob"
int 
xfce_mixer_slider_tiny_figure_out_volume (XfceMixerSliderTiny * self, GtkWidget * widget, int y)
#line 302 "xfce-mixer-slider-tiny.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider:Tiny::figure_out_volume"
#line 122 "mixer-slider-tiny.gob"
	g_return_val_if_fail (self != NULL, (int )0);
#line 122 "mixer-slider-tiny.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_SLIDER_TINY (self), (int )0);
#line 309 "xfce-mixer-slider-tiny.c"
{
#line 122 "mixer-slider-tiny.gob"
	
		int	sy; /* size in pixels. */

		sy = widget->allocation.height; /* size */
		if (sy > 4) {
			sy -= 4;
			/* this is a hack 'cause I dont know how to get the height of the border of the progressbar yet ;) */
			y = (sy + 2 - y) * 100 / sy;
			if (y <= 0)
				y = 0;
		} else {
			y = 0;
		}

		if (y < 0) {
			y = 0;
		} else if (y > 100) {
			y = 100;
		}
		return y;
        }}
#line 333 "xfce-mixer-slider-tiny.c"
#undef __GOB_FUNCTION__

#line 144 "mixer-slider-tiny.gob"
gboolean 
xfce_mixer_slider_tiny_motion_cb (XfceMixerSliderTiny * self, GdkEventMotion * m, GtkWidget * widget)
#line 339 "xfce-mixer-slider-tiny.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider:Tiny::motion_cb"
#line 144 "mixer-slider-tiny.gob"
	g_return_val_if_fail (self != NULL, (gboolean )0);
#line 144 "mixer-slider-tiny.gob"
	g_return_val_if_fail (XFCE_IS_MIXER_SLIDER_TINY (self), (gboolean )0);
#line 346 "xfce-mixer-slider-tiny.c"
{
#line 145 "mixer-slider-tiny.gob"
	
		if (self->pressed) {
			int y = (int) m->y; /* pos */
			y = self_figure_out_volume(self, widget, y);
			self_set_vval (self, y);
			return TRUE;
		}
		return FALSE;
	}}
#line 358 "xfce-mixer-slider-tiny.c"
#undef __GOB_FUNCTION__

#line 155 "mixer-slider-tiny.gob"
XfceMixerControl * 
xfce_mixer_slider_tiny_new (void)
#line 364 "xfce-mixer-slider-tiny.c"
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider:Tiny::new"
{
#line 156 "mixer-slider-tiny.gob"
	
		return XFCE_MIXER_CONTROL(GET_NEW);
	}}
#line 372 "xfce-mixer-slider-tiny.c"
#undef __GOB_FUNCTION__

#line 160 "mixer-slider-tiny.gob"
static void 
___8_xfce_mixer_slider_tiny_value_changed (XfceMixerControl * pself G_GNUC_UNUSED)
#line 378 "xfce-mixer-slider-tiny.c"
#define PARENT_HANDLER(___pself) \
	{ if(XFCE_MIXER_CONTROL_CLASS(parent_class)->value_changed) \
		(* XFCE_MIXER_CONTROL_CLASS(parent_class)->value_changed)(___pself); }
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider:Tiny::value_changed"
#line 160 "mixer-slider-tiny.gob"
	g_return_if_fail (pself != NULL);
#line 160 "mixer-slider-tiny.gob"
	g_return_if_fail (XFCE_IS_MIXER_CONTROL (pself));
#line 388 "xfce-mixer-slider-tiny.c"
{
#line 162 "mixer-slider-tiny.gob"
	
		gint v;

		Self *self;

		self = SELF (pself);

		v = xfce_mixer_control_calc_num_value (pself);

		gtk_progress_bar_set_fraction (GTK_PROGRESS_BAR (self->progress), ((gdouble) v) / 100.0);
	}}
#line 402 "xfce-mixer-slider-tiny.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER

#line 174 "mixer-slider-tiny.gob"
static void 
___9_xfce_mixer_slider_tiny_vcname_changed (XfceMixerControl * pself G_GNUC_UNUSED)
#line 409 "xfce-mixer-slider-tiny.c"
#define PARENT_HANDLER(___pself) \
	{ if(XFCE_MIXER_CONTROL_CLASS(parent_class)->vcname_changed) \
		(* XFCE_MIXER_CONTROL_CLASS(parent_class)->vcname_changed)(___pself); }
{
#define __GOB_FUNCTION__ "Xfce:Mixer:Slider:Tiny::vcname_changed"
#line 174 "mixer-slider-tiny.gob"
	g_return_if_fail (pself != NULL);
#line 174 "mixer-slider-tiny.gob"
	g_return_if_fail (XFCE_IS_MIXER_CONTROL (pself));
#line 419 "xfce-mixer-slider-tiny.c"
{
#line 176 "mixer-slider-tiny.gob"
	
		Self *self;
		char *sanename;
		PARENT_HANDLER (pself);

		self = SELF (pself);
		sanename = xfce_mixer_control_calc_sanename (pself);
/*		gtk_label_set_text (GTK_LABEL (self->label), sanename);*/
		if (sanename && self->progress) {
			gtk_tooltips_set_tip (tooltips, GTK_WIDGET (self->progress), sanename, NULL);
		}
		g_free (sanename);
	}}
#line 435 "xfce-mixer-slider-tiny.c"
#undef __GOB_FUNCTION__
#undef PARENT_HANDLER
